# "Categories": ["Sub Categories 1", "Sub Categories 2"]

Categories_and_Subcategories = {
    "Stationary Combustion": ["Fuel"],
    "Mobile Combustion": ["Fuel", "Vehicles", "Road Travel", "Rail Freight"],
    "Refrigerants and Fugitive Gases": ["Refrigerants and Fugitive Gases"],
    "Purchased Electricity": ["Electricity", "Energy Services", "Utilities"],
    "Purchased Heat & Steam": ["Heat and Steam", "Energy Services", "Utilities"],
    "Purchased Cooling": ["Electricity", "Energy Services", "Utilities"],
    "Purchased Goods & Services": [
        "Agriculture/Hunting/Forestry/Fishing",
        "Arable Farming",
        "Building Materials",
        "Ceramic Goods",
        "Chemical Products",
        "Clothing and Footwear",
        "Cloud Computing - CPU",
        "Cloud Computing - Memory",
        "Cloud Computing - Networking",
        "Cloud Computing - Storage",
        "Consumer Goods Rental",
        "DIY and Gardening Equipment",
        "Domestic Services",
        "Education",
        "Electrical Equipment",
        "Electronics",
        "Equipment Rental",
        "Fabricated Metal Products",
        "Financial Services",
        "Fishing/Aquaculture/Hunting",
        "Food and Beverage Services",
        "Food/Beverages/Tobacco",
        "Furnishings and Household",
        "General Retail",
        "Glass and Glass Products",
        "Government Activities",
        "Health and Social Care",
        "Health Care",
        "Housing",
        "Information and Communication Services",
        "Insurance Services",
        "Livestock Farming",
        "Machinery",
        "Maintenance and Repair",
        "Manufacturing",
        "Metals",
        "Mined Materials",
        "Mining",
        "Non-profit Activities",
        "Office Equipment",
        "Operational Activities",
        "Organic Products",
        "Other Materials",
        "Paper and Cardboard",
        "Paper Products",
        "Pavement and Surfacing",
        "Personal Care and Accessories",
        "Plastics and Rubber Products",
        "Professional Services and Activities",
        "Real Estate",
        "Recreation and Culture",
        "Social Care",
        "Textiles",
        "Timber and Forestry Products",
        "Utilities",
        "Vehicle Maintenance and Services",
        "Vehicle Parts",
        "Waste Management",
        "Water Supply",
        "Water Treatment",
        "Wholesale Trade",
    ],
    "Capital Goods": [
        "Construction",
        "Electrical Equipment",
        "Electronics",
        "Furnishings and Household",
        "Health Care",
        "Machinery",
        "Office Equipment",
    ],
    "Fuel & Energy Related Activities": ["Electricity", "Fuel"],
    "Upstream Transportation & Distribution": [
        "Air Freight",
        "Energy Services",
        "Rail Freight",
        "Road Freight",
        "Sea Freight",
        "Transport Services and Warehousing",
        "Vehicles",
    ],
    "Waste Generated in Operations": [
        "Construction Waste",
        "Electrical Waste",
        "Food and Organic Waste",
        "General Waste",
        "Glass Waste",
        "Metal Waste",
        "Paper and Cardboard Waste",
        "Plastic Waste",
        "Waste Management",
        "Water Treatment",
    ],
    "Business Travel": [
        "Restaurants and Accommodation",
        "Accommodation",
        "Air Travel",
        "Rail Travel",
        "Road Travel",
        "Sea Travel",
        "Tickets and Passes",
        "Vehicles",
    ],
    "Employee Commuting": [
        "Homeworking",
        "Rail Travel",
        "Road Travel",
        "Tickets and Passes",
        "Vehicles",
    ],
    "Upstream Leased Assets": ["Facility", "Housing", "Real Estate"],
    "Downstream Transportation & Distribution": [
        "Air Freight",
        "Energy Services",
        "Infrastructure",
        "Rail Freight",
        "Road Freight",
        "Sea Freight",
        "Transport Services and Warehousing",
    ],
    "Processing of Sold Products": [
        "Cloud Computing - CPU",
        "Cloud Computing - Memory",
        "Cloud Computing - Networking",
        "Cloud Computing - Storage",
        "Information and Communication Services",
    ],
    "End of Life Treatment of Sold Products": ["Electricity", "Fuel"],
    "Downstream Leased Assets": [
        "Equipment Rental",
        "Facility",
        "Housing",
        "Real Estate",
    ],
}
# Sub Categories which do not have a lot of results, hence, where they are found, it has been specially mentioned.
Missing_SubCategories = {
    "Clothing and Footwear": [{"source": "EXIOBASE", "year": 2019}],
    "DIY and Gardening Equipment": [{"source": "EPA", "year": 2019}],
    "Domestic Services": [{"source": "EXIOBASE", "year": 2019}],
    "Education": [{"source": "EXIOBASE", "year": 2019}],
    "Electric Equipment": [{"source": "EXIOBASE", "year": 2019}],
    "Equipment Rental": [{"source": "EXIOBASE", "year": 2019}],
    "Food and Beverage Services": [{"source": "EPA", "year": 2019}],
    "Food and Beverage Service": [{"source": "BEIS", "year": 2019}],
    "Furnishings and Household": [{"source": "EXIOBASE", "year": 2019}],
    "General Retail": [{"source": "EXIOBASE", "year": 2019}],
    "Government Activities": [{"source": "EXIOBASE", "year": 2019}],
    "Health and Social work": [{"source": "EXIOBASE", "year": 2019}],
    "Post and Telecommunication": [{"source": "EXIPOBASE", "year": 2019}],
    "Office Equipment": [
        {"source": "EXIOBASE", "year": 2019},
        {"source": "EPA", "year": 2019},
        {"source": "EPA", "year": 2019},
    ],
    "Paper Products": [{"source": "EXIOBASE", "year": 2019}],
    "Plastic and Rubber Products": [{"source": "EXIOBASE", "year": 2019}],
    "Professional Services and Activities": [
        {"source": "EXIOBASE", "year": 2019},
    ],
    "Waste Management": [{"source": "EXIOBASE", "year": 2019}],
    "Water Supply": [{"source": "Ecoinvent", "year": 2015}],
}
