# Generated by Django 5.1.1 on 2024-10-24 06:14

import datametric.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=400)),
                ('description', models.CharField(max_length=1000)),
                ('response_type', models.CharField(choices=[('Integer', 'Integer'), ('Float', 'Float'), ('String', 'String'), ('Boolean', 'Boolean'), ('Array of Objects', 'Array of Objects'), ('Object', 'Object')], default='String', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response_type', models.CharField(choices=[('Integer', 'Integer'), ('Float', 'Float'), ('String', 'String'), ('Boolean', 'Boolean'), ('Array of Objects', 'Array of Objects'), ('Object', 'Object')], default='String', max_length=20)),
                ('number_holder', models.FloatField(default=None, null=True)),
                ('string_holder', models.CharField(default=None, null=True)),
                ('json_holder', models.JSONField(default=None, null=True)),
                ('boolean_holder', models.BooleanField(default=True, null=True)),
                ('index', models.IntegerField(default=0)),
                ('value', models.JSONField(default=None, null=True)),
                ('metric_name', models.CharField(default='Not Set')),
                ('is_calculated', models.BooleanField(default=False)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1999), django.core.validators.MaxValueValidator(2100)])),
                ('month', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('user_id', models.PositiveIntegerField(default=1)),
                ('client_id', models.PositiveIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmissionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emission_id', models.UUIDField(blank=True, null=True)),
                ('activity_id', models.CharField(max_length=200)),
                ('activity', models.TextField()),
                ('index', models.PositiveIntegerField()),
                ('co2e_total', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('co2', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('n2o', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('co2e_other', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('ch4', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('calculation_method', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=10)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('scope', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=300)),
                ('unit', models.CharField(max_length=50)),
                ('unit1', models.CharField(blank=True, max_length=50, null=True)),
                ('unit2', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('quantity2', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('consumption', models.DecimalField(decimal_places=3, max_digits=20)),
                ('type_of', models.CharField(blank=True, db_column='type', max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FieldGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('meta_data', models.JSONField()),
                ('ui_schema', models.JSONField()),
                ('schema', datametric.models.OrderedJSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                ('slug', models.CharField(db_index=True, max_length=500, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RawResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', datametric.models.OrderedJSONField(default=list)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1999), django.core.validators.MaxValueValidator(2100)])),
                ('month', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
