# Generated by Django 5.1.1 on 2024-10-24 06:14

import authentication.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('datametric', '0001_initial'),
        ('materiality_dashboard', '0001_initial'),
        ('sustainapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='corporate',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity'),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='data_metric',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='data_metric_points', to='datametric.datametric'),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='locale',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location'),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization'),
        ),
        migrations.AddField(
            model_name='path',
            name='disclosure',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paths', to='materiality_dashboard.disclosure'),
        ),
        migrations.AddField(
            model_name='fieldgroup',
            name='path',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fieldgroups', to='datametric.path'),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datametric.path'),
        ),
        migrations.AddField(
            model_name='datametric',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datametric.path'),
        ),
        migrations.AddField(
            model_name='rawresponse',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, on_delete=django.db.models.deletion.CASCADE, related_name='raw_responses', to='authentication.client'),
        ),
        migrations.AddField(
            model_name='rawresponse',
            name='corporate',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity'),
        ),
        migrations.AddField(
            model_name='rawresponse',
            name='locale',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location'),
        ),
        migrations.AddField(
            model_name='rawresponse',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization'),
        ),
        migrations.AddField(
            model_name='rawresponse',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datametric.path'),
        ),
        migrations.AddField(
            model_name='rawresponse',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='raw_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emissionanalysis',
            name='raw_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='raw_response',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response_points', to='datametric.rawresponse'),
        ),
    ]
