# Generated by Django 4.2.4 on 2024-06-05 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datametric', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapoint',
            name='slug',
        ),
        migrations.AddField(
            model_name='datapoint',
            name='path',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='datametric.path'),
            preserve_default=False,
        ),
    ]
