# Generated by Django 4.2.4 on 2024-10-24 05:40

import authentication.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_client_alter_customuser_client'),
        ('datametric', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawresponse',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, on_delete=django.db.models.deletion.CASCADE, related_name='raw_responses', to='authentication.client'),
        ),
    ]
