# Generated by Django 4.2.4 on 2024-06-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datametric', '0002_remove_datapoint_slug_datapoint_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawresponse',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rawresponse',
            name='month',
            field=models.CharField(default='Jan', null=True),
        ),
        migrations.AddField(
            model_name='rawresponse',
            name='year',
            field=models.IntegerField(default=2024, null=True),
        ),
    ]
