# Generated by Django 4.2.4 on 2025-01-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datametric', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionanalysis',
            name='unique_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emissionanalysis',
            name='ch4',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='emissionanalysis',
            name='co2',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='emissionanalysis',
            name='co2e_other',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='emissionanalysis',
            name='co2e_total',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='emissionanalysis',
            name='consumption',
            field=models.DecimalField(decimal_places=20, max_digits=40),
        ),
        migrations.AlterField(
            model_name='emissionanalysis',
            name='n2o',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='emissionanalysis',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='emissionanalysis',
            name='quantity2',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=40, null=True),
        ),
    ]
