# Generated by Django 4.2.4 on 2025-05-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datametric', '0003_emissionanalysis_unique_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_id', models.CharField(max_length=100, unique=True)),
                ('activity_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('source_link', models.URLField(blank=True, null=True)),
                ('source_dataset', models.CharField(max_length=255)),
                ('uncertainty', models.FloatField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('year_released', models.IntegerField()),
                ('region', models.CharField(max_length=50)),
                ('region_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('unit_type', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('source_lca_activity', models.CharField(blank=True, max_length=255, null=True)),
                ('data_quality_flags', models.JSONField(default=list)),
                ('access_type', models.CharField(max_length=50)),
                ('supported_calculation_methods', models.JSONField(default=list)),
                ('factor', models.FloatField()),
                ('factor_calculation_method', models.CharField(max_length=50)),
                ('factor_calculation_origin', models.CharField(max_length=50)),
                ('constituent_gases', models.JSONField()),
                ('data_version', models.JSONField()),
                ('data_version_information', models.JSONField()),
                ('possible_filters', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
