# Generated by Django 4.2.4 on 2024-06-05 12:35

from django.db import migrations, models
import django.db.models.deletion


def populate_raw_response(apps, schema_editor):
    DataPoint = apps.get_model("datametric", "DataPoint")
    RawResponse = apps.get_model("datametric", "RawResponse")

    default_raw_response = RawResponse.objects.first()

    for datapoint in DataPoint.objects.all():
        if not datapoint.raw_response:
            datapoint.raw_response = default_raw_response
        datapoint.save()


class Migration(migrations.Migration):

    dependencies = [
        ('datametric', '0003_rawresponse_location_rawresponse_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=400)),
                ('description', models.CharField(max_length=1000)),
                ('response_type', models.CharField(choices=[('Integer', 'Integer'), ('Float', 'Float'), ('String', 'String'), ('Boolean', 'Boolean'), ('Array of Objects', 'Array of Objects'), ('Object', 'Object')], default='String', max_length=20)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datametric.path')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='description',
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='label',
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='name',
        ),
        migrations.AddField(
            model_name='datapoint',
            name='json_holder',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='number_holder',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='raw_response',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='response_points', to='datametric.rawresponse'),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='string_holder',
            field=models.CharField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='value',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.DeleteModel(
            name='ResponsePoint',
        ),
        migrations.AddField(
            model_name='datapoint',
            name='data_metric',
            field=models.ForeignKey(default=None,null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_metric_points', to='datametric.datametric'),
        ),
    ]
