# Generated by Django 4.2.4 on 2024-06-05 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datametric', '0004_datametric_remove_datapoint_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='raw_response',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='response_points', to='datametric.rawresponse'),
        ),
    ]
