# Generated by Django 4.2.4 on 2024-06-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datametric', '0005_alter_datapoint_raw_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
