# Generated by Django 4.2.4 on 2024-06-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datametric', '0006_datapoint_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='boolean_holder',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
