# Generated by Django 4.2.4 on 2024-06-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datametric', '0007_datapoint_boolean_holder'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='metric_name',
            field=models.CharField(default='Not Set'),
        ),
    ]
