# Generated by Django 4.2.4 on 2024-06-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datametric', '0008_datapoint_metric_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='is_calculated',
            field=models.BooleanField(default=False),
        ),
    ]
