# Generated by Django 4.2.4 on 2024-06-06 09:17

from django.db import migrations, models


def fix_data(apps, schema_editor):
    # Example cleanup code
    raw_response_model = apps.get_model("DataMetric", "RawResponse")
    for instance in raw_response_model.objects.all():
        if instance.month == "Jan":
            instance.month = 1  # or another appropriate integer value
            instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ("datametric", "0008_datapoint_metric_name"),
    ]

    operations = [
        migrations.RunPython(fix_data),
        migrations.AlterField(
            model_name="rawresponse",
            name="month",
            field=models.IntegerField(default=1, null=True),
        ),
    ]
