# Generated by Django 4.2.4 on 2024-06-06 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datametric", "0009_alter_rawresponse_month"),
        ("datametric", "0009_datapoint_is_calculated"),
    ]

    operations = []
