# Generated by Django 4.2.4 on 2024-06-06 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datametric", "0010_merge_20240606_1059"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datapoint",
            name="is_calculated",
        ),
        migrations.AddField(
            model_name="datapoint",
            name="location",
            field=models.CharField(default="Bangalore", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="datapoint",
            name="month",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="datapoint",
            name="year",
            field=models.IntegerField(
                default=2024,
                validators=[
                    django.core.validators.MinValueValidator(1999),
                    django.core.validators.MaxValueValidator(2100),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rawresponse",
            name="location",
            field=models.CharField(default="Bangalore", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rawresponse",
            name="month",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="rawresponse",
            name="year",
            field=models.IntegerField(
                default=2024,
                validators=[
                    django.core.validators.MinValueValidator(1999),
                    django.core.validators.MaxValueValidator(2100),
                ],
            ),
            preserve_default=False,
        ),
    ]
