# Generated by Django 4.2.4 on 2024-06-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "datametric",
            "0011_remove_datapoint_is_calculated_datapoint_location_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="datapoint",
            name="is_calculated",
            field=models.BooleanField(default=False),
        ),
    ]
