# Generated by Django 4.2.4 on 2024-06-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datametric", "0012_datapoint_is_calculated"),
    ]

    operations = [
        migrations.AddField(
            model_name="datapoint",
            name="client_id",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="datapoint",
            name="user_id",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
