# Generated by Django 4.2.4 on 2024-06-26 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("datametric", "0013_datapoint_client_id_datapoint_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmissionAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("activity_id", models.CharField(max_length=200)),
                ("index", models.PositiveIntegerField()),
                ("co2e_total", models.DecimalField(decimal_places=3, max_digits=10)),
                ("co2", models.DecimalField(decimal_places=3, max_digits=10)),
                ("n2o", models.DecimalField(decimal_places=3, max_digits=10)),
                ("co2e_other", models.DecimalField(decimal_places=3, max_digits=10)),
                ("ch4", models.DecimalField(decimal_places=3, max_digits=10)),
                ("calculation_method", models.CharField(max_length=10)),
                ("category", models.CharField(max_length=100)),
                ("region", models.CharField(max_length=10)),
                ("year", models.IntegerField()),
                ("name", models.CharField(max_length=300)),
                (
                    "raw_response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="datametric.rawresponse",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
