# Generated by Django 4.2.4 on 2024-07-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datametric", "0014_emissionanalysis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emissionanalysis",
            name="ch4",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="emissionanalysis",
            name="co2",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="emissionanalysis",
            name="co2e_other",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="emissionanalysis",
            name="n2o",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
    ]
