# Generated by Django 4.2.4 on 2024-07-01 10:34

import datametric.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datametric', '0015_alter_emissionanalysis_ch4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldgroup',
            name='schema',
            field=datametric.models.OrderedJSONField(),
        ),
    ]
