# Generated by Django 4.2.4 on 2024-07-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datametric", "0015_alter_emissionanalysis_ch4_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emissionanalysis",
            name="co2e_total",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
    ]
