# Generated by Django 4.2.4 on 2024-07-04 04:11

import datametric.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datametric', '0016_alter_emissionanalysis_co2e_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldgroup',
            name='schema',
            field=datametric.models.OrderedJSONField(),
        ),
    ]
