# Generated by Django 4.2.4 on 2024-07-09 08:32

import datametric.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datametric', '0017_alter_fieldgroup_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawresponse',
            name='data',
            field=datametric.models.OrderedJSONField(default=list),
        ),
    ]
