# Generated by Django 4.2.4 on 2024-07-16 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0003_delete_logincounter'),
        ('datametric', '0019_datapoint_corporate_datapoint_locale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawresponse',
            name='corporate',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity'),
        ),
        migrations.AlterField(
            model_name='rawresponse',
            name='locale',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location'),
        ),
        migrations.AlterField(
            model_name='rawresponse',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rawresponse',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization'),
        ),
    ]
