# Generated by Django 4.2.4 on 2024-07-17 08:43

from django.db import migrations


def add_locationid(apps, schema_editor):

    rr = apps.get_model("datametric", "RawResponse")
    loc = apps.get_model("sustainapp", "Location")

    rr_objs = rr.objects.all()

    for obj in rr_objs:

        try:
            print(f"id of the rr is {obj.id} and loc is {obj.location}")
            if obj.location is not None:
                print(f"\t the locale is {obj.locale}")

                obj_loc = loc.objects.get(name=obj.location)
                obj.locale = obj_loc
                obj.save()

        except Exception as e:
            print("Error : ", e)


def rev_add_locationid(apps, schema_editor):

    rr = apps.get_model("datametric", "RawResponse")
    loc = apps.get_model("sustainapp", "Location")

    rr_objs = rr.objects.all().filter(location__isnull=False)

    for obj in rr_objs:
        obj.location = obj.locale.name
        obj.locale = None
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        (
            "datametric",
            "0020_alter_rawresponse_corporate_alter_rawresponse_locale_and_more",
        ),
        ("sustainapp", "0003_delete_logincounter"),
    ]

    operations = [
        migrations.RunPython(add_locationid, rev_add_locationid),
    ]
