# Generated by Django 4.2.4 on 2024-07-17 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datametric', '0021_auto_20240717_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapoint',
            name='location',
        ),
        migrations.RemoveField(
            model_name='rawresponse',
            name='location',
        ),
    ]
