# Generated by Django 4.2.4 on 2024-07-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datametric', '0022_remove_datapoint_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionanalysis',
            name='ch4',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='emissionanalysis',
            name='co2',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='emissionanalysis',
            name='co2e_other',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='emissionanalysis',
            name='co2e_total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='emissionanalysis',
            name='n2o',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
    ]
