# Generated by Django 4.2.4 on 2024-07-29 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datametric', '0023_alter_emissionanalysis_ch4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='raw_response',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response_points', to='datametric.rawresponse'),
        ),
    ]
