# Generated by Django 4.2.4 on 2024-07-29 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datametric', '0024_alter_datapoint_raw_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionanalysis',
            name='raw_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
    ]
