# Generated by Django 4.2.4 on 2024-08-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datametric', '0025_alter_emissionanalysis_raw_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionanalysis',
            name='consumption',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emissionanalysis',
            name='unit',
            field=models.CharField(default='kg', max_length=10),
            preserve_default=False,
        ),
    ]
