# Generated by Django 4.2.4 on 2024-08-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datametric', '0026_emissionanalysis_consumption_emissionanalysis_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionanalysis',
            name='unit',
            field=models.CharField(max_length=50),
        ),
    ]
