# Generated by Django 4.2.4 on 2024-08-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datametric', '0027_alter_emissionanalysis_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionanalysis',
            name='month',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emissionanalysis',
            name='scope',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
