# Generated by Django 4.2.4 on 2024-08-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datametric', '0028_emissionanalysis_month_emissionanalysis_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionanalysis',
            name='subcategory',
            field=models.CharField(default='something', max_length=255),
            preserve_default=False,
        ),
    ]
