# Generated by Django 4.2.4 on 2024-08-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datametric', '0029_emissionanalysis_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionanalysis',
            name='activity',
            field=models.TextField(default='something'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emissionanalysis',
            name='scope',
            field=models.CharField(max_length=10),
        ),
    ]
