# Generated by Django 4.2.4 on 2024-08-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datametric', '0030_emissionanalysis_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionanalysis',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='emissionanalysis',
            name='quantity2',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='emissionanalysis',
            name='unit2',
            field=models.CharField(default='something', max_length=50),
            preserve_default=False,
        ),
    ]
