# Generated by Django 4.2.4 on 2024-08-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datametric', '0031_emissionanalysis_quantity_emissionanalysis_quantity2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionanalysis',
            name='unit2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
