# Generated by Django 4.2.4 on 2024-08-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datametric', '0032_alter_emissionanalysis_unit2'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionanalysis',
            name='unit1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
