# Generated by Django 4.2.4 on 2024-09-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datametric', '0033_emissionanalysis_unit1'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionanalysis',
            name='type_of',
            field=models.CharField(db_column='type', default='PassengerOverDistance', max_length=255),
            preserve_default=False,
        ),
    ]
