# Generated by Django 4.2.4 on 2024-09-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datametric', '0034_emissionanalysis_type_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionanalysis',
            name='type_of',
            field=models.CharField(blank=True, db_column='type', max_length=255, null=True),
        ),
    ]
