# Generated by Django 4.2.4 on 2024-09-17 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiality_dashboard', '0010_alter_managementapproachquestion_negative_impact_involvement_description'),
        ('datametric', '0035_alter_emissionanalysis_type_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='dislcosure',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materiality_dashboard.disclosure'),
        ),
    ]
