# Generated by Django 4.2.4 on 2024-09-17 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datametric', '0036_path_dislcosure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='path',
            old_name='dislcosure',
            new_name='disclosure',
        ),
    ]
