# Generated by Django 4.2.4 on 2024-09-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datametric', '0037_rename_dislcosure_path_disclosure'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionanalysis',
            name='emission_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
