# Generated by Django 4.2.4 on 2024-09-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datametric', '0038_emissionanalysis_emission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='slug',
            field=models.CharField(db_index=True, max_length=500, unique=True),
        ),
    ]
