# Generated by Django 4.2.4 on 2024-09-24 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiality_dashboard', '0014_alter_disclosure_unique_together'),
        ('datametric', '0039_alter_path_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='disclosure',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paths', to='materiality_dashboard.disclosure'),
        ),
    ]
