# Generated by Django 4.2.4 on 2024-08-27 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_logincounter'),
        ('sustainapp', '0004_report_investment_corporates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approach', models.CharField(blank=True, choices=[('In accordance with', 'In accordance with'), ('With Reference to', 'With Reference to')], max_length=100, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('outdated', 'Outdated'), ('archived', 'Archived')], default='in_progress', max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client')),
                ('corporate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sustainapp.corporateentity')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.framework')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.framework')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialityImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('impact_overview', models.TextField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_impacts', to='materiality_dashboard.materialityassessment')),
                ('impact_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materiality_dashboard.impacttype')),
                ('material_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiality_dashboard.materialtopic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialityChangeConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change_made', models.BooleanField()),
                ('reason_for_change', models.TextField(blank=True, null=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='change_confirmation', to='materiality_dashboard.materialityassessment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialityAssessmentProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process_description', models.TextField(blank=True, null=True)),
                ('impact_assessment_process', models.TextField(blank=True, null=True)),
                ('stakeholder_others', models.TextField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_process', to='materiality_dashboard.materialityassessment')),
                ('selected_stakeholders', models.ManyToManyField(blank=True, to='materiality_dashboard.stakeholder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='materialityassessment',
            name='reporting_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiality_dashboard.reportingperiod'),
        ),
        migrations.CreateModel(
            name='ManagementApproachQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_text', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_approach_questions', to='materiality_dashboard.materialityassessment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Disclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiality_dashboard.materialtopic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentTopicSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_topics', to='materiality_dashboard.materialityassessment')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiality_dashboard.materialtopic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentDisclosureSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disclosure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiality_dashboard.disclosure')),
                ('topic_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_disclosures', to='materiality_dashboard.assessmenttopicselection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
