# Generated by Django 4.2.4 on 2024-08-28 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiality_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stakeholder',
            new_name='StakeholderEngagement',
        ),
    ]
