# Generated by Django 4.2.4 on 2024-10-18 08:09

from django.db import migrations, models
import django.db.models.deletion
import sustainapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sustainapp', '0001_initial'),
        ('materiality_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtopic',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.framework'),
        ),
        migrations.AddField(
            model_name='materialityimpact',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_impacts', to='materiality_dashboard.materialityassessment'),
        ),
        migrations.AddField(
            model_name='materialityimpact',
            name='material_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiality_dashboard.materialtopic'),
        ),
        migrations.AddField(
            model_name='materialitychangeconfirmation',
            name='assessment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='change_confirmation', to='materiality_dashboard.materialityassessment'),
        ),
        migrations.AddField(
            model_name='materialityassessmentprocess',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_process', to='materiality_dashboard.materialityassessment'),
        ),
        migrations.AddField(
            model_name='materialityassessmentprocess',
            name='selected_stakeholders',
            field=models.ManyToManyField(blank=True, to='materiality_dashboard.stakeholderengagement'),
        ),
        migrations.AddField(
            model_name='materialityassessment',
            name='client',
            field=models.ForeignKey(default=sustainapp.models.Client.get_default_client, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.client'),
        ),
        migrations.AddField(
            model_name='materialityassessment',
            name='corporate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sustainapp.corporateentity'),
        ),
        migrations.AddField(
            model_name='materialityassessment',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.framework'),
        ),
        migrations.AddField(
            model_name='materialityassessment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization'),
        ),
        migrations.AddField(
            model_name='managementapproachquestion',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_approach_questions', to='materiality_dashboard.materialityassessment'),
        ),
        migrations.AddField(
            model_name='disclosure',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiality_dashboard.materialtopic'),
        ),
        migrations.AddField(
            model_name='assessmenttopicselection',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_topics', to='materiality_dashboard.materialityassessment'),
        ),
        migrations.AddField(
            model_name='assessmenttopicselection',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materiality_dashboard.materialtopic'),
        ),
        migrations.AddField(
            model_name='assessmentdisclosureselection',
            name='disclosure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materiality_dashboard.disclosure'),
        ),
        migrations.AddField(
            model_name='assessmentdisclosureselection',
            name='topic_selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_disclosures', to='materiality_dashboard.assessmenttopicselection'),
        ),
        migrations.AlterUniqueTogether(
            name='materialtopic',
            unique_together={('identifier', 'framework')},
        ),
        migrations.AlterUniqueTogether(
            name='disclosure',
            unique_together={('identifier', 'description', 'topic')},
        ),
    ]
