# Generated by Django 4.2.4 on 2024-08-29 04:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('materiality_dashboard', '0002_rename_stakeholder_stakeholderengagement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialityassessment',
            name='reporting_period',
        ),
        migrations.AddField(
            model_name='materialityassessment',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialityassessment',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ReportingPeriod',
        ),
    ]
