# Generated by Django 4.2.4 on 2024-08-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiality_dashboard', '0003_remove_materialityassessment_reporting_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtopic',
            name='esg_category',
            field=models.CharField(choices=[('environmental', 'Environmental'), ('social', 'Social'), ('governance', 'Governance')], default='Environment', max_length=20),
            preserve_default=False,
        ),
    ]
