# Generated by Django 4.2.4 on 2024-08-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiality_dashboard', '0004_materialtopic_esg_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialityassessment',
            name='approach',
            field=models.CharField(blank=True, choices=[('GRI: In accordance with', 'In accordance with'), ('GRI: With Reference to', 'With Reference to')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='materialtopic',
            name='esg_category',
            field=models.CharField(choices=[('environment', 'Environment'), ('social', 'Social'), ('governance', 'Governance')], max_length=20),
        ),
    ]
