# Generated by Django 4.2.4 on 2024-08-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiality_dashboard', '0005_alter_materialityassessment_approach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialityassessment',
            name='approach',
            field=models.CharField(blank=True, choices=[('GRI: In accordance with', 'GRI: In accordance with'), ('GRI: With Reference to', 'GRI: In accordance with')], max_length=100, null=True),
        ),
    ]
