# Generated by Django 4.2.4 on 2024-09-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiality_dashboard', '0006_alter_materialityassessment_approach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialityimpact',
            name='impact_type',
            field=models.CharField(choices=[('Positive Impact', 'positive impact'), ('Negative Impact', 'negative impact')], default='Negative', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ImpactType',
        ),
    ]
