# Generated by Django 4.2.4 on 2024-09-02 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiality_dashboard', '0007_alter_materialityimpact_impact_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managementapproachquestion',
            old_name='question_text',
            new_name='negative_impact_involvement_description',
        ),
        migrations.RenameField(
            model_name='managementapproachquestion',
            old_name='answer',
            new_name='stakeholder_engagement_effectiveness_description',
        ),
    ]
