# Generated by Django 4.2.4 on 2024-09-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiality_dashboard', '0008_rename_question_text_managementapproachquestion_negative_impact_involvement_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialityassessment',
            name='esg_selected',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
