# Generated by Django 4.2.4 on 2024-09-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiality_dashboard', '0009_materialityassessment_esg_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementapproachquestion',
            name='negative_impact_involvement_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
