# Generated by Django 4.2.4 on 2024-09-19 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiality_dashboard', '0010_alter_managementapproachquestion_negative_impact_involvement_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentdisclosureselection',
            name='disclosure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materiality_dashboard.disclosure'),
        ),
        migrations.AlterField(
            model_name='assessmenttopicselection',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materiality_dashboard.materialtopic'),
        ),
    ]
