# Generated by Django 4.2.4 on 2024-09-23 11:49

from django.db import migrations, models
import uuid


# * Create a method that adds a unique identifier to the disclosure and material topic models
# * The identifier should be a combination of the disclosure name and the material topic name
def add_identifier(apps, schema_editor):
    Disclosure = apps.get_model("materiality_dashboard", "Disclosure")
    MaterialTopic = apps.get_model("materiality_dashboard", "MaterialTopic")
    for disclosure in Disclosure.objects.all():
        disclosure.identifier = f"{uuid.uuid4()}"
        disclosure.save()
    for material_topic in MaterialTopic.objects.all():
        material_topic.identifier = f"{uuid.uuid4()}"
        material_topic.save()



class Migration(migrations.Migration):

    dependencies = [
        (
            "materiality_dashboard",
            "0011_alter_assessmentdisclosureselection_disclosure_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="disclosure",
            name="identifier",
            field=models.CharField(max_length=255, null=True, blank=True, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="materialtopic",
            name="identifier",
            field=models.CharField(max_length=255, null=True, blank=True, unique=True),
            preserve_default=False,
        ),
        migrations.RunPython(add_identifier),
    ]
