# Generated by Django 4.2.4 on 2024-09-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0006_alter_trackdashboard_report_name'),
        ('materiality_dashboard', '0012_disclosure_identifier_materialtopic_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disclosure',
            name='identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='materialtopic',
            name='identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='disclosure',
            unique_together={('identifier', 'description')},
        ),
        migrations.AlterUniqueTogether(
            name='materialtopic',
            unique_together={('identifier', 'framework')},
        ),
    ]
