# Generated by Django 4.2.4 on 2024-09-24 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiality_dashboard', '0013_alter_disclosure_identifier_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='disclosure',
            unique_together={('identifier', 'description', 'topic')},
        ),
    ]
