# Generated by Django 4.2.4 on 2024-09-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiality_dashboard', '0014_alter_disclosure_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='disclosure',
            name='category',
            field=models.CharField(blank=True, choices=[('topic_disclosure', 'Topic Dislcosure'), ('topic_management_dislcosure', 'Topic Management Dislcosure')], default=True, max_length=255, null=True),
        ),
    ]
