# Generated by Django 4.2.4 on 2024-09-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiality_dashboard', '0015_disclosure_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disclosure',
            name='category',
            field=models.CharField(blank=True, choices=[('topic_disclosure', 'Topic Dislcosure'), ('topic_management_dislcosure', 'Topic Management Dislcosure')], default=None, max_length=255, null=True),
        ),
    ]
