# Generated by Django 4.2.4 on 2024-10-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiality_dashboard', '0017_indicator_subindicator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialtopic',
            name='esg_category',
            field=models.CharField(choices=[('environment', 'Environment'), ('social', 'Social'), ('governance', 'Governance'), ('general', 'General')], max_length=20),
        ),
    ]
