# Generated by Django 4.2.4 on 2025-06-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcfd_framework', '0002_coreelements_recommendeddisclosures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacollectionscreen',
            name='name',
            field=models.CharField(help_text='Name of the data collection screen.', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicaldatacollectionscreen',
            name='name',
            field=models.CharField(help_text='Name of the data collection screen.', max_length=255),
        ),
    ]
