# Generated by Django 4.2.4 on 2025-06-12 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcfd_framework', '0004_selecteddisclosures_historicalselecteddisclosures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalselecteddisclosures',
            old_name='corporate_entity',
            new_name='corporate',
        ),
        migrations.RenameField(
            model_name='selecteddisclosures',
            old_name='corporate_entity',
            new_name='corporate',
        ),
    ]
