# Generated by Django 4.2.4 on 2025-06-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcfd_framework', '0006_historicaltcfdreportinginformation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltcfdreportinginformation',
            name='sector',
            field=models.CharField(blank=True, help_text="Only required if sector_type is 'financial'", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tcfdreportinginformation',
            name='sector',
            field=models.CharField(blank=True, help_text="Only required if sector_type is 'financial'", max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='HistoricalSector',
        ),
        migrations.DeleteModel(
            name='Sector',
        ),
    ]
