# Generated by Django 4.2.4 on 2025-02-09 12:53

import apps.supplier_assessment.utils.snowflake
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_assessment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalstakeholdergroup',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='stakeholdergroup',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='historicalstakeholder',
            name='id',
            field=models.PositiveBigIntegerField(db_index=True, default=apps.supplier_assessment.utils.snowflake.generate_snowflake_id, editable=False),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='id',
            field=models.PositiveBigIntegerField(default=apps.supplier_assessment.utils.snowflake.generate_snowflake_id, editable=False, primary_key=True, serialize=False),
        ),
    ]
