# Generated by Django 4.2.4 on 2025-02-09 14:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplier_assessment', '0002_rename_user_historicalstakeholdergroup_created_by_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stakeholdergroup',
            unique_together={('name', 'created_by')},
        ),
    ]
