# Generated by Django 4.2.4 on 2025-02-12 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0014_merge_20250210_0558'),
        ('supplier_assessment', '0007_alter_stakeholdergroup_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stakeholdergroup',
            unique_together={('name', 'organization')},
        ),
    ]
