# Generated by Django 4.2.4 on 2025-02-14 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_assessment', '0008_alter_stakeholdergroup_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stakeholder',
            options={'ordering': ['-created_at']},
        ),
    ]
