# Generated by Django 4.2 on 2025-05-08 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0023_alter_corporateentity_employeecount_and_more'),
        ('v2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportingforentities',
            name='corporate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity'),
        ),
        migrations.AlterField(
            model_name='submissioninformation',
            name='corporate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity'),
        ),
    ]
