# Generated by Django 4.2 on 2025-05-08 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0023_alter_corporateentity_employeecount_and_more'),
        ('v2', '0002_alter_reportingforentities_corporate_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submissioninformation',
            unique_together={('organization', 'corporate', 'screen')},
        ),
    ]
