# Generated by Django 4.2 on 2025-05-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0003_alter_submissioninformation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreportingforentities',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('incomplete', 'Incomplete'), ('in_progress', 'In Progress')], default='incomplete', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalsubmissioninformation',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('incomplete', 'Incomplete'), ('in_progress', 'In Progress')], default='incomplete', max_length=20),
        ),
        migrations.AddField(
            model_name='reportingforentities',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('incomplete', 'Incomplete'), ('in_progress', 'In Progress')], default='incomplete', max_length=20),
        ),
        migrations.AddField(
            model_name='submissioninformation',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('incomplete', 'Incomplete'), ('in_progress', 'In Progress')], default='incomplete', max_length=20),
        ),
    ]
