# Generated by Django 4.2.4 on 2025-05-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0004_historicalreportingforentities_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreportingforentities',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsubmissioninformation',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportingforentities',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissioninformation',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
