# Generated by Django 5.2.1 on 2025-05-28 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0023_alter_corporateentity_employeecount_and_more'),
        ('v2', '0006_historicalbills211report_bills211report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills211report',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canada_bill_s211_v2_report', to='sustainapp.report'),
        ),
    ]
