# Generated by Django 4.2.4 on 2025-06-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0007_alter_bills211report_report'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bills211report',
            name='unique_report_screen',
        ),
        migrations.AddConstraint(
            model_name='bills211report',
            constraint=models.UniqueConstraint(fields=('report', 'screen'), name='unique_report_screen'),
        ),
    ]
