from esg_report.models import Report


class ScreenNineService:
    def __init__(self, report_id: int) -> None:
        self.report_id = report_id
        self.report = Report.objects.get(id=report_id)

        self.slugs = {
            0: "gri-governance-structure-2-9-a-governance_structure",
            1: "gri-governance-structure-2-9-b-committees",
            2: "gri-governance-structure-2-9-c-composition",
            3: "gri-governance-nomination-2-10-a-nomination",
            4: "gri-governance-nomination-2-10-b-criteria",
            5: "gri-governance-nomination-2-10-b-consideration_and_selection",
            6: "gri-governance-chair_of_board-2-11-b-chair",
            7: "gri-economic-proportion_of_senior_management-local_community-202-2a",
            8: "gri-economic-proportion_of_senior_management-senior_management-202-2b",
            9: "gri-economic-proportion_of_senior_management-local-202-2c",
            10: "gri-economic-proportion_of_senior_management-operation-202-2d",
            11: "gri-governance-management_of_impact-2-12-a-senior_executives",
            12: "gri-governance-management_of_impact-2-12-b-due_diligence",
            13: "gri-governance-sustainability_knowledge-2-17-a",
            14: "gri-governance-sustainability_reporting-2-14-role",
            15: "gri-governance-delegation-2-13-a-managing",
            16: "gri-governance-delegation-2-13-b-frequency",
            17: "gri-governance-critical_concerns-2-16-a-critical_concerns",
            18: "gri-governance-critical_concerns-2-16-b-report",
            19: "gri-governance-performance_evaluations-2-18-a-processes",
            20: "gri-governance-performance_evaluations-2-18-b-evaluation",
            21: "gri-governance-performance_evaluations-2-18-c-actions",
            22: "gri-governance-remuneration-2-19-a-remuneration",
            23: "gri-governance-compensation_ratio-2-21-a-annual",
            24: "gri-governance-compensation_ratio-2-21-b-percentage",
            25: "gri-governance-compensation_ratio-2-21-c-contextual",
            26: "gri-governance-sustainability_strategy-2-22-a_provide",
            27: "gri-governance-process-2-25-a-commitments",
            28: "gri-governance-process-2-25-b-approach",
            29: "gri-governance-process-2-25-c-other_processes",
            30: "gri-governance-process-2-25-d-stakeholders",
            31: "gri-governance-process-2-25-e-effectiveness",
            32: "gri-governance-advice_and_concerns-2-26-a",
            33: "gri-general-laws_and_regulation-instance-2-27-a",
            34: "gri-general-laws_and_regulation-monetary-2-27-b",
            35: "gri-general-laws_and_regulation-significant-2-27-c",
            36: "gri-general-laws_and_regulation-organization-2-27-d",
            37: "gri-economic-anti_competitive_behavior-206-1a-behavior",
            38: "gri-economic-defined_benefit_plan-general-201-3a",
            39: "gri-economic-defined_benefit_plan-separate-201-3b",
            40: "gri-economic-defined_benefit_plan-explain-201-3c",
            41: "gri-economic-defined_benefit_plan-percentage-201-3d",
            42: "gri-economic-defined_benefit_plan-mention-201-3e",
            43: "gri-governance-conflict_of_interest-2-15-a-highest",
            44: "gri-governance-conflict_of_interest-2-15-b-report",
            45: "gri-general-membership_association-2-28-a-report",
            46: "gri-governance-determine-remuneration-2-20-a-process",
            47: "gri-governance-determine-remuneration-2-22-b-results",
            48: "gri-governance-policy_commitments-2-23-a-business_conduct",
            49: "gri-governance-policy_commitments-2-23-b-human_rights",
            50: "gri-governance-policy_commitments-2-23-c-links",
            51: "gri-governance-policy_commitments-2-23-c-leave",
            52: "gri-governance-policy_commitments-2-23-e-report",
            53: "gri-governance-policy_commitments-2-23-f-describe",
            54: "gri-economic-anti_competitive_behavior-206-1b-judgements",
            55: "gri-economic-ratios_of_standard_entry_level_wage_by_gender_compared_to_local_minimum_wage-202-1a-s1",
            56: "gri-economic-ratios_of_standard_entry_level_wage_by_gender_compared_to_local_minimum_wage-202-1b-s2",
            57: "gri-economic-ratios_of_standard_entry-202-1c-location",
            58: "gri-economic-ratios_of_standard_entry-202-1d-definition",
            59: "gri-governance-compensation_ratio-2-21-a-annual",
            60: "gri-governance-compensation_ratio-2-21-b-percentage",
        }

    def get_response(self): ...
