# Generated by Django 4.2.4 on 2024-12-12 06:03

import authentication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sustainapp', '0006_department'),
        ('authentication', '0007_remove_userprofile_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentifyingInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(help_text='Year of the financial reporting year')),
                ('report_purpose_1', models.CharField(blank=True, help_text='1. This report is for which of the following?', max_length=128, null=True)),
                ('reporting_legal_name_2', models.CharField(help_text='2.Legal name of reporting entity', max_length=128, null=True)),
                ('financial_reporting_year_from_3', models.DateField(help_text='3.Financial reporting year from', null=True)),
                ('financial_reporting_year_to_3', models.DateField(help_text='3.Financial reporting year to', null=True)),
                ('is_revised_version_4', models.CharField(help_text='4.Is this a revised version of a report already submitted this reporting year?', max_length=16, null=True)),
                ('original_report_date_4_1', models.DateField(blank=True, help_text='4.1 If yes, identify the date the original report was submitted.', null=True)),
                ('changes_description_4_2', models.TextField(blank=True, help_text='4.2 Describe the changes made to the original report, including by listing the questions or sections that were revised (1,500 character limit)', max_length=1500, null=True)),
                ('business_number_5', models.BigIntegerField(blank=True, help_text='5. Business Number(s)', null=True)),
                ('is_joint_report_6', models.CharField(help_text='6. Is this a joint report?', max_length=16, null=True)),
                ('legal_name_and_business_numbers_6_1_2', models.JSONField(blank=True, help_text='6.1 & 6.2 If yes, identify the legal name and business number(s) of each entity covered by this report', null=True)),
                ('subject_to_supply_chain_legislation_7', models.CharField(help_text='7. Is the entity also subject to reporting requirements under supply chain legislation in another jurisdiction', max_length=16, null=True)),
                ('applicable_laws_7_1', models.JSONField(blank=True, help_text='7.1 If yes, indicate the applicable law(s)', null=True)),
                ('other_laws_description_7_1', models.TextField(blank=True, help_text='7.1 Description for applicable law(s)', max_length=1500, null=True)),
                ('categorizations_8', models.JSONField(help_text='8. Which of the following categorizations applies to the entity?', null=True)),
                ('sectors_or_industries_9', models.JSONField(help_text='9. Which of the following sectors or industries does the entity operate in?', null=True)),
                ('sectors_or_industries_description_9', models.TextField(blank=True, help_text='9. Other sector or industries', max_length=1500, null=True)),
                ('country_10', models.CharField(help_text='10. Country headquarted or principally located?', max_length=128, null=True)),
                ('province_or_territory_10_1', models.CharField(blank=True, help_text='10.1 If in Canada: In which province or territory is the entity headquartered or principally located?', max_length=255, null=True)),
                ('client', models.ForeignKey(default=authentication.models.Client.get_default_client, on_delete=django.db.models.deletion.CASCADE, related_name='Identifying_information_client', to='authentication.client')),
                ('corporate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Idnetifying_Information_Corporate', to='sustainapp.corporateentity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Idnetifying_Information_Organization', to='sustainapp.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Idnetifying_Information_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='identifyinginformation',
            constraint=models.UniqueConstraint(fields=('client', 'organization', 'corporate', 'year'), name='unique_identifying_information'),
        ),
    ]
