# Generated by Django 4.2.4 on 2024-12-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canadabills211', '0002_annualreport_annualreport_unique_annual_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualreport',
            name='additional_info_assessment_18',
            field=models.TextField(help_text='18. Please provide additional information on how the entity assesses its effectiveness in ensuring that forced labour and child labour are not being used in its activities and supply chains (if applicable)', null=True),
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='additional_info_entity_10',
            field=models.TextField(help_text='10. Please provide additional information on the parts of the entity’s activities and supply chains that carry a risk of forced labour or child labour being used, as well as the steps that the entity has taken to assess and manage that risk (if applicable)', null=True),
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='additional_info_loss_income_14',
            field=models.TextField(help_text='14. Please provide additional information on any measures the entity has taken to remediate the loss of income to the most vulnerable families that results from any measure taken to eliminate the use of forced labour or child labour in its activities and supply chains (if applicable)', null=True),
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='additional_info_policies_7',
            field=models.TextField(help_text='7. Please provide additional information on the entity’s policies and due diligence processes in relation to forced labour and child labour (if applicable)', null=True),
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='additional_info_training_16',
            field=models.TextField(help_text='16. Please provide additional information on any measures the entity has taken to remediate the loss of income to the most vulnerable families that results from any measure taken to eliminate the use of forced labour or child labour in its activities and supply chains (if applicable)', null=True),
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='additional_information_2',
            field=models.TextField(help_text='2. Please provide additional information describing the steps taken (if applicable)', null=True),
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='additional_information_entity_5',
            field=models.TextField(help_text='5. Please provide additional information on the entity’s structure, activities and supply chains', null=True),
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='assessment_method_description_17_1',
            field=models.TextField(blank=True, help_text='17.1 Other, please specify', null=True),
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='measures_remediate_activaties_11',
            field=models.TextField(help_text='11. Has the entity taken any measures to remediate any forced labour or child labour in its activities and supply chains?', null=True),
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='remediation_measures_12',
            field=models.TextField(help_text='12. Please provide additional information on any measures the entity has taken to remediate any forced labour or child labour (if applicable)', null=True),
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='remediation_measures_taken_description_11_1',
            field=models.TextField(blank=True, help_text='11.1 Other, please specify', null=True),
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='risk_activaties_description_9',
            field=models.TextField(blank=True, help_text='9. Other, please specify', null=True),
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='risk_aspects_description_8_1',
            field=models.TextField(blank=True, help_text='8.1 Other, please specify', null=True),
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='steps_taken_description_1',
            field=models.TextField(blank=True, help_text='1. Other, please specify', null=True),
        ),
        migrations.AlterField(
            model_name='identifyinginformation',
            name='changes_description_4_2',
            field=models.TextField(blank=True, help_text='4.2 Describe the changes made to the original report, including by listing the questions or sections that were revised (1,500 character limit)', null=True),
        ),
        migrations.AlterField(
            model_name='identifyinginformation',
            name='other_laws_description_7_1',
            field=models.TextField(blank=True, help_text='7.1 Description for applicable law(s)', null=True),
        ),
        migrations.AlterField(
            model_name='identifyinginformation',
            name='reporting_legal_name_2',
            field=models.CharField(help_text='2.Legal name of reporting entity', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='identifyinginformation',
            name='sectors_or_industries_description_9',
            field=models.TextField(blank=True, help_text='9. Other sector or industries', null=True),
        ),
    ]
