# Generated by Django 4.2.4 on 2025-03-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canadabills211', '0003_alter_annualreport_additional_info_assessment_18_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifyinginformation',
            name='business_number_5',
            field=models.CharField(blank=True, help_text='5. Business Number(s)', max_length=16, null=True),
        ),
    ]
