# Generated by Django 4.2.4 on 2025-04-21 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('canadabills211', '0004_alter_identifyinginformation_business_number_5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualreport',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Annaul_report', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='identifyinginformation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Idnetifying_Information_User', to=settings.AUTH_USER_MODEL),
        ),
    ]
