# Generated by Django 5.2.3 on 2025-06-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltcfdreport',
            name='screen',
        ),
        migrations.RemoveField(
            model_name='tcfdreport',
            name='screen',
        ),
        migrations.AddField(
            model_name='historicaltcfdreport',
            name='screen_name',
            field=models.CharField(default='message_ceo', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tcfdreport',
            name='screen_name',
            field=models.CharField(default='message_ceo', max_length=255),
            preserve_default=False,
        ),
    ]
