# Generated by Django 5.1.1 on 2024-10-24 06:14

import authentication.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0001_initial'),
        ('sustainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='corps',
            field=models.ManyToManyField(related_name='corporates', to='sustainapp.corporateentity'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='userext_groups', related_query_name='userext', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='locs',
            field=models.ManyToManyField(related_name='locations', to='sustainapp.location'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='orgs',
            field=models.ManyToManyField(related_name='organizations', to='sustainapp.organization'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='userext_permissions', related_query_name='userext', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='client',
            field=models.ForeignKey(blank=True, default=authentication.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='custom_userclient', to='authentication.client'),
        ),
        migrations.AddField(
            model_name='customrole',
            name='view_permissions',
            field=models.ManyToManyField(to='authentication.custompermission'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='custom_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.customrole'),
        ),
        migrations.AddField(
            model_name='logincounter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='first_login', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
