# Generated by Django 4.2.4 on 2024-10-18 08:09

from django.db import migrations, models
import django.db.models.deletion
import sustainapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sustainapp', '0001_initial'),
        ('authentication', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='client',
            field=models.ForeignKey(blank=True, default=sustainapp.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='custom_userclient', to='sustainapp.client'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='custom_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.customrole'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='userext_groups', related_query_name='userext', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='userext_permissions', related_query_name='userext', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
