# Generated by Django 4.2.4 on 2024-10-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0001_initial'),
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='corps',
            field=models.ManyToManyField(related_name='corporates', to='sustainapp.corporateentity'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='locs',
            field=models.ManyToManyField(related_name='locations', to='sustainapp.location'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='orgs',
            field=models.ManyToManyField(related_name='organizations', to='sustainapp.userorg'),
        ),
    ]
