# Generated by Django 4.2.4 on 2024-09-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_logincounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
