# Generated by Django 4.2.4 on 2024-10-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0001_initial'),
        ('authentication', '0003_customuser_corps_customuser_locs_customuser_orgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='orgs',
            field=models.ManyToManyField(related_name='organizations', to='sustainapp.organization'),
        ),
    ]
