# Generated by Django 4.2.4 on 2024-09-20 10:58

from django.db import migrations, models
import uuid


# * Create a method that adds UUID in uuid field.
def add_uuid(apps, schema_editor):
    Client = apps.get_model("authentication", "Client")
    for client in Client.objects.all():

        client.uuid = uuid.uuid4()
        client.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_client_uuid"),
    ]

    operations = [
        migrations.RunPython(add_uuid),
        migrations.AlterField(
            model_name="client",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
