# Generated by Django 5.1.1 on 2024-10-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customuser_orgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='permissions_checkbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='optimise',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='report',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='track',
            field=models.BooleanField(default=False),
        ),
    ]
