# Generated by Django 4.2.4 on 2024-11-12 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
