# Generated by Django 4.2.4 on 2024-10-24 05:40

import authentication.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customuser_permissions_checkbox_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('customer', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sub_domain', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('okta_url', models.CharField(blank=True, max_length=900, null=True, unique=True)),
                ('okta_key', models.CharField(blank=True, max_length=900, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='client',
            field=models.ForeignKey(blank=True, default=authentication.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='custom_userclient', to='authentication.client'),
        ),
    ]
