# Generated by Django 4.2.4 on 2024-11-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_delete_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='work_email',
            field=models.CharField(blank=True, max_length=200, verbose_name='work_email'),
        ),
    ]
