# Generated by Django 4.2.4 on 2024-10-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0007_alter_client_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_client_admin",
            field=models.BooleanField(default=False),
        ),
    ]
