# Generated by Django 4.2.4 on 2025-01-10 12:50

from django.db import migrations, models


def populate_old_password(apps, schema_editor):
    # Get the CustomUser model dynamically
    CustomUser = apps.get_model("authentication", "CustomUser")
    for user in CustomUser.objects.all():
        user.old_password = user.password  # Copy the current password to old_password
        user.save(update_fields=["old_password"])


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0007_remove_userprofile_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="old_password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.RunPython(populate_old_password),
    ]
