# Generated by Django 4.2.4 on 2024-10-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0008_customuser_is_client_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="roles",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("employee", "Employee"),
                ],
                default="employee",
                max_length=20,
            ),
        ),
    ]
