# Generated by Django 4.2.4 on 2025-01-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_customuser_old_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersafelock',
            name='last_failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
