# Generated by Django 4.2 on 2025-05-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_usersafelock_last_failed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='job_description',
            field=models.TextField(blank=True, verbose_name='job description'),
        ),
    ]
