# Generated by Django 4.2.4 on 2024-10-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0009_customuser_admin_customuser_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="sub_domain",
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
