# Generated by Django 4.2.4 on 2024-10-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_client_sub_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='okta_key',
            field=models.CharField(blank=True, max_length=900, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='okta_url',
            field=models.CharField(blank=True, max_length=900, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.CharField(choices=[('system_admin', 'System Admin'), ('client_admin', 'Client Admin'), ('manager', 'Manager'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
