# Generated by Django 4.2 on 2025-05-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_customuser_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='job_description',
            field=models.TextField(blank=True, null=True, verbose_name='job description'),
        ),
    ]
