# Generated by Django 4.2.4 on 2024-10-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_custompermission_customrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompermission',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
