# Generated by Django 4.2.4 on 2025-05-30 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_useremailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersafelock',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safelock', to=settings.AUTH_USER_MODEL),
        ),
    ]
