# Generated by Django 4.2.4 on 2024-10-11 03:12

from django.db import migrations, models
import django.db.models.deletion

def set_default_custom_role(apps, schema_editor):
    CustomUser = apps.get_model('authentication', 'CustomUser')
    CustomRole = apps.get_model('authentication', 'CustomRole')
    default_role, _ = CustomRole.objects.get_or_create(name="System Admin")
    for user in CustomUser.objects.filter(custom_role__isnull=True):
        user.custom_role = default_role
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_custompermission_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='custom_role',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.customrole'),
        ),
        migrations.RunPython(set_default_custom_role),
    ]