# Generated by Django 4.2.4 on 2024-10-11 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_custom_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='custom_role',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.customrole'),
        ),
    ]
