# Generated by Django 5.1.1 on 2024-10-24 06:14

import authentication.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeinwaterstorage',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
    ]
