# Generated by Django 4.2.4 on 2024-08-11 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmploymentHiresAndTurnover',
        ),
    ]
