# Generated by Django 4.2.4 on 2024-10-18 08:09

from django.db import migrations, models
import django.db.models.deletion
import sustainapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sustainapp', '0001_initial'),
        ('datametric', '0001_initial'),
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterfromstressareas',
            name='client',
            field=models.ForeignKey(default=sustainapp.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.client'),
        ),
        migrations.AddField(
            model_name='waterfromstressareas',
            name='corporate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity'),
        ),
        migrations.AddField(
            model_name='waterfromstressareas',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location'),
        ),
        migrations.AddField(
            model_name='waterfromstressareas',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization'),
        ),
        migrations.AddField(
            model_name='waterfromstressareas',
            name='raw_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
        migrations.AddField(
            model_name='waterfromallareas',
            name='client',
            field=models.ForeignKey(default=sustainapp.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.client'),
        ),
        migrations.AddField(
            model_name='waterfromallareas',
            name='corporate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity'),
        ),
        migrations.AddField(
            model_name='waterfromallareas',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location'),
        ),
        migrations.AddField(
            model_name='waterfromallareas',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization'),
        ),
        migrations.AddField(
            model_name='waterfromallareas',
            name='raw_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
        migrations.AddField(
            model_name='waterdischargefromstressareas',
            name='client',
            field=models.ForeignKey(default=sustainapp.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.client'),
        ),
        migrations.AddField(
            model_name='waterdischargefromstressareas',
            name='corporate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity'),
        ),
        migrations.AddField(
            model_name='waterdischargefromstressareas',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location'),
        ),
        migrations.AddField(
            model_name='waterdischargefromstressareas',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization'),
        ),
        migrations.AddField(
            model_name='waterdischargefromstressareas',
            name='raw_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
        migrations.AddField(
            model_name='wastegenerated',
            name='client',
            field=models.ForeignKey(default=sustainapp.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.client'),
        ),
        migrations.AddField(
            model_name='wastegenerated',
            name='corporate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity'),
        ),
        migrations.AddField(
            model_name='wastegenerated',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location'),
        ),
        migrations.AddField(
            model_name='wastegenerated',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization'),
        ),
        migrations.AddField(
            model_name='wastegenerated',
            name='raw_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
        migrations.AddField(
            model_name='wastedivertedfromdisposal',
            name='client',
            field=models.ForeignKey(default=sustainapp.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.client'),
        ),
        migrations.AddField(
            model_name='wastedivertedfromdisposal',
            name='corporate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity'),
        ),
        migrations.AddField(
            model_name='wastedivertedfromdisposal',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location'),
        ),
        migrations.AddField(
            model_name='wastedivertedfromdisposal',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization'),
        ),
        migrations.AddField(
            model_name='wastedivertedfromdisposal',
            name='raw_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
        migrations.AddField(
            model_name='wastedirectedtodisposal',
            name='client',
            field=models.ForeignKey(default=sustainapp.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.client'),
        ),
        migrations.AddField(
            model_name='wastedirectedtodisposal',
            name='corporate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity'),
        ),
        migrations.AddField(
            model_name='wastedirectedtodisposal',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location'),
        ),
        migrations.AddField(
            model_name='wastedirectedtodisposal',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization'),
        ),
        migrations.AddField(
            model_name='wastedirectedtodisposal',
            name='raw_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
        migrations.AddField(
            model_name='thirdpartywaterdischargefromallareas',
            name='client',
            field=models.ForeignKey(default=sustainapp.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.client'),
        ),
        migrations.AddField(
            model_name='thirdpartywaterdischargefromallareas',
            name='corporate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity'),
        ),
        migrations.AddField(
            model_name='thirdpartywaterdischargefromallareas',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location'),
        ),
        migrations.AddField(
            model_name='thirdpartywaterdischargefromallareas',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization'),
        ),
        migrations.AddField(
            model_name='thirdpartywaterdischargefromallareas',
            name='raw_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
        migrations.AddField(
            model_name='selfgeneratedenergy',
            name='client',
            field=models.ForeignKey(default=sustainapp.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.client'),
        ),
        migrations.AddField(
            model_name='selfgeneratedenergy',
            name='corporate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity'),
        ),
        migrations.AddField(
            model_name='selfgeneratedenergy',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location'),
        ),
        migrations.AddField(
            model_name='selfgeneratedenergy',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization'),
        ),
        migrations.AddField(
            model_name='selfgeneratedenergy',
            name='raw_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
        migrations.AddField(
            model_name='reductionenergyinproductservices',
            name='client',
            field=models.ForeignKey(default=sustainapp.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.client'),
        ),
        migrations.AddField(
            model_name='reductionenergyinproductservices',
            name='corporate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity'),
        ),
        migrations.AddField(
            model_name='reductionenergyinproductservices',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location'),
        ),
        migrations.AddField(
            model_name='reductionenergyinproductservices',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization'),
        ),
        migrations.AddField(
            model_name='reductionenergyinproductservices',
            name='raw_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
        migrations.AddField(
            model_name='reductionenergyconsumption',
            name='client',
            field=models.ForeignKey(default=sustainapp.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.client'),
        ),
        migrations.AddField(
            model_name='reductionenergyconsumption',
            name='corporate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity'),
        ),
        migrations.AddField(
            model_name='reductionenergyconsumption',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location'),
        ),
        migrations.AddField(
            model_name='reductionenergyconsumption',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization'),
        ),
        migrations.AddField(
            model_name='reductionenergyconsumption',
            name='raw_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
        migrations.AddField(
            model_name='parentalleave',
            name='client',
            field=models.ForeignKey(default=sustainapp.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.client'),
        ),
        migrations.AddField(
            model_name='parentalleave',
            name='corporate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity'),
        ),
        migrations.AddField(
            model_name='parentalleave',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parental_leave_gender', to='analysis.gender'),
        ),
        migrations.AddField(
            model_name='parentalleave',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location'),
        ),
        migrations.AddField(
            model_name='parentalleave',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization'),
        ),
        migrations.AddField(
            model_name='parentalleave',
            name='raw_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
        migrations.AddField(
            model_name='organisationgovernancebodies',
            name='client',
            field=models.ForeignKey(default=sustainapp.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.client'),
        ),
        migrations.AddField(
            model_name='organisationgovernancebodies',
            name='corporate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity'),
        ),
        migrations.AddField(
            model_name='organisationgovernancebodies',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.gender'),
        ),
        migrations.AddField(
            model_name='organisationgovernancebodies',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location'),
        ),
        migrations.AddField(
            model_name='organisationgovernancebodies',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization'),
        ),
        migrations.AddField(
            model_name='organisationgovernancebodies',
            name='raw_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
        migrations.AddField(
            model_name='injuryreport',
            name='client',
            field=models.ForeignKey(default=sustainapp.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.client'),
        ),
        migrations.AddField(
            model_name='injuryreport',
            name='corporate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity'),
        ),
        migrations.AddField(
            model_name='injuryreport',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location'),
        ),
        migrations.AddField(
            model_name='injuryreport',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization'),
        ),
        migrations.AddField(
            model_name='injuryreport',
            name='raw_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
        migrations.AddField(
            model_name='illhealthreport',
            name='client',
            field=models.ForeignKey(default=sustainapp.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.client'),
        ),
        migrations.AddField(
            model_name='illhealthreport',
            name='corporate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity'),
        ),
        migrations.AddField(
            model_name='illhealthreport',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location'),
        ),
        migrations.AddField(
            model_name='illhealthreport',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization'),
        ),
        migrations.AddField(
            model_name='illhealthreport',
            name='raw_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
        migrations.AddField(
            model_name='governancebodydetails',
            name='client',
            field=models.ForeignKey(default=sustainapp.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.client'),
        ),
        migrations.AddField(
            model_name='governancebodydetails',
            name='corporate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity'),
        ),
        migrations.AddField(
            model_name='governancebodydetails',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.gender'),
        ),
        migrations.AddField(
            model_name='governancebodydetails',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location'),
        ),
        migrations.AddField(
            model_name='governancebodydetails',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization'),
        ),
        migrations.AddField(
            model_name='governancebodydetails',
            name='raw_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
        migrations.AddField(
            model_name='energysold',
            name='client',
            field=models.ForeignKey(default=sustainapp.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.client'),
        ),
        migrations.AddField(
            model_name='energysold',
            name='corporate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity'),
        ),
        migrations.AddField(
            model_name='energysold',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location'),
        ),
        migrations.AddField(
            model_name='energysold',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization'),
        ),
        migrations.AddField(
            model_name='energysold',
            name='raw_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
        migrations.AddField(
            model_name='energyintensity',
            name='client',
            field=models.ForeignKey(default=sustainapp.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.client'),
        ),
        migrations.AddField(
            model_name='energyintensity',
            name='corporate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity'),
        ),
        migrations.AddField(
            model_name='energyintensity',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location'),
        ),
        migrations.AddField(
            model_name='energyintensity',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization'),
        ),
        migrations.AddField(
            model_name='energyintensity',
            name='raw_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
        migrations.AddField(
            model_name='energyconsumedoutsideorg',
            name='client',
            field=models.ForeignKey(default=sustainapp.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.client'),
        ),
        migrations.AddField(
            model_name='energyconsumedoutsideorg',
            name='corporate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity'),
        ),
        migrations.AddField(
            model_name='energyconsumedoutsideorg',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location'),
        ),
        migrations.AddField(
            model_name='energyconsumedoutsideorg',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization'),
        ),
        migrations.AddField(
            model_name='energyconsumedoutsideorg',
            name='raw_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
        migrations.AddField(
            model_name='employmentturnover',
            name='client',
            field=models.ForeignKey(default=sustainapp.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.client'),
        ),
        migrations.AddField(
            model_name='employmentturnover',
            name='corporate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity'),
        ),
        migrations.AddField(
            model_name='employmentturnover',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.gender'),
        ),
        migrations.AddField(
            model_name='employmentturnover',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location'),
        ),
        migrations.AddField(
            model_name='employmentturnover',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization'),
        ),
        migrations.AddField(
            model_name='employmentturnover',
            name='raw_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
        migrations.AddField(
            model_name='employmenthires',
            name='client',
            field=models.ForeignKey(default=sustainapp.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.client'),
        ),
        migrations.AddField(
            model_name='employmenthires',
            name='corporate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity'),
        ),
        migrations.AddField(
            model_name='employmenthires',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employment_hire_and_turnover_gender', to='analysis.gender'),
        ),
        migrations.AddField(
            model_name='employmenthires',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location'),
        ),
        migrations.AddField(
            model_name='employmenthires',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization'),
        ),
        migrations.AddField(
            model_name='employmenthires',
            name='raw_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
        migrations.AddField(
            model_name='employeeworkerdata',
            name='client',
            field=models.ForeignKey(default=sustainapp.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.client'),
        ),
        migrations.AddField(
            model_name='employeeworkerdata',
            name='corporate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity'),
        ),
        migrations.AddField(
            model_name='employeeworkerdata',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location'),
        ),
        migrations.AddField(
            model_name='employeeworkerdata',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization'),
        ),
        migrations.AddField(
            model_name='employeeworkerdata',
            name='raw_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
        migrations.AddField(
            model_name='directpurchasedenergy',
            name='client',
            field=models.ForeignKey(default=sustainapp.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.client'),
        ),
        migrations.AddField(
            model_name='directpurchasedenergy',
            name='corporate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity'),
        ),
        migrations.AddField(
            model_name='directpurchasedenergy',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location'),
        ),
        migrations.AddField(
            model_name='directpurchasedenergy',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization'),
        ),
        migrations.AddField(
            model_name='directpurchasedenergy',
            name='raw_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
        migrations.AddField(
            model_name='consumedenergy',
            name='client',
            field=models.ForeignKey(default=sustainapp.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.client'),
        ),
        migrations.AddField(
            model_name='consumedenergy',
            name='corporate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity'),
        ),
        migrations.AddField(
            model_name='consumedenergy',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location'),
        ),
        migrations.AddField(
            model_name='consumedenergy',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization'),
        ),
        migrations.AddField(
            model_name='consumedenergy',
            name='raw_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
        migrations.AddField(
            model_name='communitydevelopmentnumberofoperation',
            name='client',
            field=models.ForeignKey(default=sustainapp.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.client'),
        ),
        migrations.AddField(
            model_name='communitydevelopmentnumberofoperation',
            name='corporate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity'),
        ),
        migrations.AddField(
            model_name='communitydevelopmentnumberofoperation',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location'),
        ),
        migrations.AddField(
            model_name='communitydevelopmentnumberofoperation',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization'),
        ),
        migrations.AddField(
            model_name='communitydevelopmentnumberofoperation',
            name='raw_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
        migrations.AddField(
            model_name='changeinwaterstorage',
            name='client',
            field=models.ForeignKey(default=sustainapp.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.client'),
        ),
        migrations.AddField(
            model_name='changeinwaterstorage',
            name='corporate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity'),
        ),
        migrations.AddField(
            model_name='changeinwaterstorage',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location'),
        ),
        migrations.AddField(
            model_name='changeinwaterstorage',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization'),
        ),
        migrations.AddField(
            model_name='changeinwaterstorage',
            name='raw_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
    ]
