# Generated by Django 4.2.4 on 2024-10-24 05:40

import authentication.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_client_alter_customuser_client'),
        ('analysis', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeinwaterstorage',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='communitydevelopmentnumberofoperation',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='consumedenergy',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='directpurchasedenergy',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='employeeworkerdata',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='employmenthires',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='employmentturnover',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='energyconsumedoutsideorg',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='energyintensity',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='energysold',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='governancebodydetails',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='illhealthreport',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='injuryreport',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='organisationgovernancebodies',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='parentalleave',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='reductionenergyconsumption',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='reductionenergyinproductservices',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='selfgeneratedenergy',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='thirdpartywaterdischargefromallareas',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='wastedirectedtodisposal',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='wastedivertedfromdisposal',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='wastegenerated',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='waterdischargefromstressareas',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='waterfromallareas',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='waterfromstressareas',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
    ]
