# Generated by Django 4.2.4 on 2024-08-11 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sustainapp', '0003_delete_logincounter'),
        ('analysis', '0002_delete_employmenthiresandturnover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmploymentHiresAndTurnover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('age_group', models.CharField(choices=[('less than 30 years old', 'Less than 30 years old'), ('30-50 years old', '30-50 years old'), ('greater than 50 years old', 'Greater than 50 years old')], max_length=255)),
                ('employment_type', models.CharField(choices=[('permanent employee', 'Permanent Employee'), ('temporary employee', 'Temporary Employee'), ('non-guaranteed-employee', 'Non-guaranteed Employee'), ('full-time employee', 'Full-time Employee'), ('part-time employee', 'Part-time Employee')], max_length=255)),
                ('employmee_table_name', models.CharField(choices=[('new employee hire', 'New Employee Hire'), ('employee turnover', 'Employee Turnover')], max_length=255)),
                ('value', models.IntegerField()),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_hire_and_turnover_gender', to='analysis.gender')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='sustainapp.location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
