# Generated by Django 4.2.4 on 2024-08-11 07:12

from django.db import migrations


def create_gender_objects(apps, schema_editor):
    Gender = apps.get_model("analysis", "Gender")
    Gender.objects.create(gender="male")
    Gender.objects.create(gender="female")
    Gender.objects.create(gender="other")


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_initial'),
    ]

    operations = [
        migrations.RunPython(create_gender_objects),
    ]
