# Generated by Django 5.1.1 on 2024-10-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclaimedmaterials',
            name='amount_of_product_sold',
            field=models.DecimalField(decimal_places=6, max_digits=36),
        ),
        migrations.AlterField(
            model_name='reclaimedmaterials',
            name='amount_of_recycled_material_used',
            field=models.DecimalField(decimal_places=6, max_digits=36),
        ),
        migrations.AlterField(
            model_name='recycledinputmaterials',
            name='amount_of_material_recycled',
            field=models.DecimalField(decimal_places=6, max_digits=36),
        ),
        migrations.AlterField(
            model_name='recycledinputmaterials',
            name='amount_of_recycled_input_material_used',
            field=models.DecimalField(decimal_places=6, max_digits=36),
        ),
        migrations.AlterField(
            model_name='recycledinputmaterials',
            name='total_weight_or_volume',
            field=models.DecimalField(decimal_places=6, max_digits=36),
        ),
    ]
