# Generated by Django 4.2.4 on 2024-08-11 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0003_delete_logincounter'),
        ('analysis', '0004_auto_20240811_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmenthiresandturnover',
            name='corporate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employmenthiresandturnover',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employmenthiresandturnover',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employment_hire_and_turnover_gender', to='analysis.gender'),
        ),
    ]
