# Generated by Django 4.2.4 on 2025-05-26 06:18

import authentication.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0023_alter_corporateentity_employeecount_and_more'),
        ('datametric', '0003_emissionanalysis_unique_id_and_more'),
        ('authentication', '0011_alter_customuser_job_description'),
        ('analysis', '0004_alter_reclaimedmaterials_amount_of_product_sold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GHGIntensity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.IntegerField(null=True)),
                ('year', models.IntegerField()),
                ('organization_specific_metric', models.CharField(max_length=255)),
                ('metric_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=32)),
                ('unit', models.CharField(max_length=255)),
                ('types_included', models.JSONField(blank=True, default=list)),
                ('custom_metric_type', models.CharField(blank=True, max_length=255, null=True)),
                ('index', models.PositiveIntegerField()),
                ('client', models.ForeignKey(default=authentication.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client')),
                ('corporate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location')),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization')),
                ('raw_response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
