# Generated by Django 4.2.4 on 2024-08-11 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0003_delete_logincounter'),
        ('analysis', '0005_employmenthiresandturnover_corporate_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmploymentHiresAndTurnover',
            new_name='EmploymentHires',
        ),
    ]
