# Generated by Django 4.2.4 on 2024-08-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_employmentturnover'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmenthires',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employmentturnover',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
