# Generated by Django 4.2.4 on 2024-08-11 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0003_delete_logincounter'),
        ('analysis', '0008_employmenthires_index_employmentturnover_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentalLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('value', models.IntegerField()),
                ('employee_category', models.CharField(choices=[('parental_leave_entitlement', 'Parental Leave Entitlement'), ('taking_parental_leave', 'Taking parental leave'), ('returning_to_work_post-leave', 'Returning to Work Post-Leave'), ('retained_12_months_after_leave', 'Retained 12 Months After Leave')], max_length=255)),
                ('corporate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parental_leave_gender', to='analysis.gender')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parental_leave_location', to='sustainapp.location')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
