# Generated by Django 4.2.4 on 2024-08-11 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0003_delete_logincounter'),
        ('analysis', '0009_parentalleave'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWorkerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('category', models.CharField(choices=[('covered_by_system', 'Covered by the system'), ('internally_audited', 'Internally audited'), ('externally_audited', 'Audited or certified by an external party')], max_length=50)),
                ('number_of_employees', models.IntegerField()),
                ('number_of_workers_not_employees', models.IntegerField()),
                ('total_number_of_employees', models.IntegerField()),
                ('corporate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization')),
            ],
            options={
                'verbose_name_plural': 'Employee and Worker Data',
            },
        ),
    ]
