# Generated by Django 4.2.4 on 2024-08-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_employeeworkerdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeworkerdata',
            name='category',
            field=models.CharField(choices=[('covered_by_system', 'Covered by the system'), ('internally_audited', 'Internally audited'), ('externally_audited', 'Audited or certified by an external party')], max_length=255),
        ),
    ]
