# Generated by Django 4.2.4 on 2024-08-11 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0003_delete_logincounter'),
        ('analysis', '0011_alter_employeeworkerdata_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='InjuryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('table_name', models.CharField(choices=[('the_number_of_injuries_for_all_employees', 'The number of injuries for all employees'), ('the_number_of_injuries_for_workers_who_are_not_employees_but_whose_work_and_workplace_is_controlled_by_the_organization', 'The Number of Injuries for workers who are not employees but whose work and workplace is controlled by the organization')], max_length=120)),
                ('employee_category', models.CharField(help_text='Indicate if the report is for employees or non-employees controlled by the organization.', max_length=500)),
                ('fatalities', models.PositiveIntegerField(help_text='Number of fatalities as a result of work-related injury')),
                ('high_consequence_injuries', models.PositiveIntegerField(help_text='Number of high-consequence work-related injuries (excluding fatalities)')),
                ('recordable_injuries', models.PositiveIntegerField(help_text='Number of recordable work-related injuries')),
                ('injury_types', models.TextField(help_text='Main types of work-related injury')),
                ('hours_worked', models.PositiveIntegerField(help_text='Number of hours worked')),
                ('corporate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization')),
            ],
            options={
                'verbose_name_plural': 'Injury Reports',
            },
        ),
    ]
