# Generated by Django 4.2.4 on 2024-08-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_injuryreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='IllHealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table_name', models.CharField(choices=[('employees', 'Employees'), ('non_employees', 'Non-Employees (Controlled by Organization)')], max_length=200)),
                ('employee_category', models.CharField(choices=[('employees', 'Employees'), ('non_employees', 'Non-Employees (Controlled by Organization)')], help_text='Indicate if the report is for employees or non-employees controlled by the organization.', max_length=500)),
                ('fatalities_due_to_ill_health', models.PositiveIntegerField(help_text='Number of fatalities as a result of work-related ill health')),
                ('recordable_ill_health_cases', models.PositiveIntegerField(help_text='Number of cases of recordable work-related ill health')),
                ('types_of_ill_health', models.TextField(help_text='Main types of work-related ill health')),
            ],
            options={
                'verbose_name_plural': 'Ill Health Reports',
            },
        ),
    ]
