# Generated by Django 4.2.4 on 2024-08-12 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0003_delete_logincounter'),
        ('analysis', '0013_illhealthreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationGovernanceBodies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('employee_category', models.CharField(help_text='Category of employees within the governance body', max_length=500)),
                ('age_group', models.CharField(choices=[('less than 30 years old', 'Less than 30 years old'), ('30-50 years old', '30-50 years old'), ('greater than 50 years old', 'Greater than 50 years old')], max_length=255)),
                ('minority_group_count', models.PositiveIntegerField(help_text='Number of employees in minority groups')),
                ('vulnerable_communities_count', models.PositiveIntegerField(help_text='Number of employees from vulnerable communities')),
                ('gender_value', models.IntegerField()),
                ('age_group_value', models.IntegerField()),
                ('index', models.IntegerField()),
                ('corporate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.gender')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
