# Generated by Django 4.2.4 on 2024-08-12 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0003_delete_logincounter'),
        ('analysis', '0014_organisationgovernancebodies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationgovernancebodies',
            name='corporate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity'),
        ),
        migrations.AlterField(
            model_name='organisationgovernancebodies',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location'),
        ),
        migrations.AlterField(
            model_name='organisationgovernancebodies',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization'),
        ),
    ]
