# Generated by Django 4.2.4 on 2024-08-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_alter_organisationgovernancebodies_corporate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationgovernancebodies',
            name='month',
            field=models.IntegerField(null=True),
        ),
    ]
