# Generated by Django 4.2.4 on 2024-08-12 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0003_delete_logincounter'),
        ('analysis', '0016_alter_organisationgovernancebodies_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernanceBodyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.IntegerField(null=True)),
                ('year', models.IntegerField()),
                ('employee_category', models.CharField(help_text='Basic Salary per Employee Category', max_length=500)),
                ('gender_count', models.PositiveIntegerField(help_text='Number of gender employees in minority groups')),
                ('corporate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.gender')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location')),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization')),
            ],
            options={
                'verbose_name_plural': 'Governance Body Details',
            },
        ),
    ]
