# Generated by Django 4.2.4 on 2024-08-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0017_governancebodydetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='governancebodydetails',
            name='location_of_operation',
            field=models.CharField(default='Something', help_text='Location of operation', max_length=500),
            preserve_default=False,
        ),
    ]
