# Generated by Django 4.2.4 on 2024-08-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0018_governancebodydetails_location_of_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='governancebodydetails',
            name='index',
            field=models.PositiveIntegerField(default=0, help_text='Index of the data'),
            preserve_default=False,
        ),
    ]
