# Generated by Django 4.2.4 on 2024-08-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0019_governancebodydetails_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='governancebodydetails',
            name='table_name',
            field=models.CharField(default='ratio_of_remuneration_of_women_to_men', help_text='Table Name', max_length=500),
            preserve_default=False,
        ),
    ]
