# Generated by Django 4.2.4 on 2024-08-12 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0003_delete_logincounter'),
        ('analysis', '0020_governancebodydetails_table_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityDevelopmentNumberOfOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.IntegerField(null=True)),
                ('year', models.IntegerField()),
                ('name_of_operation', models.CharField(choices=[('Social impact assessments', 'social_impact_assessments'), ('Mention the number of operations that include the use of social impact assessments, including gender impact assessments, based on participatory processes.', 'mention_the_number_of_operations_that_include_the_use_of_social_impact_assessments,_including_gender_impact_assessments,_based_on_participatory_processes.'), ('Environmental impact assessments', 'environmental_impact_assessments'), ('Public disclosure', 'public_disclosure'), ('Community development programs', 'community_development_programs'), ('Stakeholder engagement plans', 'stakeholder_engagement_plans'), ('Local community consultation committes', 'local_community_consultation_committes'), ('Works councils, occupational health and safety committees', 'works_councils,_occupational_health_and_safety_committees'), ('Community grievance processes', 'community_grievance_processes')], max_length=500)),
                ('local_community_operations_count', models.PositiveIntegerField(help_text='Number of operations implemented by engaging local communities')),
                ('total_operations_count', models.PositiveIntegerField(help_text='Total number of operations')),
                ('corporate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location')),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
