# Generated by Django 4.2.4 on 2024-08-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0021_communitydevelopmentnumberofoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitydevelopmentnumberofoperation',
            name='index',
            field=models.PositiveIntegerField(default=0, help_text='Index of the operation'),
        ),
    ]
