# Generated by Django 4.2.4 on 2024-08-12 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0022_communitydevelopmentnumberofoperation_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeworkerdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeworkerdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
