# Generated by Django 4.2.4 on 2024-08-12 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0003_delete_logincounter'),
        ('analysis', '0023_employeeworkerdata_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteGenerated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.IntegerField(null=True)),
                ('year', models.IntegerField()),
                ('category', models.CharField(choices=[('hazardous', 'Hazardous'), ('non_hazardous', 'Non-hazardous')], max_length=200)),
                ('waste_generated', models.DecimalField(choices=[('g', 'grams'), ('Kgs', 'kilograms'), ('t', 'metric tons'), ('ton', 'US short ton'), ('lbs', 'pounds')], decimal_places=2, default='Kgs', max_digits=10)),
                ('waste_unit', models.CharField(max_length=50)),
                ('waste_type', models.CharField(max_length=500)),
                ('index', models.PositiveIntegerField()),
                ('corporate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location')),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
