# Generated by Django 4.2.4 on 2024-08-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0025_alter_wastegenerated_waste_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterdivertedfromdisposal',
            name='site',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
