# Generated by Django 4.2.4 on 2024-08-12 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0003_delete_logincounter'),
        ('analysis', '0027_wastedirectedtodisposal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WaterDivertedFromDisposal',
            new_name='WasteDivertedFromDisposal',
        ),
    ]
