# Generated by Django 4.2.4 on 2024-08-12 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0003_delete_logincounter'),
        ('analysis', '0028_rename_waterdivertedfromdisposal_wastedivertedfromdisposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='illhealthreport',
            name='corporate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity'),
        ),
        migrations.AddField(
            model_name='illhealthreport',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location'),
        ),
        migrations.AddField(
            model_name='illhealthreport',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='illhealthreport',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization'),
        ),
        migrations.AddField(
            model_name='illhealthreport',
            name='year',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
    ]
