# Generated by Django 4.2.4 on 2024-08-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0029_illhealthreport_corporate_illhealthreport_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='illhealthreport',
            name='index',
            field=models.PositiveIntegerField(default=4, help_text='Index of the report within the year'),
            preserve_default=False,
        ),
    ]
