# Generated by Django 4.2.4 on 2024-08-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0031_selfgeneratedenergy_reductionenergyinproductservices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumedenergy',
            name='index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directpurchasedenergy',
            name='index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energyconsumedoutsideorg',
            name='index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energyintensity',
            name='index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energysold',
            name='index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reductionenergyconsumption',
            name='index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reductionenergyinproductservices',
            name='index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selfgeneratedenergy',
            name='index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
