# Generated by Django 4.2.4 on 2024-08-12 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0032_consumedenergy_index_directpurchasedenergy_index_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energyintensity',
            name='energy_quantity',
        ),
        migrations.RemoveField(
            model_name='energyintensity',
            name='energy_unit',
        ),
    ]
