# Generated by Django 4.2.4 on 2024-08-12 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0003_delete_logincounter'),
        ('analysis', '0033_remove_energyintensity_energy_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energyintensity',
            name='index',
        ),
        migrations.RemoveField(
            model_name='energyintensity',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='energyintensity',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='energyintensity',
            name='quantiy_gj',
        ),
        migrations.RemoveField(
            model_name='energyintensity',
            name='raw_response',
        ),
        migrations.RemoveField(
            model_name='energyintensity',
            name='unit',
        ),
        migrations.AddField(
            model_name='energyintensity',
            name='energy_quantity',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='energyintensity',
            name='energy_unit',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='energyintensity',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization'),
        ),
        migrations.AlterField(
            model_name='energyintensity',
            name='corporate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity'),
        ),
        migrations.AlterField(
            model_name='energyintensity',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location'),
        ),
        migrations.AlterField(
            model_name='energyintensity',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='energyintensity',
            name='year',
            field=models.IntegerField(),
        ),
    ]
