# Generated by Django 4.2.4 on 2024-08-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0034_remove_energyintensity_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyintensity',
            name='index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
