# Generated by Django 4.2.4 on 2024-08-12 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datametric', '0027_alter_emissionanalysis_unit'),
        ('analysis', '0035_energyintensity_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyintensity',
            name='raw_response',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
            preserve_default=False,
        ),
    ]
