# Generated by Django 4.2.4 on 2024-08-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0036_energyintensity_raw_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyintensity',
            name='energy_quantity',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='energyintensity',
            name='metric_quantity',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
    ]
