# Generated by Django 4.2.4 on 2024-08-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0037_alter_energyintensity_energy_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationgovernancebodies',
            name='table_name',
            field=models.CharField(default='Number of individuals within the organizations governance bodies', max_length=500),
            preserve_default=False,
        ),
    ]
