# Generated by Django 4.2.4 on 2024-08-12 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0003_delete_logincounter'),
        ('analysis', '0040_alter_employmentturnover_corporate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentalleave',
            name='corporate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity'),
        ),
        migrations.AlterField(
            model_name='parentalleave',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location'),
        ),
        migrations.AlterField(
            model_name='parentalleave',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parentalleave',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization'),
        ),
    ]
