# Generated by Django 4.2.4 on 2024-08-12 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datametric', '0027_alter_emissionanalysis_unit'),
        ('analysis', '0041_alter_parentalleave_corporate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeworkerdata',
            name='corporate',
        ),
        migrations.RemoveField(
            model_name='employeeworkerdata',
            name='location',
        ),
        migrations.RemoveField(
            model_name='employeeworkerdata',
            name='month',
        ),
        migrations.RemoveField(
            model_name='employeeworkerdata',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='employeeworkerdata',
            name='year',
        ),
        migrations.AddField(
            model_name='communitydevelopmentnumberofoperation',
            name='raw_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
        migrations.AddField(
            model_name='employmenthires',
            name='raw_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
        migrations.AddField(
            model_name='employmentturnover',
            name='raw_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
        migrations.AddField(
            model_name='governancebodydetails',
            name='raw_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
        migrations.AddField(
            model_name='illhealthreport',
            name='raw_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
        migrations.AddField(
            model_name='organisationgovernancebodies',
            name='raw_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
        migrations.AddField(
            model_name='parentalleave',
            name='raw_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
        migrations.AddField(
            model_name='wastedirectedtodisposal',
            name='raw_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
        migrations.AddField(
            model_name='wastedivertedfromdisposal',
            name='raw_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
        migrations.AddField(
            model_name='wastegenerated',
            name='raw_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
    ]
