# Generated by Django 4.2.4 on 2024-08-12 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datametric', '0027_alter_emissionanalysis_unit'),
        ('sustainapp', '0003_delete_logincounter'),
        ('analysis', '0042_remove_employeeworkerdata_corporate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeworkerdata',
            name='corporate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity'),
        ),
        migrations.AddField(
            model_name='employeeworkerdata',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location'),
        ),
        migrations.AddField(
            model_name='employeeworkerdata',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employeeworkerdata',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization'),
        ),
        migrations.AddField(
            model_name='employeeworkerdata',
            name='raw_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
        migrations.AddField(
            model_name='employeeworkerdata',
            name='year',
            field=models.IntegerField(default=2024),
            preserve_default=False,
        ),
    ]
