# Generated by Django 4.2.4 on 2024-09-16 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datametric', '0035_alter_emissionanalysis_type_of'),
        ('sustainapp', '0005_trackdashboard'),
        ('analysis', '0047_waterdischargefromstressareas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyWaterDischargeFromAllAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.IntegerField(null=True)),
                ('year', models.IntegerField()),
                ('third_party_discharge', models.CharField(max_length=100)),
                ('water_unit', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(choices=[('Litre', 'Litre'), ('Megalitre', 'Megalitre'), ('Cubic meter', 'Cubic meter'), ('Kilolitre', 'Kilolitre'), ('Million litres per day', 'Million litres per day')], decimal_places=6, default='Megalitre', max_digits=20)),
                ('index', models.PositiveIntegerField()),
                ('corporate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location')),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization')),
                ('raw_response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
