# Generated by Django 4.2.4 on 2024-09-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0050_changeinwaterstorage_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitydevelopmentnumberofoperation',
            name='name_of_operation',
            field=models.CharField(choices=[('Social impact assessments', 'social_impact_assessments'), ('Environmental impact assessments', 'environmental_impact_assessments'), ('Public disclosure', 'public_disclosure'), ('Community development programs', 'community_development_programs'), ('Stakeholder engagement plans', 'stakeholder_engagement_plans'), ('Local community consultation committes', 'local_community_consultation_committes'), ('Works councils, occupational health and safety committees', 'works_councils,_occupational_health_and_safety_committees'), ('Community grievance processes', 'community_grievance_processes')], max_length=500),
        ),
    ]
