# Generated by Django 4.2.4 on 2024-10-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "analysis",
            "0051_alter_communitydevelopmentnumberofoperation_name_of_operation",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumedenergy",
            name="quantity",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=24, null=True
            ),
        ),
        migrations.AlterField(
            model_name="consumedenergy",
            name="quantiy_gj",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=24, null=True
            ),
        ),
        migrations.AlterField(
            model_name="directpurchasedenergy",
            name="quantity",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=24, null=True
            ),
        ),
        migrations.AlterField(
            model_name="directpurchasedenergy",
            name="quantiy_gj",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=24, null=True
            ),
        ),
        migrations.AlterField(
            model_name="energyconsumedoutsideorg",
            name="quantity",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=24, null=True
            ),
        ),
        migrations.AlterField(
            model_name="energyconsumedoutsideorg",
            name="quantiy_gj",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=24, null=True
            ),
        ),
        migrations.AlterField(
            model_name="energysold",
            name="quantity",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=24, null=True
            ),
        ),
        migrations.AlterField(
            model_name="energysold",
            name="quantiy_gj",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=24, null=True
            ),
        ),
        migrations.AlterField(
            model_name="reductionenergyconsumption",
            name="quantity",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=24, null=True
            ),
        ),
        migrations.AlterField(
            model_name="reductionenergyconsumption",
            name="quantiy_gj",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=24, null=True
            ),
        ),
        migrations.AlterField(
            model_name="reductionenergyinproductservices",
            name="quantity",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=24, null=True
            ),
        ),
        migrations.AlterField(
            model_name="reductionenergyinproductservices",
            name="quantiy_gj",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=24, null=True
            ),
        ),
        migrations.AlterField(
            model_name="selfgeneratedenergy",
            name="quantity",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=24, null=True
            ),
        ),
        migrations.AlterField(
            model_name="selfgeneratedenergy",
            name="quantiy_gj",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=24, null=True
            ),
        ),
    ]
