# Generated by Django 4.2.4 on 2024-10-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0052_alter_consumedenergy_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='governancebodydetails',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency', max_length=10),
            preserve_default=False,
        ),
    ]
