# Generated by Django 4.2.4 on 2024-10-08 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("datametric", "0040_alter_path_disclosure"),
        ("authentication", "0007_alter_client_uuid"),
        ("sustainapp", "0008_clienttaskdashboard_region_and_more"),
        ("analysis", "0053_governancebodydetails_currency"),
    ]

    operations = [
        migrations.CreateModel(
            name="NonRenewableMaterials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("month", models.IntegerField(null=True)),
                ("year", models.IntegerField()),
                ("type_of_material", models.CharField(max_length=100)),
                ("material_used", models.CharField(max_length=100)),
                ("source", models.CharField(max_length=100)),
                (
                    "quantity",
                    models.DecimalField(
                        choices=[
                            ("Milligram", "Milligram"),
                            ("Gram", "Gram"),
                            ("Kilogram", "Kilogram"),
                            ("Metric ton", "Metric ton"),
                            ("Pound", "Pound"),
                            ("US short ton", "US short ton"),
                            ("Milliliter", "Milliliter"),
                            ("Liter", "Liter"),
                            ("Fluid Ounce", "Fluid Ounce"),
                            ("Quart", "Quart"),
                            ("Gallon", "Gallon"),
                            ("Pint", "Pint"),
                            ("Cubic centimeter", "Cubic centimeter"),
                            ("Cubic decimeter", "Cubic decimeter"),
                            ("Cubic meter", "Cubic meter"),
                            ("Cubic foot", "Cubic foot"),
                        ],
                        decimal_places=6,
                        default="Milligram",
                        max_digits=20,
                    ),
                ),
                ("unit", models.CharField(max_length=100)),
                ("index", models.PositiveIntegerField()),
                ("data_source", models.CharField(max_length=100)),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.client",
                    ),
                ),
                (
                    "corporate",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sustainapp.corporateentity",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sustainapp.location",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sustainapp.organization",
                    ),
                ),
                (
                    "raw_response",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="datametric.rawresponse",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
