# Generated by Django 4.2.4 on 2024-10-08 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sustainapp", "0008_clienttaskdashboard_region_and_more"),
        ("authentication", "0007_alter_client_uuid"),
        ("datametric", "0040_alter_path_disclosure"),
        ("analysis", "0055_renewablematerials"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecycledInputMaterials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("month", models.IntegerField(null=True)),
                ("year", models.IntegerField()),
                ("recycled_material", models.CharField(max_length=100)),
                ("type_of_recycled_material", models.CharField(max_length=100)),
                (
                    "total_weight_or_volume",
                    models.DecimalField(decimal_places=6, max_digits=20),
                ),
                (
                    "amount_of_material_recycled",
                    models.DecimalField(decimal_places=6, max_digits=20),
                ),
                (
                    "amount_of_recycled_input_material_used",
                    models.DecimalField(decimal_places=6, max_digits=20),
                ),
                ("unit_material_recycled", models.CharField(max_length=100)),
                ("unit_input_material_used", models.CharField(max_length=100)),
                ("index", models.PositiveIntegerField()),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.client",
                    ),
                ),
                (
                    "corporate",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sustainapp.corporateentity",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sustainapp.location",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sustainapp.organization",
                    ),
                ),
                (
                    "raw_response",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="datametric.rawresponse",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
