# Generated by Django 4.2.4 on 2024-10-08 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("datametric", "0040_alter_path_disclosure"),
        ("sustainapp", "0008_clienttaskdashboard_region_and_more"),
        ("authentication", "0007_alter_client_uuid"),
        ("analysis", "0056_recycledinputmaterials"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReclaimedMaterials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("month", models.IntegerField(null=True)),
                ("year", models.IntegerField()),
                ("type_of_product_sold", models.CharField(max_length=100)),
                ("product_classification", models.CharField(max_length=100)),
                ("product_code", models.CharField(max_length=100)),
                ("product_name", models.CharField(max_length=100)),
                (
                    "amount_of_product_sold",
                    models.DecimalField(decimal_places=6, max_digits=10),
                ),
                ("product_sold_unit", models.CharField(max_length=100)),
                ("recycled_material_used", models.CharField(max_length=100)),
                ("type_of_recycled_material_used", models.CharField(max_length=100)),
                (
                    "amount_of_recycled_material_used",
                    models.DecimalField(decimal_places=6, max_digits=10),
                ),
                ("recycled_material_used_unit", models.CharField(max_length=100)),
                ("data_collection_method", models.CharField(max_length=100)),
                ("index", models.PositiveIntegerField()),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.client",
                    ),
                ),
                (
                    "corporate",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sustainapp.corporateentity",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sustainapp.location",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sustainapp.organization",
                    ),
                ),
                (
                    "raw_response",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="datametric.rawresponse",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
