# Generated by Django 4.2.4 on 2024-10-09 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_client_uuid'),
        ('datametric', '0040_alter_path_disclosure'),
        ('sustainapp', '0008_clienttaskdashboard_region_and_more'),
        ('analysis', '0057_reclaimedmaterials'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompensationIncrease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('highest_paid_individual_percentage_increase', models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Percentage increase in annual total compensation for the organization's highest-paid individual")),
                ('median_employee_percentage_increase', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Median percentage increase in annual total compensation for all employees excluding the highest-paid individual')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Compensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.IntegerField(null=True)),
                ('year', models.IntegerField()),
                ('highest_paid_individual_compensation', models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Annual total compensation for the organization's highest-paid individual")),
                ('median_employee_compensation', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Median annual total compensation for all employees excluding the highest-paid individual')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client')),
                ('corporate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location')),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization')),
                ('raw_response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
