# Generated by Django 4.2.4 on 2024-10-09 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_client_uuid'),
        ('datametric', '0040_alter_path_disclosure'),
        ('sustainapp', '0008_clienttaskdashboard_region_and_more'),
        ('analysis', '0058_compensationincrease_compensation'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensationincrease',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.AddField(
            model_name='compensationincrease',
            name='corporate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity'),
        ),
        migrations.AddField(
            model_name='compensationincrease',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location'),
        ),
        migrations.AddField(
            model_name='compensationincrease',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='compensationincrease',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization'),
        ),
        migrations.AddField(
            model_name='compensationincrease',
            name='raw_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse'),
        ),
        migrations.AddField(
            model_name='compensationincrease',
            name='year',
            field=models.IntegerField(default=2024),
            preserve_default=False,
        ),
    ]
