# Generated by Django 5.1.1 on 2024-10-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0059_compensationincrease_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='injuryreport',
            name='index',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
