# Generated by Django 4.2.4 on 2024-10-15 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0009_alter_trackdashboard_report_name'),
        ('authentication', '0007_alter_client_uuid'),
        ('datametric', '0040_alter_path_disclosure'),
        ('analysis', '0060_injuryreport_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralWorkersNotEmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.IntegerField(null=True)),
                ('year', models.IntegerField()),
                ('type_of_worker', models.CharField(blank=True, max_length=255, null=True)),
                ('total_workers', models.FloatField()),
                ('contractual_relationship', models.CharField(blank=True, max_length=255, null=True)),
                ('work_performed', models.CharField(blank=True, max_length=255, null=True)),
                ('engagement_approach', models.CharField(blank=True, max_length=255, null=True)),
                ('third_party', models.CharField(blank=True, max_length=255, null=True)),
                ('index', models.PositiveIntegerField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client')),
                ('corporate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location')),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization')),
                ('raw_response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralTotalEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.IntegerField(null=True)),
                ('year', models.IntegerField()),
                ('employment_type', models.CharField(choices=[('permanent employee', 'Permanent Employee'), ('temporary employee', 'Temporary Employee'), ('non-guaranteed-employee', 'Non-guaranteed Employee'), ('full-time employee', 'Full-time Employee'), ('part-time employee', 'Part-time Employee')], max_length=255)),
                ('age_group', models.CharField(choices=[('less than 30 years old', 'Less than 30 years old'), ('30-50 years old', '30-50 years old'), ('greater than 50 years old', 'Greater than 50 years old')], max_length=255)),
                ('value', models.IntegerField()),
                ('index', models.IntegerField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client')),
                ('corporate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='total_employees_gender', to='analysis.gender')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location')),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization')),
                ('raw_response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralCollectiveBargaining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.IntegerField(null=True)),
                ('year', models.IntegerField()),
                ('emp_covered_by_cb', models.FloatField()),
                ('emp_in_org', models.FloatField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client')),
                ('corporate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location')),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization')),
                ('raw_response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
