# Generated by Django 4.2.4 on 2024-10-21 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_client_uuid'),
        ('datametric', '0040_alter_path_disclosure'),
        ('sustainapp', '0013_alter_clienttaskdashboard_location'),
        ('analysis', '0061_generalworkersnotemp_generaltotalemployees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoOperationsAssesed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.IntegerField(null=True)),
                ('year', models.IntegerField()),
                ('operations_assessed', models.FloatField()),
                ('operations', models.FloatField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client')),
                ('corporate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location')),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization')),
                ('raw_response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
