# Generated by Django 4.2.4 on 2024-10-21 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0013_alter_clienttaskdashboard_location'),
        ('authentication', '0007_alter_client_uuid'),
        ('datametric', '0040_alter_path_disclosure'),
        ('analysis', '0062_ecooperationsassesed'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoTotalBodyMembersRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.IntegerField(null=True)),
                ('year', models.IntegerField()),
                ('table_name', models.CharField(choices=[('communicated anti-corruption policy - emp category', 'Communicated anti-corruption policy - Employee Category'), ('communicated anti-corruption policy - business partner', 'Communicated anti-corruption policy - Business Partner'), ('received training on anti-corruption - region', 'Received training on anti-corruption - Region')], max_length=255)),
                ('emp_category_or_business_partner', models.CharField(choices=[('emp category', 'Employee Category'), ('business partner', 'Business Partner')], max_length=32)),
                ('specific_total', models.PositiveBigIntegerField(blank=True, null=True)),
                ('total', models.PositiveBigIntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client')),
                ('corporate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location')),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization')),
                ('raw_response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EcoTotalBodyMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.IntegerField(null=True)),
                ('year', models.IntegerField()),
                ('table_name', models.CharField(choices=[('communicated anti-corruption policy - region', 'Communicated anti-corruption policy - region'), ('received training on anti-corruption - region', 'Received training on anti-corruption - region')], max_length=255)),
                ('specific_total', models.PositiveBigIntegerField(blank=True, null=True)),
                ('total', models.PositiveBigIntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client')),
                ('corporate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location')),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization')),
                ('raw_response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
