# Generated by Django 4.2.4 on 2024-10-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0063_ecototalbodymembersregion_ecototalbodymembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecototalbodymembers',
            name='index',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ecototalbodymembersregion',
            name='index',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
