# Generated by Django 4.2.4 on 2024-10-22 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0013_alter_clienttaskdashboard_location'),
        ('analysis', '0064_ecototalbodymembers_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecototalbodymembers',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ecototalbodymembersregion',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ecototalbodymembers',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location'),
        ),
        migrations.AlterField(
            model_name='ecototalbodymembersregion',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location'),
        ),
    ]
