# Generated by Django 4.2.4 on 2024-10-23 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datametric', '0040_alter_path_disclosure'),
        ('sustainapp', '0013_alter_clienttaskdashboard_location'),
        ('authentication', '0007_alter_client_uuid'),
        ('analysis', '0065_ecototalbodymembers_location_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoStandardWages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.IntegerField(null=True)),
                ('year', models.IntegerField()),
                ('currency', models.CharField(blank=True, max_length=255, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.PositiveBigIntegerField(blank=True, null=True)),
                ('minimum_wage', models.PositiveBigIntegerField(blank=True, null=True)),
                ('minimum_wage_currency', models.CharField(blank=True, max_length=255, null=True)),
                ('index', models.PositiveBigIntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client')),
                ('corporate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='analysis.gender')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location')),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization')),
                ('raw_response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datametric.rawresponse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
