# Generated by Django 4.2.4 on 2024-06-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sustainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="country",
            field=models.CharField(default="IN", max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="location",
            name="state",
            field=models.CharField(default="UP", max_length=256),
            preserve_default=False,
        ),
    ]
