# Generated by Django 4.2.4 on 2024-10-24 05:40

import authentication.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_client_alter_customuser_client'),
        ('analysis', '0003_alter_changeinwaterstorage_client_and_more'),
        ('datametric', '0003_alter_rawresponse_client'),
        ('materiality_dashboard', '0003_alter_materialityassessment_client'),
        ('sustainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisdata2',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, on_delete=django.db.models.deletion.CASCADE, related_name='AnalysisData2client', to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, on_delete=django.db.models.deletion.CASCADE, related_name='batchclient', to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='bussinessactivity',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, on_delete=django.db.models.deletion.CASCADE, related_name='Bussinessactivityclient', to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='bussinessrelationship',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, on_delete=django.db.models.deletion.CASCADE, related_name='Bussinessrelationship_client', to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='companyactivities',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, on_delete=django.db.models.deletion.CASCADE, related_name='Companyactivitiesclient', to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='corporateentity',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, on_delete=django.db.models.deletion.CASCADE, related_name='corporatenetityclient', to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='location',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, on_delete=django.db.models.deletion.CASCADE, related_name='locationclient', to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='mygoal',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, on_delete=django.db.models.deletion.CASCADE, related_name='Mygoalclient', to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, on_delete=django.db.models.deletion.CASCADE, related_name='client_Org', to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='report',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, on_delete=django.db.models.deletion.CASCADE, related_name='client_reports', to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='rowdatabatch',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, on_delete=django.db.models.deletion.CASCADE, related_name='RowDataBatchclient', to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, on_delete=django.db.models.deletion.CASCADE, related_name='Stakeholderclient', to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='stakeholdergroup',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, on_delete=django.db.models.deletion.CASCADE, related_name='Stakeholdergroupclient', to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='task',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, on_delete=django.db.models.deletion.CASCADE, related_name='Taskclient', to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='taskdashboard',
            name='client',
            field=models.ForeignKey(blank=True, default=authentication.models.Client.get_default_client, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TaskDashboard_client', to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='user_client',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, on_delete=django.db.models.deletion.CASCADE, related_name='client_userclient', to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='userorg',
            name='client',
            field=models.ForeignKey(default=authentication.models.Client.get_default_client, on_delete=django.db.models.deletion.CASCADE, related_name='client_User_Org', to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='zohoinfo',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zoho_info', to='authentication.client'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
