# Generated by Django 4.2.4 on 2024-07-11 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0002_alter_location_country_alter_location_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginCounter',
        ),
    ]
