# Generated by Django 4.2.4 on 2024-07-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sustainapp", "0002_alter_location_country_alter_location_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="logincounter",
            name="needs_password_change",
            field=models.BooleanField(default=True),
        ),
    ]
