# Generated by Django 4.2.4 on 2024-08-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0003_delete_logincounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='investment_corporates',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
