# Generated by Django 5.1.1 on 2024-10-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0003_alter_clienttaskdashboard_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackdashboard',
            name='report_name',
            field=models.CharField(choices=[('emission', 'Emission'), ('energy', 'Energy'), ('waste', 'Waste'), ('employment', 'Employment'), ('ohs', 'Occupational Health and Safety (OHS)'), ('diversity_inclusion', 'Diversity & Inclusion'), ('community_development', 'Community Development'), ('water_and_effluents', 'Water & Effluents'), ('material', 'Material'), ('general', 'General'), ('economic', 'Economic')], max_length=1024),
        ),
    ]
