# Generated by Django 4.2.4 on 2024-07-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sustainapp", "0003_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="logincounter",
            name="needs_password_change",
            field=models.BooleanField(default=True),
        ),
    ]
