# Generated by Django 4.2.4 on 2024-09-11 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_logincounter'),
        ('sustainapp', '0004_report_investment_corporates'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_name', models.CharField(choices=[('emission', 'Emission'), ('energy', 'Energy'), ('waste', 'Waste'), ('employment', 'Employment'), ('ohs', 'Occupational Health and Safety (OHS)'), ('diversity_inclusion', 'Diversity & Inclusion'), ('community_development', 'Community Development')], max_length=1024)),
                ('report_id', models.CharField(max_length=255)),
                ('group_id', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_dashboard', to='authentication.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
