# Generated by Django 4.2.4 on 2024-09-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0006_alter_trackdashboard_report_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackdashboard',
            name='client',
        ),
        migrations.AddField(
            model_name='trackdashboard',
            name='table_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
