# Generated by Django 4.2.4 on 2024-10-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0007_remove_trackdashboard_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttaskdashboard',
            name='region',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='clienttaskdashboard',
            name='activity',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
