# Generated by Django 4.2.4 on 2025-01-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0007_alter_clienttaskdashboard_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttaskdashboard',
            name='comments_assignee',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clienttaskdashboard',
            name='task_status',
            field=models.CharField(choices=[('in_progress', 'in_progress'), ('approved', 'approved'), ('under_review', 'under_review'), ('completed', 'completed'), ('reject', 'reject'), ('not_started', 'not_started')], default='in_progress', max_length=64),
        ),
    ]
