# Generated by Django 4.2.4 on 2024-10-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0008_clienttaskdashboard_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackdashboard',
            name='report_name',
            field=models.CharField(choices=[('emission', 'Emission'), ('energy', 'Energy'), ('waste', 'Waste'), ('employment', 'Employment'), ('ohs', 'Occupational Health and Safety (OHS)'), ('diversity_inclusion', 'Diversity & Inclusion'), ('community_development', 'Community Development'), ('water_and_effluents', 'Water & Effluents'), ('governance', 'Governance')], max_length=1024),
        ),
    ]
