# Generated by Django 4.2.4 on 2025-01-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0010_alter_clienttaskdashboard_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttaskdashboard',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
