# Generated by Django 5.1.1 on 2024-10-17 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0010_alter_trackdashboard_report_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackdashboard',
            name='table_name',
        ),
    ]
