# Generated by Django 4.2.4 on 2025-01-24 08:57

import authentication.models
import common.Validators.validate_future_date
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_usersafelock_last_failed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sustainapp', '0011_clienttaskdashboard_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyGoalOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=1024)),
                ('description', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField(help_text='Enter only future dates', validators=[common.Validators.validate_future_date.validate_future_date])),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('not_started', 'Not Started')], default='not_started', max_length=20)),
                ('client', models.ForeignKey(default=authentication.models.Client.get_default_client, on_delete=django.db.models.deletion.CASCADE, related_name='mygoal_client', to='authentication.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mygoal_created_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mygoal_organization', to='sustainapp.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
