# Generated by Django 4.2.4 on 2024-10-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0011_remove_trackdashboard_table_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clienttaskdashboard',
            old_name='factor_id',
            new_name='activity_id',
        ),
        migrations.RenameField(
            model_name='clienttaskdashboard',
            old_name='filename',
            new_name='unit_type',
        ),
        migrations.RemoveField(
            model_name='clienttaskdashboard',
            name='file',
        ),
        migrations.RemoveField(
            model_name='clienttaskdashboard',
            name='file_modified_at',
        ),
        migrations.AddField(
            model_name='clienttaskdashboard',
            name='file_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clienttaskdashboard',
            name='task_status',
            field=models.CharField(choices=[('in_progress', 'in_progress'), ('approved', 'approved'), ('under_review', 'under_review'), ('completed', 'completed'), ('reject', 'reject')], default='in_progress', max_length=64),
        ),
    ]
