# Generated by Django 4.2.4 on 2025-02-06 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0012_mygoalorganization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mygoalorganization',
            options={'verbose_name': 'My Goal', 'verbose_name_plural': 'My Goals'},
        ),
    ]
