# Generated by Django 4.2.4 on 2024-10-21 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0012_rename_factor_id_clienttaskdashboard_activity_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttaskdashboard',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.location'),
        ),
    ]
