# Generated by Django 4.2.4 on 2025-02-06 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sustainapp', '0012_mygoalorganization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mygoalorganization',
            options={'verbose_name': 'My Goal', 'verbose_name_plural': 'My Goals'},
        ),
        migrations.AddField(
            model_name='report',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
