# Generated by Django 4.2.4 on 2025-02-10 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0013_alter_mygoalorganization_options'),
        ('sustainapp', '0013_alter_mygoalorganization_options_and_more'),
    ]

    operations = [
    ]
