# Generated by Django 4.2.4 on 2025-02-18 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0015_alter_corporateentity_name_alter_location_name_and_more'),
        ('sustainapp', '0015_historicalmygoalorganization'),
    ]

    operations = [
    ]
