# Generated by Django 4.2.4 on 2025-03-25 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0016_merge_20250218_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='active',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='group',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='language',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='no_of_employees',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='ownership_and_legal_form',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='sub_industry',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='type_of_business_activities',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='type_of_corporate_entity',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='type_of_product',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='type_of_services',
        ),
    ]
