# Generated by Django 4.2.4 on 2025-03-26 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0018_remove_organization_type_corporate_entity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='type_of_incorporation',
            new_name='type_corporate_entity',
        ),
        migrations.RemoveField(
            model_name='corporateentity',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='corporateentity',
            name='group',
        ),
        migrations.RemoveField(
            model_name='corporateentity',
            name='language',
        ),
        migrations.RemoveField(
            model_name='corporateentity',
            name='legalform',
        ),
        migrations.RemoveField(
            model_name='corporateentity',
            name='location_of_headquarters',
        ),
        migrations.RemoveField(
            model_name='corporateentity',
            name='ownership',
        ),
        migrations.RemoveField(
            model_name='corporateentity',
            name='type_of_business_activities',
        ),
        migrations.RemoveField(
            model_name='corporateentity',
            name='type_of_business_relationship',
        ),
        migrations.RemoveField(
            model_name='corporateentity',
            name='type_of_product',
        ),
        migrations.RemoveField(
            model_name='corporateentity',
            name='type_of_services',
        ),
        migrations.RemoveField(
            model_name='corporateentity',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='corporateentity',
            name='certification',
            field=models.ManyToManyField(blank=True, related_name='corporatecertification', to='sustainapp.certification'),
        ),
        migrations.AddField(
            model_name='corporateentity',
            name='rating',
            field=models.ManyToManyField(blank=True, related_name='corporaterating', to='sustainapp.rating'),
        ),
        migrations.AddField(
            model_name='corporateentity',
            name='regulation',
            field=models.ManyToManyField(blank=True, related_name='corporateregulation', to='sustainapp.regulation'),
        ),
        migrations.AddField(
            model_name='corporateentity',
            name='target',
            field=models.ManyToManyField(blank=True, related_name='corporatetarget', to='sustainapp.target'),
        ),
        migrations.AlterField(
            model_name='corporateentity',
            name='Country',
            field=models.CharField(default='India', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corporateentity',
            name='address',
            field=models.CharField(default='Default', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corporateentity',
            name='city',
            field=models.CharField(default='Default', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corporateentity',
            name='corporatetype',
            field=models.CharField(default='Default', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corporateentity',
            name='currency',
            field=models.CharField(default='Default', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corporateentity',
            name='employeecount',
            field=models.CharField(default='100', max_length=256),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='corporateentity',
            name='framework',
        ),
        migrations.AlterField(
            model_name='corporateentity',
            name='location_headquarters',
            field=models.CharField(default='Default', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corporateentity',
            name='organization',
            field=models.ForeignKey(default=158, on_delete=django.db.models.deletion.CASCADE, related_name='corporatenetityorg', to='sustainapp.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corporateentity',
            name='phone',
            field=models.CharField(default='Default', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corporateentity',
            name='revenue',
            field=models.CharField(default='Default', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corporateentity',
            name='sector',
            field=models.CharField(default='Default', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corporateentity',
            name='state',
            field=models.CharField(default='Default', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corporateentity',
            name='subindustry',
            field=models.CharField(default='Default', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corporateentity',
            name='website',
            field=models.CharField(default='Default', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corporateentity',
            name='framework',
            field=models.ManyToManyField(blank=True, related_name='corporatenetityframework', to='sustainapp.framework'),
        ),
    ]
