# Generated by Django 4.2.4 on 2025-03-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0019_rename_type_of_incorporation_organization_type_corporate_entity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='area',
        ),
        migrations.RemoveField(
            model_name='location',
            name='type_of_business_activities',
        ),
        migrations.RemoveField(
            model_name='location',
            name='type_of_product',
        ),
        migrations.RemoveField(
            model_name='location',
            name='type_of_services',
        ),
        migrations.RemoveField(
            model_name='location',
            name='typelocation',
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(default='Default', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='currency',
            field=models.CharField(default='Default', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='employeecount',
            field=models.CharField(default='100', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='phone',
            field=models.CharField(default='Default', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='revenue',
            field=models.CharField(default='1000', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='sector',
            field=models.CharField(default='Default', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='streetaddress',
            field=models.CharField(default='Default', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='sub_industry',
            field=models.CharField(default='Default', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='website',
            field=models.CharField(default='Default', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='zipcode',
            field=models.CharField(default='Default', max_length=256),
            preserve_default=False,
        ),
    ]
