# Generated by Django 4.2.4 on 2025-03-27 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0020_remove_location_area_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corporateentity',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='countryoperation',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='location',
            name='location_type',
        ),
    ]
