# Generated by Django 4.2.4 on 2025-03-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0022_StringToIntConv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateentity',
            name='employeecount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='corporateentity',
            name='revenue',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='employeecount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='revenue',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='organization',
            name='employeecount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='organization',
            name='revenue',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
