# Generated by Django 4.2.4 on 2025-05-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0023_alter_corporateentity_employeecount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttaskdashboard',
            name='act_id',
            field=models.CharField(blank=True, help_text='This stores the unique emission factor ID', max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='clienttaskdashboard',
            name='factor',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
