dummy_response_data = {
    "screen_one": [
        {
            "page": "screen_one",
            "label": "Message from CEO",
            "subLabel": "Add message from CEO",
            "type": "richTextarea",
            "content": "",
        },
        {
            "page": "screen_one",
            "label": "CEO’s Name",
            "subLabel": "",
            "type": "input",
            "content": "",
        },
    ],
    "screen_two": [
        {
            "page": "screen_two",
            "label": "Activities, Value Chain, and Other Business Relationships",
            "subLabel": "Add Introduction about company’s domain",
            "type": "richTextarea",
            "content": "",
        },
        {
            "page": "screen_two",
            "label": "Entities Included in the Organization's Sustainability Reporting",
            "subLabel": "Add statement about sustainability performance data for all entities",
            "type": "richTextarea",
            "content": "",
        },
        {
            "page": "screen_two",
            "label": "Supply Chain",
            "subLabel": "Add statement about company's supply chain process",
            "type": "richTextarea",
            "content": "",
        },
    ],
    "screen_three": [
        {
            "page": "screen_three",
            "label": "Mission, Vision, and Values",
            "subLabel": "Add statement about Mission, Vision and Values of the company",
            "type": "richTextarea",
            "content": "",
        }
    ],
    "screen_four": [
        {
            "page": "screen_four",
            "label": "Sustainability Roadmap",
            "subLabel": "",
            "type": "richTextarea",
            "content": "",
        }
    ],
    "screen_five": [
        {
            "page": "screen_five",
            "label": "Awards & Recognition",
            "subLabel": "",
            "type": "richTextarea",
            "content": "",
        }
    ],
    "screen_six": [
        {
            "page": "screen_six",
            "label": "Stakeholder Engagement",
            "subLabel": "Add statement about stakeholder engagement",
            "type": "textarea",
            "content": "",
        }
    ],
    "screen_seven": [
        {
            "page": "screen_seven",
            "label": "About the Report",
            "subLabel": "Add statement about the report",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_seven",
            "label": "Frameworks",
            "subLabel": "Add statement about framework used in report",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_seven",
            "label": "External Assurance",
            "subLabel": "Add statement about external assurance",
            "type": "textarea",
            "content": "",
        },
    ],
    "screen_eight": [
        {
            "page": "screen_eight",
            "label": "Materiality",
            "subLabel": "Add statement about company’s materiality assessment",
            "type": "textarea",
            "content": "",
        }
    ],
    "screen_nine": [
        {
            "page": "screen_nine",
            "label": "Corporate Governance",
            "subLabel": "Add statement about company’s corporate governance",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_nine",
            "label": "Governance structure and composition",
            "subLabel": "Add statement about company’s board of directors",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_nine",
            "label": "Remuneration Policies & Process to Determine Remuneration",
            "subLabel": "Add statement about company’s remuneration policies",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_nine",
            "label": "Reason why policy is not publicly available",
            "subLabel": "Add statement about company’s sustainability policies",
            "type": "textarea",
            "content": "",
        },
    ],
    "screen_ten": [
        {
            "page": "screen_ten",
            "label": "Sustainability Journey",
            "subLabel": "Add statement about company’s sustainability journey",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_ten",
            "label": "Management approach for sustainability/ESG topics",
            "subLabel": "Add statement about company’s approach for sustainability",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_ten",
            "label": "Company’s Sustainability Goals",
            "subLabel": "Add statement about company’s sustainability goals",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_ten",
            "label": "Supply Chain Sustainability",
            "subLabel": "Add statement about company’s approach to supply chain sustainability",
            "type": "textarea",
            "content": "",
        },
    ],
    "screen_eleven": [
        {
            "page": "screen_eleven",
            "label": "Economic Performance",
            "subLabel": "Add statement about company’s economic performance",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_eleven",
            "label": "Financial Assistance Received from Government",
            "subLabel": "Add introduction about financial assistance received from government",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_eleven",
            "label": "Economic Value Creation",
            "subLabel": "Add introduction for company’s economic value creation",
            "type": "textarea",
            "content": "",
        },
    ],
    "screen_twelve": [
        {
            "page": "screen_twelve",
            "label": "Environment",
            "subLabel": "Add statement about company’s responsibility to minimize the environmental impact",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_twelve",
            "label": "Emissions",
            "subLabel": "Add statement about company’s strategy to reduce emission",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_twelve",
            "label": "Scope 1 GHG Emissions",
            "subLabel": "Add statement about company’s scope 1 emissions",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_twelve",
            "label": "Scope 2 GHG Emissions",
            "subLabel": "Add statement about company’s scope 2 emissions",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_twelve",
            "label": "Scope 3 GHG Emissions",
            "subLabel": "Add statement about company’s scope 3 emissions",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_twelve",
            "label": "GHG Emission Intensity",
            "subLabel": "Add statement about tracking of GHG emission intensity",
            "type": "richTextarea",
            "content": "",
        },
        {
            "page": "screen_twelve",
            "label": "Reduction in GHG Emissions",
            "subLabel": "Add statement about efforts to reduce GHG emission",
            "type": "richTextarea",
            "content": "",
        },
        {
            "page": "screen_twelve",
            "label": "Ozone Depleting Substances",
            "subLabel": "Add statement about company’s commitment to eliminate use of ozone depleting substance",
            "type": "richTextarea",
            "content": "",
        },
        {
            "page": "screen_twelve",
            "label": "Materials",
            "subLabel": "Add statement about company’s material management strategy",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_twelve",
            "label": "Recycled Input Materials Used",
            "subLabel": "Add statement about company’s process for recycling",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_twelve",
            "label": "Reclaimed Products and Their Packaging Materials",
            "subLabel": "Add statement about company’s reclamation and recycling process",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_twelve",
            "label": "Water Withdrawal",
            "subLabel": "Add statement about company’s tracking of water withdrawal",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_twelve",
            "label": "Water Consumption",
            "subLabel": "Add statement about company’s water consumption goals",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_twelve",
            "label": "Energy Consumption within the Organization",
            "subLabel": "Add statement about company’s energy consumption within organisation",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_twelve",
            "label": "Energy Consumption Outside of the Organization",
            "subLabel": "Add statement about company’s energy consumption outside of the organisation",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_twelve",
            "label": "Energy Intensity",
            "subLabel": "Add statement about tracking the Energy Intensity",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_twelve",
            "label": "Reduction in Energy consumption",
            "subLabel": "Add statement about company’s commitment to reduce energy consumption",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_twelve",
            "label": "Significant Spills",
            "subLabel": "Add statement about company’s programs for preventing and managing significant spills",
            "type": "richTextarea",
            "content": "",
        },
        {
            "page": "screen_twelve",
            "label": "Habitat Protected and Restored",
            "subLabel": "Add statement about company’s commitment to protect and restore habitats",
            "type": "richTextarea",
            "content": "",
        },
        {
            "page": "screen_twelve",
            "label": "Air Quality",
            "subLabel": "Add statement about company’s commitment to protect and maintain air quality",
            "type": "richTextarea",
            "content": "",
        },
        {
            "page": "screen_twelve",
            "label": "Biogenic CO2 emissions",
            "subLabel": "",
            "type": "richTextarea",
            "content": "",
        },
        {
            "page": "screen_twelve",
            "label": "305-3-c. Biogenic CO2 emissions",
            "subLabel": "",
            "type": "richTextarea",
            "content": "",
        },
    ],
    "screen_thirteen": [
        {
            "page": "screen_thirteen",
            "label": "People",
            "subLabel": "Add statement about company’s employees and their policies",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_thirteen",
            "label": "Employee Hire, Turnover",
            "subLabel": "Add statement about company’s workforce hire and retention",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_thirteen",
            "label": "Standard Wage",
            "subLabel": "Add statement about company’s Policy on employee compensation",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_thirteen",
            "label": "Performance and Career Development Reviews of Employees",
            "subLabel": "Add statement about company’s process for performance review of employees",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_thirteen",
            "label": "Forced or Compulsory Labour",
            "subLabel": "Add statement about company’s position on forced / compulsory labor",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_thirteen",
            "label": "Incidents of Child Labour",
            "subLabel": "Add statement about company’s position on child labor",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_thirteen",
            "label": "Diversity of Governance Bodies and Employees",
            "subLabel": "Add statement about company’s position on diversity of employees",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_thirteen",
            "label": "Programs for Upgrading Employee Skills and Transition Assistance Programs",
            "subLabel": "Add statement about company’s programs for upgrading employee’s skills",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_thirteen",
            "label": "Remuneration",
            "subLabel": "Add statement about company’s remuneration practices & policies.",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_thirteen",
            "label": "Worker Participation, Consultation, and Communication on OHS",
            "subLabel": "Add statement about company’s OHS policies",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_thirteen",
            "label": "Hazard, Risk Identification and Investigation",
            "subLabel": "Add statement about company’s process of Hazard and risk assessment",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_thirteen",
            "label": "Work-Related Ill-Health & Injuries",
            "subLabel": "Add statement about work related ill health and injuries in company",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_thirteen",
            "label": "Safety Training",
            "subLabel": "Add statement about company’s safety training",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_thirteen",
            "label": "Workers Covered by OHS Management System",
            "subLabel": "Add statement about company’s OHS management system",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_thirteen",
            "label": "Operations and Suppliers in Which the Right to Freedom of Association and Collective Bargaining May Be at Risk",
            "subLabel": "Add statement about company’s views on freedom of association and collective bargaining",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_thirteen",
            "label": "Incidents of Violation/Discrimination",
            "subLabel": "Add statement about company’s policy for addressing violation/ discrimination",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_thirteen",
            "label": "Incidents of Violation of Rights of Indigenous People",
            "subLabel": "Add statement about company’s policy on violation of rights of indigenous people",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_thirteen",
            "label": "Parental Leaves",
            "subLabel": "Add statement about company’s policy on parental leave",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_thirteen",
            "label": "Percentage of security personnel who have received formal training in the organisation",
            "subLabel": "",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_thirteen",
            "label": "Percentage of security personnel who have received formal training from third-party organisation",
            "subLabel": "",
            "type": "textarea",
            "content": "",
        },
    ],
    "screen_fourteen": [
        {
            "page": "screen_fourteen",
            "label": "Community Engagement",
            "subLabel": "Add statement about company’s community engagement",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_fourteen",
            "label": "Impact Assessment",
            "subLabel": "",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_fourteen",
            "label": "CSR",
            "subLabel": "Add statement about company’s Corporate Social Responsibility policies",
            "type": "richTextarea",
            "content": "",
        },
    ],
    "screen_fifteen": [
        {
            "page": "screen_fifteen",
            "label": "Products and Services",
            "subLabel": "Add statement about company’s commitment to products and services",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_fifteen",
            "label": "Product and Service Information and Labelling",
            "subLabel": "Add statement about company’s product and service information and labelling",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_fifteen",
            "label": "Marketing",
            "subLabel": "Add statement about company’s marketing practices",
            "type": "textarea",
            "content": "",
        },
        {
            "page": "screen_fifteen",
            "label": "Conclusion",
            "subLabel": "Add a conclusion to the report",
            "type": "richTextarea",
            "content": "",
        },
    ],
}
