dummy_response_data = {
    "screen_one": [
        {
            "page": "screen_one",
            "label": "1. Message from CEO",
            "subLabel": "Add message from CEO",
            "type": "richTextarea",
            "content": "",
            "field": "message",
            "isSkipped": False,
        },
        {
            "page": "screen_one",
            "label": "CEO’s Name",
            "subLabel": "Add CEO's name",
            "type": "input",
            "content": "",
            "field": "ceo_name",
            "isSkipped": False,
        },
    ],
    "screen_two": [
        {
            "page": "screen_two",
            "label": "2. About the company and operations",
            "subLabel": "Add statement about stakeholder engagement",
            "type": "richTextarea",
            "content": "",
            "field": "about_the_company",
            "isSkipped": False,
        },
        {
            "page": "screen_two",
            "label": "2.1.1 Activities, Value Chain, and Other Business Relationships",
            "subLabel": "Add Introduction about company’s domain",
            "type": "richTextarea",
            "content": "",
            "field": "business_relations",
            "isSkipped": False,
        },
        {
            "page": "screen_two",
            "label": "2.1.2 Entities Included in the Organization's Sustainability Reporting",
            "subLabel": "Add statement about sustainability performance data for all entities",
            "type": "richTextarea",
            "content": "",
            "field": "entities_included",
            "isSkipped": False,
        },
        {
            "page": "screen_two",
            "label": "2.2 Supply Chain",
            "subLabel": "Add statement about company's supply chain process",
            "type": "richTextarea",
            "content": "",
            "field": "supply_chain_description",
            "isSkipped": False,
        },
    ],
    "screen_three": [
        {
            "page": "screen_three",
            "label": "3. Mission, Vision, and Values",
            "subLabel": "Add statement about Mission, Vision and Values of the company",
            "type": "richTextarea",
            "content": "",
            "field": "mission",
            "isSkipped": False,
        }
    ],
    "screen_four": [
        {
            "page": "screen_four",
            "label": "4. Sustainability Roadmap",
            "subLabel": "",
            "type": "richTextarea",
            "content": "",
            "field": "description",
            "isSkipped": False,
        }
    ],
    "screen_five": [
        {
            "page": "screen_five",
            "label": "5. Awards & Recognition",
            "subLabel": "",
            "type": "richTextarea",
            "content": "",
            "field": "description",
            "isSkipped": False,
        },
    ],
    "screen_six": [
        {
            "page": "screen_six",
            "label": "6. Stakeholder Engagement",
            "subLabel": "Add statement about stakeholder engagement",
            "type": "textarea",
            "content": "",
            "field": "description",
            "isSkipped": False,
        }
    ],
    "screen_seven": [
        {
            "page": "screen_seven",
            "label": "7. About the Report",
            "subLabel": "Add statement about the report",
            "type": "textarea",
            "content": "",
            "field": "description",
            "isSkipped": False,
        },
        {
            "page": "screen_seven",
            "label": "7.2 Frameworks",
            "subLabel": "Add statement about framework used in report",
            "type": "textarea",
            "content": "",
            "field": "framework_description",
            "isSkipped": False,
        },
        {
            "page": "screen_seven",
            "label": "7.3 External Assurance",
            "subLabel": "Add statement about external assurance",
            "type": "textarea",
            "content": "",
            "field": "external_assurance",
            "isSkipped": False,
        },
    ],
    "screen_eight": [
        {
            "page": "screen_eight",
            "label": "8. Materiality",
            "subLabel": "Add statement about company’s materiality assessment",
            "type": "textarea",
            "content": "",
            "field": "statement",
            "isSkipped": False,
        },
    ],
    "screen_nine": [
        {
            "page": "screen_nine",
            "label": "9. Corporate Governance",
            "subLabel": "Add statement about company’s corporate governance",
            "type": "textarea",
            "content": "",
            "field": "statement",
            "isSkipped": False,
        },
        {
            "page": "screen_nine",
            "label": "9.1.1 Governance structure and composition",
            "subLabel": "Add statement about company’s board of directors",
            "type": "textarea",
            "content": "",
            "field": "board_gov_statement",
            "isSkipped": False,
        },
        {
            "page": "screen_nine",
            "label": "9.3.7 Remuneration Policies & Process to Determine Remuneration",
            "subLabel": "Add statement about company’s remuneration policies",
            "type": "textarea",
            "content": "",
            "field": "remuneration_policies",
            "isSkipped": False,
        },
        {
            "page": "screen_nine",
            "label": "9.6.2 Reason why policy is not publicly available",
            "subLabel": "Add statement about company’s sustainability policies",
            "type": "textarea",
            "content": "",
            "field": "policy_not_public_reason",
            "isSkipped": False,
        },
    ],
    "screen_ten": [
        {
            "page": "screen_ten",
            "label": "10. Sustainability Journey",
            "subLabel": "Add statement about company’s sustainability journey",
            "type": "textarea",
            "content": "",
            "field": "company_sustainability_statement",
            "isSkipped": False,
        },
        {
            "page": "screen_ten",
            "label": "10.1 Management approach for sustainability/ESG topics",
            "subLabel": "Add statement about company’s approach for sustainability",
            "type": "textarea",
            "content": "",
            "field": "approach_for_sustainability",
            "isSkipped": False,
        },
        {
            "page": "screen_ten",
            "label": "10.2 Company’s Sustainability Goals",
            "subLabel": "Add statement about company’s sustainability goals",
            "type": "textarea",
            "content": "",
            "field": "sustainability_goals",
            "isSkipped": False,
        },
        {
            "page": "screen_ten",
            "label": "10.3 Supply Chain Sustainability",
            "subLabel": "Add statement about company’s approach to supply chain sustainability",
            "type": "textarea",
            "content": "",
            "field": "approach_to_supply_chain_sustainability",
            "isSkipped": False,
        },
    ],
    "screen_eleven": [
        {
            "page": "screen_eleven",
            "label": "11. Economic Performance",
            "subLabel": "Add statement about company’s economic performance",
            "type": "textarea",
            "content": "",
            "field": "company_economic_performance_statement",
            "isSkipped": False,
        },
        {
            "page": "screen_eleven",
            "label": "11.1.3 Financial Assistance Received from Government",
            "subLabel": "Add introduction about financial assistance received from government",
            "type": "textarea",
            "content": "",
            "field": "financial_assistance_from_government",
            "isSkipped": False,
        },
        {
            "page": "screen_eleven",
            "label": "11.1.2 Economic Value Creation",
            "subLabel": "Add introduction for company’s economic value creation",
            "type": "textarea",
            "content": "",
            "field": "introduction_to_economic_value_creation",
            "isSkipped": False,
        },
        {
            "page": "screen_eleven",
            "label": "11.2 Infrastructure Investment and Services Supported",
            "subLabel": "Add statement for infrastructure investment and services provided",
            "type": "textarea",
            "content": "",
            "field": "infrastructure_investement",
            "isSkipped": False,
        },
    ],
    "screen_twelve": [
        {
            "page": "screen_twelve",
            "label": "12. Environment",
            "subLabel": "Add statement about company’s responsibility to minimize the environmental impact",
            "type": "textarea",
            "content": "",
            "field": "environmental_responsibility_statement",
            "isSkipped": False,
        },
        {
            "page": "screen_twelve",
            "label": "12.1 Emissions",
            "subLabel": "Add statement about company’s strategy to reduce emission",
            "type": "textarea",
            "content": "",
            "field": "emissions",
            "isSkipped": False,
        },
        {
            "page": "screen_twelve",
            "label": "12.1.2 Scope 1 GHG Emissions",
            "subLabel": "Add statement about company’s scope 1 emissions",
            "type": "textarea",
            "content": "",
            "field": "scope_one_emissions",
            "isSkipped": False,
        },
        {
            "page": "screen_twelve",
            "label": "12.1.3 Scope 2 GHG Emissions",
            "subLabel": "Add statement about company’s scope 2 emissions",
            "type": "textarea",
            "content": "",
            "field": "scope_two_emissions",
            "isSkipped": False,
        },
        {
            "page": "screen_twelve",
            "label": "12.1.4 Scope 3 GHG Emissions",
            "subLabel": "Add statement about company’s scope 3 emissions",
            "type": "textarea",
            "content": "",
            "field": "scope_three_emissions",
            "isSkipped": False,
        },
        {
            "page": "screen_twelve",
            "label": "12.1.5 GHG Emission Intensity",
            "subLabel": "Add statement about tracking of GHG emission intensity",
            "type": "richTextarea",
            "content": "",
            "field": "ghg_emission_intensity_tracking",
            "isSkipped": False,
        },
        {
            "page": "screen_twelve",
            "label": "12.1.6 Reduction in GHG Emissions",
            "subLabel": "Add statement about efforts to reduce GHG emission",
            "type": "richTextarea",
            "content": "",
            "field": "ghg_emission_reduction_efforts",
            "isSkipped": False,
        },
        {
            "page": "screen_twelve",
            "label": "12.1.7 Ozone Depleting Substances",
            "subLabel": "Add statement about company’s commitment to eliminate use of ozone depleting substance",
            "type": "richTextarea",
            "content": "",
            "field": "ozone_depleting_substance_elimination",
            "isSkipped": False,
        },
        {
            "page": "screen_twelve",
            "label": "12.2 Materials",
            "subLabel": "Add statement about company’s material management strategy",
            "type": "textarea",
            "content": "",
            "field": "material_management_strategy",
            "isSkipped": False,
        },
        {
            "page": "screen_twelve",
            "label": "12.2.2 Recycled Input Materials Used",
            "subLabel": "Add statement about company’s process for recycling",
            "type": "textarea",
            "content": "",
            "field": "recycling_process",
            "isSkipped": False,
        },
        {
            "page": "screen_twelve",
            "label": "12.2.3 Reclaimed Products and Their Packaging Materials",
            "subLabel": "Add statement about company’s reclamation and recycling process",
            "type": "textarea",
            "content": "",
            "field": "reclamation_recycling_process",
            "isSkipped": False,
        },
        {
            "page": "screen_twelve",
            "label": "12.3.2 Water Withdrawal",
            "subLabel": "Add statement about company’s tracking of water withdrawal",
            "type": "textarea",
            "content": "",
            "field": "water_withdrawal_tracking",
            "isSkipped": False,
        },
        {
            "page": "screen_twelve",
            "label": "12.3.4 Water Consumption",
            "subLabel": "Add statement about company’s water consumption goals",
            "type": "textarea",
            "content": "",
            "field": "water_consumption_goals",
            "isSkipped": False,
        },
        {
            "page": "screen_twelve",
            "label": "12.4.2 Energy Consumption within the Organization",
            "subLabel": "Add statement about company’s energy consumption within organisation",
            "type": "textarea",
            "content": "",
            "field": "energy_consumption_within_organization",
            "isSkipped": False,
        },
        {
            "page": "screen_twelve",
            "label": "12.4.3 Energy Consumption Outside of the Organization",
            "subLabel": "Add statement about company’s energy consumption outside of the organisation",
            "type": "textarea",
            "content": "",
            "field": "energy_consumption_outside_organization",
            "isSkipped": False,
        },
        {
            "page": "screen_twelve",
            "label": "12.4.4 Energy Intensity",
            "subLabel": "Add statement about tracking the Energy Intensity",
            "type": "textarea",
            "content": "",
            "field": "energy_intensity_tracking",
            "isSkipped": False,
        },
        {
            "page": "screen_twelve",
            "label": "12.4.5 Reduction in Energy consumption",
            "subLabel": "Add statement about company’s commitment to reduce energy consumption",
            "type": "textarea",
            "content": "",
            "field": "energy_consumption_reduction_commitment",
            "isSkipped": False,
        },
        {
            "page": "screen_twelve",
            "label": "12.5.6 Significant Spills",
            "subLabel": "Add statement about company’s programs for preventing and managing significant spills",
            "type": "richTextarea",
            "content": "",
            "field": "significant_spills",
            "isSkipped": False,
        },
        {
            "page": "screen_twelve",
            "label": "12.6.2 Habitat Protected and Restored",
            "subLabel": "Add statement about company’s commitment to protect and restore habitats",
            "type": "richTextarea",
            "content": "",
            "field": "habitat_protection_restoration_commitment",
            "isSkipped": False,
        },
        {
            "page": "screen_twelve",
            "label": "12.7 Air Quality",
            "subLabel": "Add statement about company’s commitment to protect and maintain air quality",
            "type": "richTextarea",
            "content": "",
            "field": "air_quality_protection_commitment",
            "isSkipped": False,
        },
        {
            "page": "screen_twelve",
            "label": "Biogenic CO2 emissions",
            "subLabel": "",
            "type": "richTextarea",
            "content": "",
            "field": "biogenic_c02_emissions",
            "isSkipped": False,
        },
        {
            "page": "screen_twelve",
            "label": "305-3-c. Biogenic CO2 emissions",
            "subLabel": "",
            "type": "richTextarea",
            "content": "",
            "field": "biogenic_c02_emissions_305_3c",
            "isSkipped": False,
        },
        {
            "page": "screen_twelve",
            "label": "Consolidation Approach",
            "subLabel": "Add statement about tracking of Consolidation Approach",
            "type": "textarea",
            "content": "",
            "field": "consolidation",
            "isSkipped": False,
        },
        {
            "page": "screen_twelve",
            "label": "Base Year",
            "subLabel": "Add statement about emissions in the Base Year",
            "type": "textarea",
            "content": "",
            "field": "base_year",
            "isSkipped": False,
        },
    ],
    "screen_thirteen": [
        {
            "page": "screen_thirteen",
            "label": "13. People",
            "subLabel": "Add statement about company’s employees and their policies",
            "type": "textarea",
            "content": "",
            "field": "employee_policies_statement",
            "isSkipped": False,
        },
        {
            "page": "screen_thirteen",
            "label": "13.1.2 Employee Hire, Turnover",
            "subLabel": "Add statement about company’s workforce hire and retention",
            "type": "textarea",
            "content": "",
            "field": "workforce_hire_retention_statement",
            "isSkipped": False,
        },
        {
            "page": "screen_thirteen",
            "label": "13.1.5 Standard Wage",
            "subLabel": "Add statement about company’s Policy on employee compensation",
            "type": "textarea",
            "content": "",
            "field": "standard_wage",
            "isSkipped": False,
        },
        {
            "page": "screen_thirteen",
            "label": "13.1.6 Performance and Career Development Reviews of Employees",
            "subLabel": "Add statement about company’s process for performance review of employees",
            "type": "textarea",
            "content": "",
            "field": "performance_review_process",
            "isSkipped": False,
        },
        {
            "page": "screen_thirteen",
            "label": "13.2.3 Forced or Compulsory Labour",
            "subLabel": "Add statement about company’s position on forced / compulsory labor",
            "type": "textarea",
            "content": "",
            "field": "forced_labor_position",
            "isSkipped": False,
        },
        {
            "page": "screen_thirteen",
            "label": "13.3 Incidents of Child Labour",
            "subLabel": "Add statement about company’s position on child labor",
            "type": "textarea",
            "content": "",
            "field": "child_labor_position",
            "isSkipped": False,
        },
        {
            "page": "screen_thirteen",
            "label": "13.4.2 Diversity of Governance Bodies and Employees",
            "subLabel": "Add statement about company’s position on diversity of employees",
            "type": "textarea",
            "content": "",
            "field": "employee_diversity_position",
            "isSkipped": False,
        },
        {
            "page": "screen_thirteen",
            "label": "13.5.2 Programs for Upgrading Employee Skills and Transition Assistance Programs",
            "subLabel": "Add statement about company’s programs for upgrading employee’s skills",
            "type": "textarea",
            "content": "",
            "field": "employee_skill_upgrade_programs",
            "isSkipped": False,
        },
        {
            "page": "screen_thirteen",
            "label": "13.4.3 Remuneration",
            "subLabel": "Add statement about company’s remuneration practices & policies.",
            "type": "textarea",
            "content": "",
            "field": "remuneration_practices",
            "isSkipped": False,
        },
        {
            "page": "screen_thirteen",
            "label": "13.6.4 Worker Participation, Consultation, and Communication on OHS",
            "subLabel": "Add statement about company’s OHS policies",
            "type": "textarea",
            "content": "",
            "field": "ohs_policies",
            "isSkipped": False,
        },
        {
            "page": "screen_thirteen",
            "label": "13.6.7 Hazard, Risk Identification and Investigation",
            "subLabel": "Add statement about company’s process of Hazard and risk assessment",
            "type": "textarea",
            "content": "",
            "field": "hazard_risk_assessment",
            "isSkipped": False,
        },
        {
            "page": "screen_thirteen",
            "label": "13.6.8 Work-Related Ill-Health & Injuries",
            "subLabel": "Add statement about work related ill health and injuries in company",
            "type": "textarea",
            "content": "",
            "field": "work_related_health_injuries",
            "isSkipped": False,
        },
        {
            "page": "screen_thirteen",
            "label": "13.6.9 Safety Training",
            "subLabel": "Add statement about company’s safety training",
            "type": "textarea",
            "content": "",
            "field": "safety_training",
            "isSkipped": False,
        },
        {
            "page": "screen_thirteen",
            "label": "13.6.10 Workers Covered by OHS Management System",
            "subLabel": "Add statement about company’s OHS management system",
            "type": "textarea",
            "content": "",
            "field": "ohs_management_system",
            "isSkipped": False,
        },
        {
            "page": "screen_thirteen",
            "label": "13.7.2 Operations and Suppliers in Which the Right to Freedom of Association and Collective Bargaining May Be at Risk",
            "subLabel": "Add statement about company’s views on freedom of association and collective bargaining",
            "type": "textarea",
            "content": "",
            "field": "freedom_of_association_views",
            "isSkipped": False,
        },
        {
            "page": "screen_thirteen",
            "label": "13.8 Incidents of Violation/Discrimination",
            "subLabel": "Add statement about company’s policy for addressing violation/ discrimination",
            "type": "textarea",
            "content": "",
            "field": "violation_discrimination_policy",
            "isSkipped": False,
        },
        {
            "page": "screen_thirteen",
            "label": "13.8.2 Incidents of Violation of Rights of Indigenous People",
            "subLabel": "Add statement about company’s policy on violation of rights of indigenous people",
            "type": "textarea",
            "content": "",
            "field": "indigenous_rights_policy",
            "isSkipped": False,
        },
        {
            "page": "screen_thirteen",
            "label": "13.1.4 Parental Leaves",
            "subLabel": "Add statement about company’s policy on parental leave",
            "type": "textarea",
            "content": "",
            "field": "parental_leaves",
            "isSkipped": False,
        },
        {
            "page": "screen_thirteen",
            "label": "Percentage of security personnel who have received formal training in the organisation",
            "subLabel": "",
            "type": "textarea",
            "content": "",
            "field": "security_personnel_internal_training",
            "isSkipped": False,
        },
        {
            "page": "screen_thirteen",
            "label": "Percentage of security personnel who have received formal training from third-party organisation",
            "subLabel": "",
            "type": "textarea",
            "content": "",
            "field": "security_personnel_external_training",
            "isSkipped": False,
        },
    ],
    "screen_fourteen": [
        {
            "page": "screen_fourteen",
            "label": "14.1 Community Engagement",
            "subLabel": "Add statement about company’s community engagement",
            "type": "textarea",
            "content": "",
            "field": "community_engagement",
            "isSkipped": False,
        },
        {
            "page": "screen_fourteen",
            "label": "Impact Assessment",
            "subLabel": "",
            "type": "textarea",
            "content": "",
            "field": "impact_assessment",
            "isSkipped": False,
        },
        {
            "page": "screen_fourteen",
            "label": "14.2 CSR",
            "subLabel": "Add statement about company’s Corporate Social Responsibility policies",
            "type": "richTextarea",
            "content": "",
            "field": "csr_policies",
            "isSkipped": False,
        },
        {
            "page":"screen_fourteen",
            "label":"14.1.2 Incidents of Violation of Rights of Indigenous People",
            "subLabel":"Add statement about company’s policy on violation of rights of indigenous people",
            "type":"textarea",
            "content":"",
            "field":"violation_rights",
            "isSkipped":False
        },


    ],
    "screen_fifteen": [
        {
            "page": "screen_fifteen",
            "label": "15.1 Products and Services",
            "subLabel": "Add statement about company’s commitment to products and services",
            "type": "textarea",
            "content": "",
            "field": "commitment_statement",
            "isSkipped": False,
        },
        {
            "page": "screen_fifteen",
            "label": "15.2 Product and Service Information and Labelling",
            "subLabel": "Add statement about company’s product and service information and labelling",
            "type": "textarea",
            "content": "",
            "field": "product_info_labelling",
            "isSkipped": False,
        },
        {
            "page": "screen_fifteen",
            "label": "15.2.2 Marketing",
            "subLabel": "Add statement about company’s marketing practices",
            "type": "textarea",
            "content": "",
            "field": "marketing_practices",
            "isSkipped": False,
        },
        {
            "page": "screen_fifteen",
            "label": "Conclusion",
            "subLabel": "Add a conclusion to the report",
            "type": "richTextarea",
            "content": "",
            "field": "conclusion",
            "isSkipped": False,
        },
        {
        "page": "screen_fifteen",
        "label": "Customers",
        "subLabel": "Add statement about customers",
        "type": "textarea",
        "content": "",
        "field": "customers",
        "isSkipped": False,
      },
    ],
}
