from typing import Any
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from esg_report.models.ScreenNine import ScreenNine
from datametric.models import RawResponse
from esg_report.Serializer.ScreenNineSerializer import ScreenNineSerializer
from sustainapp.models import Report
from rest_framework.permissions import IsAuthenticated
from django.core.exceptions import ObjectDoesNotExist
