# Generated by Django 4.2.4 on 2024-09-19 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sustainapp', '0005_trackdashboard'),
        ('authentication', '0003_logincounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESGReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_esg_reports', to='authentication.client')),
                ('corporate_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='esg_reports', to='sustainapp.corporateentity')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='framework_esg_reports', to='sustainapp.framework')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esg_reports', to='sustainapp.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ESGReportIntroduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_type', models.CharField(choices=[('message_from_ceo', 'Message from CEO/MD/Chairman'), ('about_company', 'About the Company & Operations'), ('business_model', 'Business Model and Impact'), ('activities_value_chain', 'Activities, Value Chain, and Other Business Relationships'), ('entities_included', "Entities Included in the Organization's Sustainability Reporting"), ('supply_chain', 'Supply Chain'), ('mission_vision_values', 'Mission, Vision, Values'), ('position_statement', 'Position Statement'), ('sustainability_roadmap', 'Sustainability Roadmap'), ('awards_alliances', 'Awards & Alliances'), ('stakeholder_engagement', 'Stakeholder Engagement')], max_length=50)),
                ('content', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='esg_report_attachments/')),
                ('esg_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='introductions', to='esg_report.esgreport')),
            ],
            options={
                'unique_together': {('esg_report', 'section_type')},
            },
        ),
    ]
