# Generated by Django 4.2.4 on 2024-09-25 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esg_report', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ESGReportIntroduction',
        ),
    ]
