# Generated by Django 4.2.4 on 2024-09-25 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esg_report', '0002_delete_esgreportintroduction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ESGReport',
        ),
    ]
