# Generated by Django 4.2.4 on 2024-09-25 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sustainapp', '0005_trackdashboard'),
        ('authentication', '0003_logincounter'),
        ('esg_report', '0003_delete_esgreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESGReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_esg_reports', to='authentication.client')),
                ('corporate_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='esg_reports', to='sustainapp.corporateentity')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='framework_esg_reports', to='sustainapp.framework')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esg_reports', to='sustainapp.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CeoMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('message_image', models.ImageField(upload_to='esg_report/ceo_message/')),
                ('signature', models.CharField(max_length=255)),
                ('signature_image', models.ImageField(upload_to='esg_report/ceo_message/')),
                ('esg_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ceo_message', to='esg_report.esgreport')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
