# Generated by Django 4.2.4 on 2024-09-30 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0005_trackdashboard'),
        ('esg_report', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceomessage',
            name='esg_report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ceo_message', to='sustainapp.report'),
        ),
    ]
