# Generated by Django 4.2.4 on 2024-09-30 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0007_remove_trackdashboard_client_and_more'),
        ('esg_report', '0005_alter_ceomessage_esg_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutTheCompanyAndOperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('about_the_company', models.TextField()),
                ('about_the_company_image', models.FileField(blank=True, null=True, upload_to='esg_report/about_the_company/')),
                ('company_operations', models.TextField()),
                ('entities_included', models.TextField()),
                ('entities_included_image', models.FileField(blank=True, null=True, upload_to='esg_report/entities_included/')),
                ('supply_chain_description', models.TextField()),
                ('supply_chain_image', models.FileField(blank=True, null=True, upload_to='esg_report/supply_chain/')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='about_the_company_and_operations', to='sustainapp.report')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
