# Generated by Django 4.2.4 on 2024-09-30 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0007_remove_trackdashboard_client_and_more'),
        ('esg_report', '0006_aboutthecompanyandoperations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutthecompanyandoperations',
            old_name='company_operations',
            new_name='business_relations',
        ),
        migrations.CreateModel(
            name='MissionVisionValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mission', models.TextField(blank=True, null=True)),
                ('mission_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mission_vision_values', to='sustainapp.report')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
