# Generated by Django 4.2.4 on 2024-10-01 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0007_remove_trackdashboard_client_and_more'),
        ('esg_report', '0008_sustainabilityroadmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardAndRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='esg_report/award_recognition/')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='award_recognition', to='sustainapp.report')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
