# Generated by Django 4.2.4 on 2024-10-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esg_report', '0011_aboutthereport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ceomessage',
            old_name='esg_report',
            new_name='report',
        ),
    ]
