# Generated by Django 4.2.4 on 2024-10-02 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0007_remove_trackdashboard_client_and_more'),
        ('esg_report', '0012_rename_esg_report_ceomessage_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenNine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statement', models.TextField()),
                ('board_gov_statement', models.TextField()),
                ('remuneration_policies', models.TextField()),
                ('policy_not_public_reason', models.TextField(blank=True, null=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screen_nine', to='sustainapp.report')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialityStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statement', models.TextField()),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='materiality_statement', to='sustainapp.report')),
            ],
            options={
                'verbose_name': 'Materiality Statement',
                'verbose_name_plural': 'Materiality Statements',
            },
        ),
    ]
