# Generated by Django 4.2.4 on 2024-10-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg_report', '0013_screennine_materialitystatement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ceomessage',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='ceomessage',
            name='signature_image',
        ),
        migrations.AddField(
            model_name='ceomessage',
            name='ceo_name',
            field=models.TextField(default='something'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ceomessage',
            name='company_name',
            field=models.TextField(default='something'),
            preserve_default=False,
        ),
    ]
