# Generated by Django 4.2.4 on 2024-10-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg_report', '0014_remove_ceomessage_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceomessage',
            name='message_image',
            field=models.ImageField(blank=True, null=True, upload_to='esg_report/ceo_message/'),
        ),
    ]
