# Generated by Django 4.2.4 on 2024-10-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg_report', '0015_alter_ceomessage_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceomessage',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='esg_report/signature_image/'),
        ),
    ]
