# Generated by Django 4.2.4 on 2024-10-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg_report', '0016_ceomessage_signature_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceomessage',
            name='message_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ceomessage',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
