# Generated by Django 4.2.4 on 2024-10-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg_report', '0017_alter_ceomessage_message_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceomessage',
            name='signature_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
