# Generated by Django 4.2.4 on 2024-10-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg_report', '0018_alter_ceomessage_signature_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutthecompanyandoperations',
            name='about_the_company_image',
        ),
        migrations.RemoveField(
            model_name='aboutthecompanyandoperations',
            name='entities_included_image',
        ),
        migrations.RemoveField(
            model_name='aboutthecompanyandoperations',
            name='supply_chain_image',
        ),
        migrations.AlterField(
            model_name='aboutthecompanyandoperations',
            name='about_the_company',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutthecompanyandoperations',
            name='business_relations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutthecompanyandoperations',
            name='entities_included',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutthecompanyandoperations',
            name='supply_chain_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
