# Generated by Django 4.2.4 on 2024-10-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg_report', '0019_remove_aboutthecompanyandoperations_about_the_company_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceomessage',
            name='ceo_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ceomessage',
            name='company_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
