# Generated by Django 4.2.4 on 2024-10-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg_report', '0020_alter_ceomessage_ceo_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceomessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
