# Generated by Django 4.2.4 on 2024-10-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg_report', '0021_alter_ceomessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceomessage',
            name='message_image_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ceomessage',
            name='signature_image_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
