# Generated by Django 4.2.4 on 2024-10-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg_report', '0021_alter_ceomessage_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screennine',
            name='board_gov_statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='screennine',
            name='remuneration_policies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='screennine',
            name='statement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
