# Generated by Django 4.2.4 on 2024-10-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg_report', '0022_ceomessage_message_image_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sustainabilityroadmap',
            name='file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
