# Generated by Django 4.2.4 on 2024-10-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg_report', '0023_alter_sustainabilityroadmap_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardandrecognition',
            name='file',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missionvisionvalues',
            name='mission_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
