# Generated by Django 4.2.4 on 2024-10-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg_report', '0024_alter_awardandrecognition_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardandrecognition',
            name='file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
