# Generated by Django 4.2.4 on 2024-10-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg_report', '0025_alter_awardandrecognition_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutthereport',
            name='external_assurance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutthereport',
            name='framework_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
