# Generated by Django 4.2.4 on 2024-10-08 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0008_clienttaskdashboard_region_and_more'),
        ('esg_report', '0026_aboutthereport_external_assurance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenTen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_sustainability_statement', models.TextField(blank=True, null=True)),
                ('approach_for_sustainability', models.TextField(blank=True, null=True)),
                ('sustainability_goals', models.TextField(blank=True, null=True)),
                ('approach_to_supply_chain_sustainability', models.TextField(blank=True, null=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screen_ten', to='sustainapp.report')),
            ],
            options={
                'verbose_name': 'Screen Ten',
                'verbose_name_plural': 'Screen Ten',
                'db_table': 'screen_ten',
            },
        ),
    ]
