# Generated by Django 4.2.4 on 2024-10-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg_report', '0027_screenten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholderengagement',
            name='description',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
