# Generated by Django 4.2.4 on 2024-10-08 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0008_clienttaskdashboard_region_and_more'),
        ('esg_report', '0028_alter_stakeholderengagement_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenEleven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_economic_performance_statement', models.TextField(blank=True, null=True)),
                ('financial_assistance_from_government', models.TextField(blank=True, null=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screen_eleven', to='sustainapp.report')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
