# Generated by Django 4.2.4 on 2024-10-09 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esg_report', '0022_alter_screennine_board_gov_statement_and_more'),
        ('esg_report', '0029_screeneleven'),
    ]

    operations = [
    ]
