# Generated by Django 4.2.4 on 2024-10-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg_report', '0030_merge_20241009_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialitystatement',
            name='statement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
