# Generated by Django 4.2.4 on 2024-10-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg_report', '0031_alter_materialitystatement_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeneleven',
            name='introduction_to_economic_value_creation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
