# Generated by Django 4.2.4 on 2024-10-14 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0009_alter_trackdashboard_report_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('esg_report', '0033_historicalsustainabilityroadmap_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenTwelve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environmental_responsibility_statement', models.TextField(blank=True, help_text="Statement about company's responsibility to minimize the environmental impact", null=True)),
                ('emissions', models.TextField(blank=True, help_text="Description of the company's efforts to reduce emissions", null=True)),
                ('scope_one_emissions', models.TextField(blank=True, help_text='Add statement about company’s scope 1 emissions', null=True)),
                ('scope_two_emissions', models.TextField(blank=True, help_text='Add statement about company’s scope 2 emissions', null=True)),
                ('scope_three_emissions', models.TextField(blank=True, help_text='Add statement about company’s scope 3 emissions', null=True)),
                ('ghg_emission_intensity_tracking', models.TextField(blank=True, help_text='Statement about tracking of GHG emission intensity', null=True)),
                ('ghg_emission_reduction_efforts', models.TextField(blank=True, help_text='Statement about efforts to reduce GHG emissions', null=True)),
                ('ozone_depleting_substance_elimination', models.TextField(blank=True, help_text="Statement about company's commitment to eliminate use of ozone depleting substances", null=True)),
                ('material_management_strategy', models.TextField(blank=True, help_text="Statement about company's material management strategy", null=True)),
                ('recycling_process', models.TextField(blank=True, help_text="Statement about company's process for recycling", null=True)),
                ('reclamation_recycling_process', models.TextField(blank=True, help_text="Statement about company's reclamation and recycling process", null=True)),
                ('water_withdrawal_tracking', models.TextField(blank=True, help_text="Statement about company's tracking of water withdrawal", null=True)),
                ('water_consumption_goals', models.TextField(blank=True, help_text="Statement about company's water consumption goals", null=True)),
                ('energy_consumption_within_organization', models.TextField(blank=True, help_text="Statement about company's energy consumption within the organization", null=True)),
                ('energy_consumption_outside_organization', models.TextField(blank=True, help_text="Statement about company's energy consumption outside of the organization", null=True)),
                ('energy_intensity_tracking', models.TextField(blank=True, help_text='Statement about tracking the Energy Intensity', null=True)),
                ('energy_consumption_reduction_commitment', models.TextField(blank=True, help_text="Statement about company's commitment to reduce energy consumption", null=True)),
                ('significant_spills', models.TextField(blank=True, help_text="Statement about company's significant spills", null=True)),
                ('habitat_protection_restoration_commitment', models.TextField(blank=True, help_text="Statement about company's commitment to protect and restore habitats", null=True)),
                ('air_quality_protection_commitment', models.TextField(blank=True, help_text="Statement about company's commitment to protect and maintain air quality", null=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screen_twelve', to='sustainapp.report')),
            ],
            options={
                'verbose_name': 'Screen Twelve',
                'verbose_name_plural': 'Screen Twelve',
            },
        ),
        migrations.CreateModel(
            name='HistoricalScreenTwelve',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('environmental_responsibility_statement', models.TextField(blank=True, help_text="Statement about company's responsibility to minimize the environmental impact", null=True)),
                ('emissions', models.TextField(blank=True, help_text="Description of the company's efforts to reduce emissions", null=True)),
                ('scope_one_emissions', models.TextField(blank=True, help_text='Add statement about company’s scope 1 emissions', null=True)),
                ('scope_two_emissions', models.TextField(blank=True, help_text='Add statement about company’s scope 2 emissions', null=True)),
                ('scope_three_emissions', models.TextField(blank=True, help_text='Add statement about company’s scope 3 emissions', null=True)),
                ('ghg_emission_intensity_tracking', models.TextField(blank=True, help_text='Statement about tracking of GHG emission intensity', null=True)),
                ('ghg_emission_reduction_efforts', models.TextField(blank=True, help_text='Statement about efforts to reduce GHG emissions', null=True)),
                ('ozone_depleting_substance_elimination', models.TextField(blank=True, help_text="Statement about company's commitment to eliminate use of ozone depleting substances", null=True)),
                ('material_management_strategy', models.TextField(blank=True, help_text="Statement about company's material management strategy", null=True)),
                ('recycling_process', models.TextField(blank=True, help_text="Statement about company's process for recycling", null=True)),
                ('reclamation_recycling_process', models.TextField(blank=True, help_text="Statement about company's reclamation and recycling process", null=True)),
                ('water_withdrawal_tracking', models.TextField(blank=True, help_text="Statement about company's tracking of water withdrawal", null=True)),
                ('water_consumption_goals', models.TextField(blank=True, help_text="Statement about company's water consumption goals", null=True)),
                ('energy_consumption_within_organization', models.TextField(blank=True, help_text="Statement about company's energy consumption within the organization", null=True)),
                ('energy_consumption_outside_organization', models.TextField(blank=True, help_text="Statement about company's energy consumption outside of the organization", null=True)),
                ('energy_intensity_tracking', models.TextField(blank=True, help_text='Statement about tracking the Energy Intensity', null=True)),
                ('energy_consumption_reduction_commitment', models.TextField(blank=True, help_text="Statement about company's commitment to reduce energy consumption", null=True)),
                ('significant_spills', models.TextField(blank=True, help_text="Statement about company's significant spills", null=True)),
                ('habitat_protection_restoration_commitment', models.TextField(blank=True, help_text="Statement about company's commitment to protect and restore habitats", null=True)),
                ('air_quality_protection_commitment', models.TextField(blank=True, help_text="Statement about company's commitment to protect and maintain air quality", null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sustainapp.report')),
            ],
            options={
                'verbose_name': 'historical Screen Twelve',
                'verbose_name_plural': 'historical Screen Twelve',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
