# Generated by Django 4.2.4 on 2024-10-17 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sustainapp', '0009_alter_trackdashboard_report_name'),
        ('esg_report', '0035_screenthirteen_historicalscreenthirteen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenFourteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community_engagement', models.TextField(help_text='Add a statement about the company’s community engagement.', verbose_name='Community Engagement Statement')),
                ('impact_assessment', models.TextField(help_text='Add a statement about the company’s impact assessment.', verbose_name='Impact Assessment')),
                ('csr_policies', models.TextField(help_text='Add a statement about the company’s Corporate Social Responsibility policies.', verbose_name='Corporate Social Responsibility Policies')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screen_fourteen', to='sustainapp.report')),
            ],
            options={
                'verbose_name': 'Screen Fourteen',
                'verbose_name_plural': 'Screen Fourteen',
            },
        ),
        migrations.CreateModel(
            name='HistoricalScreenFourteen',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('community_engagement', models.TextField(help_text='Add a statement about the company’s community engagement.', verbose_name='Community Engagement Statement')),
                ('impact_assessment', models.TextField(help_text='Add a statement about the company’s impact assessment.', verbose_name='Impact Assessment')),
                ('csr_policies', models.TextField(help_text='Add a statement about the company’s Corporate Social Responsibility policies.', verbose_name='Corporate Social Responsibility Policies')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sustainapp.report')),
            ],
            options={
                'verbose_name': 'historical Screen Fourteen',
                'verbose_name_plural': 'historical Screen Fourteen',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
