# Generated by Django 4.2.4 on 2024-10-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg_report', '0036_screenfourteen_historicalscreenfourteen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalscreenfourteen',
            name='community_engagement',
            field=models.TextField(blank=True, help_text="Add a statement about the company's community engagement.", null=True, verbose_name='Community Engagement Statement'),
        ),
        migrations.AlterField(
            model_name='historicalscreenfourteen',
            name='csr_policies',
            field=models.TextField(blank=True, help_text="Add a statement about the company's Corporate Social Responsibility policies.", null=True, verbose_name='Corporate Social Responsibility Policies'),
        ),
        migrations.AlterField(
            model_name='historicalscreenfourteen',
            name='impact_assessment',
            field=models.TextField(blank=True, help_text="Add a statement about the company's impact assessment.", null=True, verbose_name='Impact Assessment'),
        ),
        migrations.AlterField(
            model_name='screenfourteen',
            name='community_engagement',
            field=models.TextField(blank=True, help_text="Add a statement about the company's community engagement.", null=True, verbose_name='Community Engagement Statement'),
        ),
        migrations.AlterField(
            model_name='screenfourteen',
            name='csr_policies',
            field=models.TextField(blank=True, help_text="Add a statement about the company's Corporate Social Responsibility policies.", null=True, verbose_name='Corporate Social Responsibility Policies'),
        ),
        migrations.AlterField(
            model_name='screenfourteen',
            name='impact_assessment',
            field=models.TextField(blank=True, help_text="Add a statement about the company's impact assessment.", null=True, verbose_name='Impact Assessment'),
        ),
    ]
