# Generated by Django 4.2.4 on 2024-10-18 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esg_report', '0037_alter_historicalscreenfourteen_community_engagement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalscreenthirteen',
            old_name='dynamic_question_answer',
            new_name='parental_leaves',
        ),
        migrations.RenameField(
            model_name='screenthirteen',
            old_name='dynamic_question_answer',
            new_name='parental_leaves',
        ),
    ]
