# Generated by Django 4.2.4 on 2024-10-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg_report', '0038_rename_dynamic_question_answer_historicalscreenthirteen_parental_leaves_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalscreentwelve',
            name='biogenic_c02_emissions',
            field=models.TextField(blank=True, help_text="Statement about company's biogenic CO2 emissions", null=True),
        ),
        migrations.AddField(
            model_name='historicalscreentwelve',
            name='biogenic_c02_emissions_305_3c',
            field=models.TextField(blank=True, help_text="Statement about company's biogenic CO2 emissions 305 3c", null=True),
        ),
        migrations.AddField(
            model_name='screentwelve',
            name='biogenic_c02_emissions',
            field=models.TextField(blank=True, help_text="Statement about company's biogenic CO2 emissions", null=True),
        ),
        migrations.AddField(
            model_name='screentwelve',
            name='biogenic_c02_emissions_305_3c',
            field=models.TextField(blank=True, help_text="Statement about company's biogenic CO2 emissions 305 3c", null=True),
        ),
    ]
