# Generated by Django 4.2.4 on 2024-10-18 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('esg_report', '0039_historicalscreentwelve_biogenic_c02_emissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenFifteenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commitment_statement', models.TextField(help_text="Add a statement about the company's commitment to products and services.", verbose_name="Company's Commitment to Products and Services")),
                ('product_info_labelling', models.TextField(help_text="Add a statement about the company's product and service information and labelling.", verbose_name='Product and Service Information and Labelling')),
                ('marketing_practices', models.TextField(help_text="Add a statement about the company's marketing practices.", verbose_name="Company's Marketing Practices")),
                ('conclusion', models.TextField(help_text='Add a conclusion to the report.', verbose_name='Conclusion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalScreenFifteenModel',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('commitment_statement', models.TextField(help_text="Add a statement about the company's commitment to products and services.", verbose_name="Company's Commitment to Products and Services")),
                ('product_info_labelling', models.TextField(help_text="Add a statement about the company's product and service information and labelling.", verbose_name='Product and Service Information and Labelling')),
                ('marketing_practices', models.TextField(help_text="Add a statement about the company's marketing practices.", verbose_name="Company's Marketing Practices")),
                ('conclusion', models.TextField(help_text='Add a conclusion to the report.', verbose_name='Conclusion')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical screen fifteen model',
                'verbose_name_plural': 'historical screen fifteen models',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
