# Generated by Django 4.2.4 on 2024-10-18 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0012_rename_factor_id_clienttaskdashboard_activity_id_and_more'),
        ('esg_report', '0040_screenfifteenmodel_historicalscreenfifteenmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalscreenfifteenmodel',
            name='report',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sustainapp.report'),
        ),
        migrations.AddField(
            model_name='screenfifteenmodel',
            name='report',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='screen_fifteen', to='sustainapp.report'),
            preserve_default=False,
        ),
    ]
