# Generated by Django 4.2.4 on 2024-10-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg_report', '0041_historicalscreenfifteenmodel_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalscreenfifteenmodel',
            name='commitment_statement',
            field=models.TextField(blank=True, help_text="Add a statement about the company's commitment to products and services.", null=True, verbose_name="Company's Commitment to Products and Services"),
        ),
        migrations.AlterField(
            model_name='historicalscreenfifteenmodel',
            name='conclusion',
            field=models.TextField(blank=True, help_text='Add a conclusion to the report.', null=True, verbose_name='Conclusion'),
        ),
        migrations.AlterField(
            model_name='historicalscreenfifteenmodel',
            name='marketing_practices',
            field=models.TextField(blank=True, help_text="Add a statement about the company's marketing practices.", null=True, verbose_name="Company's Marketing Practices"),
        ),
        migrations.AlterField(
            model_name='historicalscreenfifteenmodel',
            name='product_info_labelling',
            field=models.TextField(blank=True, help_text="Add a statement about the company's product and service information and labelling.", null=True, verbose_name='Product and Service Information and Labelling'),
        ),
        migrations.AlterField(
            model_name='screenfifteenmodel',
            name='commitment_statement',
            field=models.TextField(blank=True, help_text="Add a statement about the company's commitment to products and services.", null=True, verbose_name="Company's Commitment to Products and Services"),
        ),
        migrations.AlterField(
            model_name='screenfifteenmodel',
            name='conclusion',
            field=models.TextField(blank=True, help_text='Add a conclusion to the report.', null=True, verbose_name='Conclusion'),
        ),
        migrations.AlterField(
            model_name='screenfifteenmodel',
            name='marketing_practices',
            field=models.TextField(blank=True, help_text="Add a statement about the company's marketing practices.", null=True, verbose_name="Company's Marketing Practices"),
        ),
        migrations.AlterField(
            model_name='screenfifteenmodel',
            name='product_info_labelling',
            field=models.TextField(blank=True, help_text="Add a statement about the company's product and service information and labelling.", null=True, verbose_name='Product and Service Information and Labelling'),
        ),
    ]
