# Generated by Django 4.2.4 on 2024-10-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg_report', '0042_alter_historicalscreenfifteenmodel_commitment_statement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalscreenthirteen',
            name='percentage_of_security_personnel_who_have_received_formal_training_from_third_party_organisation',
            field=models.TextField(blank=True, help_text='Percentage of security personnel who have received formal training from third-party organisation', null=True, verbose_name='Percentage of Security Personnel Who Have Received Formal Training from Third-Party Organisation'),
        ),
        migrations.AddField(
            model_name='historicalscreenthirteen',
            name='percentage_of_security_personnel_who_have_received_formal_training_in_the_organisation',
            field=models.TextField(blank=True, help_text='Percentage of security personnel who have received formal training in the organisation', null=True, verbose_name='Percentage of Security Personnel Who Have Received Formal Training in the Organisation'),
        ),
        migrations.AddField(
            model_name='screenthirteen',
            name='percentage_of_security_personnel_who_have_received_formal_training_from_third_party_organisation',
            field=models.TextField(blank=True, help_text='Percentage of security personnel who have received formal training from third-party organisation', null=True, verbose_name='Percentage of Security Personnel Who Have Received Formal Training from Third-Party Organisation'),
        ),
        migrations.AddField(
            model_name='screenthirteen',
            name='percentage_of_security_personnel_who_have_received_formal_training_in_the_organisation',
            field=models.TextField(blank=True, help_text='Percentage of security personnel who have received formal training in the organisation', null=True, verbose_name='Percentage of Security Personnel Who Have Received Formal Training in the Organisation'),
        ),
    ]
