# Generated by Django 4.2.4 on 2024-10-24 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "esg_report",
            "0043_historicalscreenthirteen_percentage_of_security_personnel_who_have_received_formal_training_from_thi",
        ),
    ]

    operations = []
