# Generated by Django 4.2.4 on 2024-10-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg_report', '0047_historicalcontentindexrequirementomissionreason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentindexrequirementomissionreason',
            name='reason',
            field=models.CharField(choices=[('information unavailable/incomplete', 'Information unavailable/incomplete'), ('not applicable', 'Not applicable'), ('legal prohibitions', 'Legal prohibitions'), ('confidentiality constraints', 'Confidentiality constraints')], max_length=50, verbose_name='reason'),
        ),
        migrations.AlterField(
            model_name='historicalcontentindexrequirementomissionreason',
            name='reason',
            field=models.CharField(choices=[('information unavailable/incomplete', 'Information unavailable/incomplete'), ('not applicable', 'Not applicable'), ('legal prohibitions', 'Legal prohibitions'), ('confidentiality constraints', 'Confidentiality constraints')], max_length=50, verbose_name='reason'),
        ),
    ]
