# Generated by Django 4.2.4 on 2024-10-26 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0013_alter_clienttaskdashboard_location'),
        ('esg_report', '0048_alter_contentindexrequirementomissionreason_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentindexrequirementomissionreason',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.report'),
        ),
        migrations.AlterField(
            model_name='statementofusemodel',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statement_of_uses', to='sustainapp.report'),
        ),
    ]
