# Generated by Django 4.2.4 on 2024-10-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg_report', '0049_alter_contentindexrequirementomissionreason_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentindexrequirementomissionreason',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='explanation'),
        ),
        migrations.AlterField(
            model_name='contentindexrequirementomissionreason',
            name='reason',
            field=models.CharField(blank=True, choices=[('information unavailable/incomplete', 'Information unavailable/incomplete'), ('not applicable', 'Not applicable'), ('legal prohibitions', 'Legal prohibitions'), ('confidentiality constraints', 'Confidentiality constraints')], max_length=50, null=True, verbose_name='reason'),
        ),
        migrations.AlterField(
            model_name='historicalcontentindexrequirementomissionreason',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='explanation'),
        ),
        migrations.AlterField(
            model_name='historicalcontentindexrequirementomissionreason',
            name='reason',
            field=models.CharField(blank=True, choices=[('information unavailable/incomplete', 'Information unavailable/incomplete'), ('not applicable', 'Not applicable'), ('legal prohibitions', 'Legal prohibitions'), ('confidentiality constraints', 'Confidentiality constraints')], max_length=50, null=True, verbose_name='reason'),
        ),
    ]
