# Generated by Django 4.2.4 on 2024-10-28 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esg_report', '0050_alter_contentindexrequirementomissionreason_explanation_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contentindexrequirementomissionreason',
            unique_together=set(),
        ),
    ]
