# Generated by Django 4.2.4 on 2024-10-28 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0013_alter_clienttaskdashboard_location'),
        ('esg_report', '0051_alter_contentindexrequirementomissionreason_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentindexrequirementomissionreason',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.report'),
        ),
        migrations.AlterUniqueTogether(
            name='contentindexrequirementomissionreason',
            unique_together={('report', 'indicator')},
        ),
    ]
