# Generated by Django 4.2.4 on 2024-11-04 11:06

from django.db import migrations, models

# * Create a method that converts TextField into JSONField
import json


from django.db import migrations, models
import json


def convert_textfield_to_jsonfield(apps, schema_editor):
    CeoMessage = apps.get_model("esg_report", "CeoMessage")
    for entry in CeoMessage.objects.all():
        entry.delete()
    HistoricalCeoMessage = apps.get_model("esg_report", "HistoricalCeoMessage")
    for entry in HistoricalCeoMessage.objects.all():
        entry.delete()


class Migration(migrations.Migration):

    dependencies = [
        (
            "esg_report",
            "0052_alter_contentindexrequirementomissionreason_report_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(convert_textfield_to_jsonfield),
        migrations.AlterField(
            model_name="ceomessage",
            name="ceo_name",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ceomessage",
            name="message",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalceomessage",
            name="ceo_name",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalceomessage",
            name="message",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
