# Generated by Django 4.2.4 on 2024-11-08 04:58

from django.db import migrations, models


def remove_data(apps, schema_editor):
    HistoricalStakeholderEngagement = apps.get_model(
        "esg_report", "HistoricalStakeholderEngagement"
    )
    StakeholderEngagement = apps.get_model("esg_report", "StakeholderEngagement")

    # For StakeholderEngagement model
    for record in StakeholderEngagement.objects.all():
        record.delete()

    # For HistoricalStakeholderEngagement model
    for record in HistoricalStakeholderEngagement.objects.all():
        record.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('esg_report', '0055_alter_aboutthecompanyandoperations_about_the_company_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_data),
        migrations.AlterField(
            model_name="historicalstakeholderengagement",
            name="description",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stakeholderengagement",
            name="description",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
