# Generated by Django 4.2.4 on 2024-11-18 11:38

from django.db import migrations, models
import json

def convert_text_to_json(apps, schema_editor):
    models_to_convert = [
        "AboutTheCompanyAndOperations",
        "AboutTheReport",
        "AwardAndRecognition",
        "CEOMessage",
        "MaterialityStatement",
        "MissionVisionValues",
        "ScreenNine",
        "ScreenEleven",
        "ScreenTen",
        "ScreenTwelve",
        "ScreenThirteen",
        "ScreenFourteen",
        "ScreenFifteenModel",
        "SustainabilityRoadmap",
        "HistoricalAboutTheCompanyAndOperations",
        "HistoricalAboutTheReport",
        "HistoricalAwardAndRecognition",
        "HistoricalCEOMessage",
        "HistoricalMaterialityStatement",
        "HistoricalMissionVisionValues",
        "HistoricalScreenNine",
        "HistoricalScreenEleven",
        "HistoricalScreenTen",
        "HistoricalScreenTwelve",
        "HistoricalScreenThirteen",
        "HistoricalScreenFourteen",
        "HistoricalScreenFifteenModel",
        "HistoricalSustainabilityRoadmap",
    ]

    for model_name in models_to_convert:
        Model = apps.get_model("esg_report", model_name)
        for obj in Model.objects.all():
            modified = False
            for field in obj._meta.fields:
                if field.get_internal_type() == "JSONField":
                    value = getattr(obj, field.name)
                    if value is None:
                        continue
                    if not isinstance(value, dict):
                        try:
                            json_value = (
                                json.loads(value)
                                if isinstance(value, str)
                                else {"content": value}
                            )
                            setattr(obj, field.name, json_value)
                            modified = True
                        except (json.JSONDecodeError, TypeError):
                            if value:
                                setattr(obj, field.name, {"content": str(value)})
                                modified = True
                            else:
                                setattr(obj, field.name, {})
                                modified = True
            if modified:
                obj.save()


def reverse_convert(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        (
            "esg_report",
            "0056_alter_historicalstakeholderengagement_description_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(convert_text_to_json, reverse_convert),
        migrations.AlterField(
            model_name="aboutthecompanyandoperations",
            name="about_the_company",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aboutthecompanyandoperations",
            name="business_relations",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aboutthecompanyandoperations",
            name="entities_included",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aboutthecompanyandoperations",
            name="supply_chain_description",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aboutthereport",
            name="description",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aboutthereport",
            name="external_assurance",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aboutthereport",
            name="framework_description",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="awardandrecognition",
            name="description",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ceomessage",
            name="ceo_name",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ceomessage",
            name="message",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalaboutthecompanyandoperations",
            name="about_the_company",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalaboutthecompanyandoperations",
            name="business_relations",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalaboutthecompanyandoperations",
            name="entities_included",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalaboutthecompanyandoperations",
            name="supply_chain_description",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalaboutthereport",
            name="description",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalaboutthereport",
            name="external_assurance",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalaboutthereport",
            name="framework_description",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalawardandrecognition",
            name="description",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalceomessage",
            name="ceo_name",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalceomessage",
            name="message",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalmaterialitystatement",
            name="statement",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalmissionvisionvalues",
            name="mission",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalmissionvisionvalues",
            name="mission_image",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalscreeneleven",
            name="company_economic_performance_statement",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalscreeneleven",
            name="financial_assistance_from_government",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalscreeneleven",
            name="introduction_to_economic_value_creation",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalscreenfifteenmodel",
            name="commitment_statement",
            field=models.JSONField(
                blank=True,
                help_text="Add a statement about the company's commitment to products and services.",
                null=True,
                verbose_name="Company's Commitment to Products and Services",
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreenfifteenmodel",
            name="conclusion",
            field=models.JSONField(
                blank=True,
                help_text="Add a conclusion to the report.",
                null=True,
                verbose_name="Conclusion",
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreenfifteenmodel",
            name="marketing_practices",
            field=models.JSONField(
                blank=True,
                help_text="Add a statement about the company's marketing practices.",
                null=True,
                verbose_name="Company's Marketing Practices",
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreenfifteenmodel",
            name="product_info_labelling",
            field=models.JSONField(
                blank=True,
                help_text="Add a statement about the company's product and service information and labelling.",
                null=True,
                verbose_name="Product and Service Information and Labelling",
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreenfourteen",
            name="community_engagement",
            field=models.JSONField(
                blank=True,
                help_text="Add a statement about the company's community engagement.",
                null=True,
                verbose_name="Community Engagement Statement",
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreenfourteen",
            name="csr_policies",
            field=models.JSONField(
                blank=True,
                help_text="Add a statement about the company's Corporate Social Responsibility policies.",
                null=True,
                verbose_name="Corporate Social Responsibility Policies",
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreenfourteen",
            name="impact_assessment",
            field=models.JSONField(
                blank=True,
                help_text="Add a statement about the company's impact assessment.",
                null=True,
                verbose_name="Impact Assessment",
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreennine",
            name="board_gov_statement",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalscreennine",
            name="policy_not_public_reason",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalscreennine",
            name="remuneration_policies",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalscreennine",
            name="statement",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalscreenten",
            name="approach_for_sustainability",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalscreenten",
            name="approach_to_supply_chain_sustainability",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalscreenten",
            name="company_sustainability_statement",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalscreenten",
            name="sustainability_goals",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalscreenthirteen",
            name="child_labor_position",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's position on child labor",
                null=True,
                verbose_name="Position on Child Labor",
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreenthirteen",
            name="employee_diversity_position",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's position on diversity of employees",
                null=True,
                verbose_name="Position on Employee Diversity",
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreenthirteen",
            name="employee_policies_statement",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's employees and their policies",
                null=True,
                verbose_name="Employee Policies Statement",
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreenthirteen",
            name="employee_skill_upgrade_programs",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's programs for upgrading employee's skills",
                null=True,
                verbose_name="Employee Skill Upgrade Programs",
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreenthirteen",
            name="forced_labor_position",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's position on forced or compulsory labor",
                null=True,
                verbose_name="Position on Forced/Compulsory Labor",
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreenthirteen",
            name="freedom_of_association_views",
            field=models.JSONField(
                blank=True,
                help_text="Statement about the company's views on freedom of association and collective bargaining",
                null=True,
                verbose_name="Views on Freedom of Association and Collective Bargaining",
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreenthirteen",
            name="hazard_risk_assessment",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's process of Hazard and risk assessment",
                null=True,
                verbose_name="Hazard and Risk Assessment Process",
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreenthirteen",
            name="indigenous_rights_policy",
            field=models.JSONField(
                blank=True,
                help_text="Statement about the company's policy on violation of the rights of indigenous people",
                null=True,
                verbose_name="Policy on Violation of Indigenous People's Rights",
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreenthirteen",
            name="ohs_management_system",
            field=models.JSONField(
                blank=True,
                help_text="Statement about the company's Occupational Health and Safety (OHS) management system",
                null=True,
                verbose_name="OHS Management System",
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreenthirteen",
            name="ohs_policies",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's Occupational Health and Safety (OHS) policies",
                null=True,
                verbose_name="Occupational Health and Safety Policies",
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreenthirteen",
            name="parental_leaves",
            field=models.JSONField(
                blank=True,
                help_text="This field stores the answer to a dynamic question provided as input",
                null=True,
                verbose_name="Dynamic Question Answer",
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreenthirteen",
            name="performance_review_process",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's process for performance review of employees",
                null=True,
                verbose_name="Performance Review Process",
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreenthirteen",
            name="remuneration_practices",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's remuneration practices and policies",
                null=True,
                verbose_name="Remuneration Practices and Policies",
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreenthirteen",
            name="safety_training",
            field=models.JSONField(
                blank=True,
                help_text="Statement about the company's safety training programs for employees",
                null=True,
                verbose_name="Safety Training",
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreenthirteen",
            name="security_personnel_external_training",
            field=models.JSONField(
                blank=True,
                help_text="Percentage of security personnel who have received formal training from third-party organisation",
                null=True,
                verbose_name="Percentage of Security Personnel Who Have Received Formal Training from Third-Party Organisation",
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreenthirteen",
            name="security_personnel_internal_training",
            field=models.JSONField(
                blank=True,
                help_text="Percentage of security personnel who have received formal training in the organisation",
                null=True,
                verbose_name="Percentage of Security Personnel Who Have Received Formal Training in the Organisation",
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreenthirteen",
            name="standard_wage",
            field=models.JSONField(
                blank=True,
                help_text="Information about the company's standard wage policies",
                null=True,
                verbose_name="Standard Wage",
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreenthirteen",
            name="violation_discrimination_policy",
            field=models.JSONField(
                blank=True,
                help_text="Statement about the company's policy for addressing violation or discrimination",
                null=True,
                verbose_name="Policy on Addressing Violation/Discrimination",
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreenthirteen",
            name="work_related_health_injuries",
            field=models.JSONField(
                blank=True,
                help_text="Statement about work-related ill health and injuries in the company",
                null=True,
                verbose_name="Work-Related Ill Health and Injuries",
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreenthirteen",
            name="workforce_hire_retention_statement",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's workforce hire and retention strategies",
                null=True,
                verbose_name="Workforce Hire and Retention Statement",
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreentwelve",
            name="air_quality_protection_commitment",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's commitment to protect and maintain air quality",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreentwelve",
            name="biogenic_c02_emissions",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's biogenic CO2 emissions",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreentwelve",
            name="biogenic_c02_emissions_305_3c",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's biogenic CO2 emissions 305 3c",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreentwelve",
            name="emissions",
            field=models.JSONField(
                blank=True,
                help_text="Description of the company's efforts to reduce emissions",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreentwelve",
            name="energy_consumption_outside_organization",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's energy consumption outside of the organization",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreentwelve",
            name="energy_consumption_reduction_commitment",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's commitment to reduce energy consumption",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreentwelve",
            name="energy_consumption_within_organization",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's energy consumption within the organization",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreentwelve",
            name="energy_intensity_tracking",
            field=models.JSONField(
                blank=True,
                help_text="Statement about tracking the Energy Intensity",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreentwelve",
            name="environmental_responsibility_statement",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's responsibility to minimize the environmental impact",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreentwelve",
            name="ghg_emission_intensity_tracking",
            field=models.JSONField(
                blank=True,
                help_text="Statement about tracking of GHG emission intensity",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreentwelve",
            name="ghg_emission_reduction_efforts",
            field=models.JSONField(
                blank=True,
                help_text="Statement about efforts to reduce GHG emissions",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreentwelve",
            name="habitat_protection_restoration_commitment",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's commitment to protect and restore habitats",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreentwelve",
            name="material_management_strategy",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's material management strategy",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreentwelve",
            name="ozone_depleting_substance_elimination",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's commitment to eliminate use of ozone depleting substances",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreentwelve",
            name="reclamation_recycling_process",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's reclamation and recycling process",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreentwelve",
            name="recycling_process",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's process for recycling",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreentwelve",
            name="scope_one_emissions",
            field=models.JSONField(
                blank=True,
                help_text="Add statement about company’s scope 1 emissions",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreentwelve",
            name="scope_three_emissions",
            field=models.JSONField(
                blank=True,
                help_text="Add statement about company’s scope 3 emissions",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreentwelve",
            name="scope_two_emissions",
            field=models.JSONField(
                blank=True,
                help_text="Add statement about company’s scope 2 emissions",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreentwelve",
            name="significant_spills",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's significant spills",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreentwelve",
            name="water_consumption_goals",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's water consumption goals",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalscreentwelve",
            name="water_withdrawal_tracking",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's tracking of water withdrawal",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalsustainabilityroadmap",
            name="description",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalsustainabilityroadmap",
            name="file",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="materialitystatement",
            name="statement",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="missionvisionvalues",
            name="mission",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="missionvisionvalues",
            name="mission_image",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="screeneleven",
            name="company_economic_performance_statement",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="screeneleven",
            name="financial_assistance_from_government",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="screeneleven",
            name="introduction_to_economic_value_creation",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="screenfifteenmodel",
            name="commitment_statement",
            field=models.JSONField(
                blank=True,
                help_text="Add a statement about the company's commitment to products and services.",
                null=True,
                verbose_name="Company's Commitment to Products and Services",
            ),
        ),
        migrations.AlterField(
            model_name="screenfifteenmodel",
            name="conclusion",
            field=models.JSONField(
                blank=True,
                help_text="Add a conclusion to the report.",
                null=True,
                verbose_name="Conclusion",
            ),
        ),
        migrations.AlterField(
            model_name="screenfifteenmodel",
            name="marketing_practices",
            field=models.JSONField(
                blank=True,
                help_text="Add a statement about the company's marketing practices.",
                null=True,
                verbose_name="Company's Marketing Practices",
            ),
        ),
        migrations.AlterField(
            model_name="screenfifteenmodel",
            name="product_info_labelling",
            field=models.JSONField(
                blank=True,
                help_text="Add a statement about the company's product and service information and labelling.",
                null=True,
                verbose_name="Product and Service Information and Labelling",
            ),
        ),
        migrations.AlterField(
            model_name="screenfourteen",
            name="community_engagement",
            field=models.JSONField(
                blank=True,
                help_text="Add a statement about the company's community engagement.",
                null=True,
                verbose_name="Community Engagement Statement",
            ),
        ),
        migrations.AlterField(
            model_name="screenfourteen",
            name="csr_policies",
            field=models.JSONField(
                blank=True,
                help_text="Add a statement about the company's Corporate Social Responsibility policies.",
                null=True,
                verbose_name="Corporate Social Responsibility Policies",
            ),
        ),
        migrations.AlterField(
            model_name="screenfourteen",
            name="impact_assessment",
            field=models.JSONField(
                blank=True,
                help_text="Add a statement about the company's impact assessment.",
                null=True,
                verbose_name="Impact Assessment",
            ),
        ),
        migrations.AlterField(
            model_name="screennine",
            name="board_gov_statement",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="screennine",
            name="policy_not_public_reason",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="screennine",
            name="remuneration_policies",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="screennine",
            name="statement",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="screenten",
            name="approach_for_sustainability",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="screenten",
            name="approach_to_supply_chain_sustainability",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="screenten",
            name="company_sustainability_statement",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="screenten",
            name="sustainability_goals",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="screenthirteen",
            name="child_labor_position",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's position on child labor",
                null=True,
                verbose_name="Position on Child Labor",
            ),
        ),
        migrations.AlterField(
            model_name="screenthirteen",
            name="employee_diversity_position",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's position on diversity of employees",
                null=True,
                verbose_name="Position on Employee Diversity",
            ),
        ),
        migrations.AlterField(
            model_name="screenthirteen",
            name="employee_policies_statement",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's employees and their policies",
                null=True,
                verbose_name="Employee Policies Statement",
            ),
        ),
        migrations.AlterField(
            model_name="screenthirteen",
            name="employee_skill_upgrade_programs",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's programs for upgrading employee's skills",
                null=True,
                verbose_name="Employee Skill Upgrade Programs",
            ),
        ),
        migrations.AlterField(
            model_name="screenthirteen",
            name="forced_labor_position",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's position on forced or compulsory labor",
                null=True,
                verbose_name="Position on Forced/Compulsory Labor",
            ),
        ),
        migrations.AlterField(
            model_name="screenthirteen",
            name="freedom_of_association_views",
            field=models.JSONField(
                blank=True,
                help_text="Statement about the company's views on freedom of association and collective bargaining",
                null=True,
                verbose_name="Views on Freedom of Association and Collective Bargaining",
            ),
        ),
        migrations.AlterField(
            model_name="screenthirteen",
            name="hazard_risk_assessment",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's process of Hazard and risk assessment",
                null=True,
                verbose_name="Hazard and Risk Assessment Process",
            ),
        ),
        migrations.AlterField(
            model_name="screenthirteen",
            name="indigenous_rights_policy",
            field=models.JSONField(
                blank=True,
                help_text="Statement about the company's policy on violation of the rights of indigenous people",
                null=True,
                verbose_name="Policy on Violation of Indigenous People's Rights",
            ),
        ),
        migrations.AlterField(
            model_name="screenthirteen",
            name="ohs_management_system",
            field=models.JSONField(
                blank=True,
                help_text="Statement about the company's Occupational Health and Safety (OHS) management system",
                null=True,
                verbose_name="OHS Management System",
            ),
        ),
        migrations.AlterField(
            model_name="screenthirteen",
            name="ohs_policies",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's Occupational Health and Safety (OHS) policies",
                null=True,
                verbose_name="Occupational Health and Safety Policies",
            ),
        ),
        migrations.AlterField(
            model_name="screenthirteen",
            name="parental_leaves",
            field=models.JSONField(
                blank=True,
                help_text="This field stores the answer to a dynamic question provided as input",
                null=True,
                verbose_name="Dynamic Question Answer",
            ),
        ),
        migrations.AlterField(
            model_name="screenthirteen",
            name="performance_review_process",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's process for performance review of employees",
                null=True,
                verbose_name="Performance Review Process",
            ),
        ),
        migrations.AlterField(
            model_name="screenthirteen",
            name="remuneration_practices",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's remuneration practices and policies",
                null=True,
                verbose_name="Remuneration Practices and Policies",
            ),
        ),
        migrations.AlterField(
            model_name="screenthirteen",
            name="safety_training",
            field=models.JSONField(
                blank=True,
                help_text="Statement about the company's safety training programs for employees",
                null=True,
                verbose_name="Safety Training",
            ),
        ),
        migrations.AlterField(
            model_name="screenthirteen",
            name="security_personnel_external_training",
            field=models.JSONField(
                blank=True,
                help_text="Percentage of security personnel who have received formal training from third-party organisation",
                null=True,
                verbose_name="Percentage of Security Personnel Who Have Received Formal Training from Third-Party Organisation",
            ),
        ),
        migrations.AlterField(
            model_name="screenthirteen",
            name="security_personnel_internal_training",
            field=models.JSONField(
                blank=True,
                help_text="Percentage of security personnel who have received formal training in the organisation",
                null=True,
                verbose_name="Percentage of Security Personnel Who Have Received Formal Training in the Organisation",
            ),
        ),
        migrations.AlterField(
            model_name="screenthirteen",
            name="standard_wage",
            field=models.JSONField(
                blank=True,
                help_text="Information about the company's standard wage policies",
                null=True,
                verbose_name="Standard Wage",
            ),
        ),
        migrations.AlterField(
            model_name="screenthirteen",
            name="violation_discrimination_policy",
            field=models.JSONField(
                blank=True,
                help_text="Statement about the company's policy for addressing violation or discrimination",
                null=True,
                verbose_name="Policy on Addressing Violation/Discrimination",
            ),
        ),
        migrations.AlterField(
            model_name="screenthirteen",
            name="work_related_health_injuries",
            field=models.JSONField(
                blank=True,
                help_text="Statement about work-related ill health and injuries in the company",
                null=True,
                verbose_name="Work-Related Ill Health and Injuries",
            ),
        ),
        migrations.AlterField(
            model_name="screenthirteen",
            name="workforce_hire_retention_statement",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's workforce hire and retention strategies",
                null=True,
                verbose_name="Workforce Hire and Retention Statement",
            ),
        ),
        migrations.AlterField(
            model_name="screentwelve",
            name="air_quality_protection_commitment",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's commitment to protect and maintain air quality",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="screentwelve",
            name="biogenic_c02_emissions",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's biogenic CO2 emissions",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="screentwelve",
            name="biogenic_c02_emissions_305_3c",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's biogenic CO2 emissions 305 3c",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="screentwelve",
            name="emissions",
            field=models.JSONField(
                blank=True,
                help_text="Description of the company's efforts to reduce emissions",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="screentwelve",
            name="energy_consumption_outside_organization",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's energy consumption outside of the organization",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="screentwelve",
            name="energy_consumption_reduction_commitment",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's commitment to reduce energy consumption",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="screentwelve",
            name="energy_consumption_within_organization",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's energy consumption within the organization",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="screentwelve",
            name="energy_intensity_tracking",
            field=models.JSONField(
                blank=True,
                help_text="Statement about tracking the Energy Intensity",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="screentwelve",
            name="environmental_responsibility_statement",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's responsibility to minimize the environmental impact",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="screentwelve",
            name="ghg_emission_intensity_tracking",
            field=models.JSONField(
                blank=True,
                help_text="Statement about tracking of GHG emission intensity",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="screentwelve",
            name="ghg_emission_reduction_efforts",
            field=models.JSONField(
                blank=True,
                help_text="Statement about efforts to reduce GHG emissions",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="screentwelve",
            name="habitat_protection_restoration_commitment",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's commitment to protect and restore habitats",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="screentwelve",
            name="material_management_strategy",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's material management strategy",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="screentwelve",
            name="ozone_depleting_substance_elimination",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's commitment to eliminate use of ozone depleting substances",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="screentwelve",
            name="reclamation_recycling_process",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's reclamation and recycling process",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="screentwelve",
            name="recycling_process",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's process for recycling",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="screentwelve",
            name="scope_one_emissions",
            field=models.JSONField(
                blank=True,
                help_text="Add statement about company’s scope 1 emissions",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="screentwelve",
            name="scope_three_emissions",
            field=models.JSONField(
                blank=True,
                help_text="Add statement about company’s scope 3 emissions",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="screentwelve",
            name="scope_two_emissions",
            field=models.JSONField(
                blank=True,
                help_text="Add statement about company’s scope 2 emissions",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="screentwelve",
            name="significant_spills",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's significant spills",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="screentwelve",
            name="water_consumption_goals",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's water consumption goals",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="screentwelve",
            name="water_withdrawal_tracking",
            field=models.JSONField(
                blank=True,
                help_text="Statement about company's tracking of water withdrawal",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sustainabilityroadmap",
            name="description",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sustainabilityroadmap",
            name="file",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
