# Generated by Django 4.2.4 on 2025-01-08 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiality_dashboard', '0003_alter_materialtopic_esg_category'),
        ('sustainapp', '0007_alter_clienttaskdashboard_assigned_to'),
        ('esg_report', '0057_alter_aboutthecompanyandoperations_about_the_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('materiality_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiality_dashboard.materialityassessment')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.report')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
