# Generated by Django 4.2.4 on 2025-03-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg_report', '0058_reportassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalscreentwelve',
            name='base_year',
            field=models.JSONField(blank=True, help_text="Statement about company's base year", null=True),
        ),
        migrations.AddField(
            model_name='historicalscreentwelve',
            name='consolidation',
            field=models.JSONField(blank=True, help_text="Statement about company's consolidation", null=True),
        ),
        migrations.AddField(
            model_name='screentwelve',
            name='base_year',
            field=models.JSONField(blank=True, help_text="Statement about company's base year", null=True),
        ),
        migrations.AddField(
            model_name='screentwelve',
            name='consolidation',
            field=models.JSONField(blank=True, help_text="Statement about company's consolidation", null=True),
        ),
    ]
