# Generated by Django 4.2.4 on 2025-03-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg_report', '0059_historicalscreentwelve_base_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalscreeneleven',
            name='infrastructure_investement',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screeneleven',
            name='infrastructure_investement',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
