# Generated by Django 4.2.4 on 2025-05-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg_report', '0060_historicalscreeneleven_infrastructure_investement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalscreenfifteenmodel',
            name='customers',
            field=models.JSONField(blank=True, help_text='Add statement about customers', null=True, verbose_name='Customers'),
        ),
        migrations.AddField(
            model_name='historicalscreenfourteen',
            name='violation_rights',
            field=models.JSONField(blank=True, help_text='Add statement about company’s policy on violation of rights of indigenous people', null=True, verbose_name='Incidents of Violation of Rights of Indigenous People'),
        ),
        migrations.AddField(
            model_name='screenfifteenmodel',
            name='customers',
            field=models.JSONField(blank=True, help_text='Add statement about customers', null=True, verbose_name='Customers'),
        ),
        migrations.AddField(
            model_name='screenfourteen',
            name='violation_rights',
            field=models.JSONField(blank=True, help_text='Add statement about company’s policy on violation of rights of indigenous people', null=True, verbose_name='Incidents of Violation of Rights of Indigenous People'),
        ),
    ]
