# Generated by Django 4.2.4 on 2025-05-15 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esg_report', '0061_historicalscreenfifteenmodel_customers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalscreentwelve',
            name='energy_intensity_tracking',
        ),
        migrations.RemoveField(
            model_name='screentwelve',
            name='energy_intensity_tracking',
        ),
    ]
