# Generated by Django 4.2.4 on 2025-06-11 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustainapp', '0024_clienttaskdashboard_act_id_and_more'),
        ('esg_report', '0062_remove_historicalscreentwelve_energy_intensity_tracking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsgCustomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.JSONField(default=dict)),
                ('sub_section', models.JSONField(default=dict)),
                ('include_management_material_topics', models.BooleanField(default=False)),
                ('include_content_index', models.BooleanField(default=False)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.report')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
