# Generated by Django 4.2.4 on 2025-03-27 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sustainapp', '0021_rename_country_corporateentity_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenerio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('base_year', models.IntegerField()),
                ('target_year', models.IntegerField()),
                ('corporate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sustainapp.corporateentity')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_scenerio', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainapp.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_scenerio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fte', models.BooleanField(default=False)),
                ('fte_data', models.JSONField(blank=True, default=dict, null=True)),
                ('area', models.BooleanField(default=False)),
                ('area_data', models.JSONField(blank=True, default=dict, null=True)),
                ('revenue', models.BooleanField(default=False)),
                ('revenue_data', models.JSONField(blank=True, default=dict, null=True)),
                ('production_volume', models.BooleanField(default=False)),
                ('production_volume_data', models.JSONField(blank=True, default=dict, null=True)),
                ('scenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_metrics', to='optimize.scenerio')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
