# Generated by Django 4.2.4 on 2025-04-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimize', '0002_historicalscenerio_historicalbusinessmetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalscenerio',
            name='scenario_by',
            field=models.CharField(choices=[('corporate', 'corporate'), ('organization', 'organization')], default='organization', max_length=255),
        ),
        migrations.AddField(
            model_name='scenerio',
            name='scenario_by',
            field=models.CharField(choices=[('corporate', 'corporate'), ('organization', 'organization')], default='organization', max_length=255),
        ),
    ]
