# Generated by Django 4.2.4 on 2025-04-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimize', '0003_historicalscenerio_scenario_by_scenerio_scenario_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmetric',
            name='area_weightage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businessmetric',
            name='fte_weightage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businessmetric',
            name='production_volume_weightage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businessmetric',
            name='revenue_weightage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalbusinessmetric',
            name='area_weightage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalbusinessmetric',
            name='fte_weightage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalbusinessmetric',
            name='production_volume_weightage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalbusinessmetric',
            name='revenue_weightage',
            field=models.IntegerField(default=0),
        ),
    ]
