# Generated by Django 4.2.4 on 2025-04-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimize', '0004_businessmetric_area_weightage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmetric',
            name='area_weightage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='businessmetric',
            name='fte_weightage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='businessmetric',
            name='production_volume_weightage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='businessmetric',
            name='revenue_weightage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalbusinessmetric',
            name='area_weightage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalbusinessmetric',
            name='fte_weightage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalbusinessmetric',
            name='production_volume_weightage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalbusinessmetric',
            name='revenue_weightage',
            field=models.FloatField(default=0),
        ),
    ]
