# Generated by Django 4.2.4 on 2025-04-14 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('optimize', '0005_alter_businessmetric_area_weightage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('sub_category', models.CharField(max_length=255)),
                ('activity_name', models.CharField(max_length=255)),
                ('activity_id', models.CharField(max_length=255)),
                ('factor_id', models.CharField(max_length=255)),
                ('activity_change', models.BooleanField(default=False)),
                ('percentage_change', models.JSONField(blank=True, default=dict, null=True)),
                ('changes_in_activity', models.JSONField(blank=True, default=dict, null=True)),
                ('calculated_results', models.JSONField(blank=True, default=dict, null=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimize.scenerio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalSelectedActivity',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('scope', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('sub_category', models.CharField(max_length=255)),
                ('activity_name', models.CharField(max_length=255)),
                ('activity_id', models.CharField(max_length=255)),
                ('factor_id', models.CharField(max_length=255)),
                ('activity_change', models.BooleanField(default=False)),
                ('percentage_change', models.JSONField(blank=True, default=dict, null=True)),
                ('changes_in_activity', models.JSONField(blank=True, default=dict, null=True)),
                ('calculated_results', models.JSONField(blank=True, default=dict, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='optimize.scenerio')),
            ],
            options={
                'verbose_name': 'historical selected activity',
                'verbose_name_plural': 'historical selected activitys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
