# Generated by Django 4.2.4 on 2025-04-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimize', '0006_selectedactivity_historicalselectedactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalselectedactivity',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalselectedactivity',
            name='quantity2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalselectedactivity',
            name='unit',
            field=models.CharField(default='kg', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalselectedactivity',
            name='unit2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='selectedactivity',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selectedactivity',
            name='quantity2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='selectedactivity',
            name='unit',
            field=models.CharField(default='kg', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selectedactivity',
            name='unit2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
