# Generated by Django 4.2.4 on 2025-04-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimize', '0007_historicalselectedactivity_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalselectedactivity',
            name='unit_type',
            field=models.CharField(default='energy', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selectedactivity',
            name='unit_type',
            field=models.CharField(default='energy', max_length=255),
            preserve_default=False,
        ),
    ]
