# Generated by Django 4.2.4 on 2025-04-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimize', '0009_historicalselectedactivity_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalselectedactivity',
            name='co2e_total',
            field=models.DecimalField(decimal_places=4, default=1000, max_digits=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selectedactivity',
            name='co2e_total',
            field=models.DecimalField(decimal_places=4, default=1000, max_digits=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalselectedactivity',
            name='quantity2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='selectedactivity',
            name='quantity2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=32, null=True),
        ),
    ]
