# Generated by Django 4.2.4 on 2025-04-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimize', '0010_historicalselectedactivity_co2e_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalselectedactivity',
            name='region',
            field=models.CharField(default='US', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selectedactivity',
            name='region',
            field=models.CharField(default='US', max_length=255),
            preserve_default=False,
        ),
    ]
