# Generated by Django 4.2.4 on 2025-05-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimize', '0013_historicalcalculatedresult_calculatedresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatedresult',
            name='category',
            field=models.CharField(default='default-cat', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculatedresult',
            name='scope',
            field=models.CharField(default='scope1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculatedresult',
            name='sub_category',
            field=models.CharField(default='default-sub_cat', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcalculatedresult',
            name='category',
            field=models.CharField(default='default-cat', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcalculatedresult',
            name='scope',
            field=models.CharField(default='scope1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcalculatedresult',
            name='sub_category',
            field=models.CharField(default='default-sub_cat', max_length=100),
            preserve_default=False,
        ),
    ]
