# Generated by Django 4.2.4 on 2025-05-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimize', '0014_calculatedresult_category_calculatedresult_scope_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalselectedactivity',
            name='quantity',
            field=models.DecimalField(decimal_places=8, max_digits=64),
        ),
        migrations.AlterField(
            model_name='historicalselectedactivity',
            name='quantity2',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=64, null=True),
        ),
        migrations.AlterField(
            model_name='selectedactivity',
            name='quantity',
            field=models.DecimalField(decimal_places=8, max_digits=64),
        ),
        migrations.AlterField(
            model_name='selectedactivity',
            name='quantity2',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=64, null=True),
        ),
    ]
