# Generated by Django 4.2.4 on 2025-05-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimize', '0015_alter_historicalselectedactivity_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalselectedactivity',
            name='co2e_total',
            field=models.DecimalField(decimal_places=8, max_digits=64),
        ),
        migrations.AlterField(
            model_name='selectedactivity',
            name='co2e_total',
            field=models.DecimalField(decimal_places=8, max_digits=64),
        ),
    ]
