# Generated by Django 4.2.4 on 2025-05-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimize', '0016_alter_historicalselectedactivity_co2e_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatedresult',
            name='uuid',
            field=models.CharField(default='somekey', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcalculatedresult',
            name='uuid',
            field=models.CharField(default='somekey', max_length=255),
            preserve_default=False,
        ),
    ]
