name: Create Asana Task on Pull Request

on:
  pull_request:
    types: [opened]
    branches:
      - dev

jobs:
  create_asana_task:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Asana Task
      env:
        ASANA_TOKEN: "2/1206370253774697/1207905742780138:8d2035b60ee02493ca800700970a18f6"
        ASANA_WORKSPACE_ID: "1203486548572199"
        ASANA_PROJECT_ID: "1207703004239689"
      run: |
        pr_title=$(echo "${{ github.event.pull_request.title }}" | jq -Rr @uri)
        pr_url="${{ github.event.pull_request.html_url }}"
        pr_body=$(echo "${{ github.event.pull_request.body }}" | jq -Rr @uri)
        user_name="${{ github.event.pull_request.user.login }}"
        user_email=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/users/${{ github.event.pull_request.user.login }} | jq -r .email)
        
        curl -X POST https://app.asana.com/api/1.0/tasks \
          -H "Authorization: Bearer $ASANA_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{
                \"data\": {
                  \"workspace\": \"$ASANA_WORKSPACE_ID\",
                  \"projects\": [\"$ASANA_PROJECT_ID\"],
                  \"name\": \"$pr_title\",
                  \"notes\": \"Pull Request URL: $pr_url\n\n$pr_body\"
                }
              }"
