name: Manage Asana Task on Pull Request Events

on:
  pull_request:
    types: [opened, closed]
    branches:
      - dev

jobs:
  create_asana_task:
    if: ${{ github.event.action == 'opened' && github.base_ref == 'dev' && github.head_ref != 'dev' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Asana Task
      run: |
        pr_title="${{ github.event.pull_request.title }}"
        pr_url="${{ github.event.pull_request.html_url }}"
        pr_body="${{ github.event.pull_request.body }}"
        asana_task_id=$(curl -X POST https://app.asana.com/api/1.0/tasks \
          -H "Authorization: Bearer 2/1206370253774697/1207905742780138:8d2035b60ee02493ca800700970a18f6" \
          -H "Content-Type: application/json" \
          -d "{
                \"data\": {
                  \"workspace\": \"1203486548572199\",
                  \"projects\": [\"1207906053156776\"],
                  \"name\": \"$pr_title\",
                  \"notes\": \"Pull Request URL: $pr_url\n\n$pr_body\",
                  \"custom_fields\": {
                    \"1205222382328468\": \"1205222382328471\"
                  }
                }
              }" | jq -r .data.gid)
        echo "Asana Task ID: $asana_task_id"
        echo "asana_task_id=$asana_task_id" >> $GITHUB_ENV
        echo $asana_task_id > asana_task_id.txt
    - name: Check Asana Task ID File
      run: cat asana_task_id.txt

    - name: List Directory Before Uploading Artifact
      run: ls -alh

    - name: Persist Asana Task ID
      uses: actions/upload-artifact@v2
      with:
        name: asana_task_id
        path: asana_task_id.txt

  update_asana_task:
    needs: create_asana_task 
    if: ${{ github.event.action == 'closed' && github.base_ref == 'dev' && github.head_ref != 'dev' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Delay for artifact availability
      run: sleep 10

    - name: List Directory Before Downloading Artifact
      run: ls -alh

    - name: Retrieve Asana Task ID
      uses: actions/download-artifact@v4
      with:
        name: asana_task_id
        path: artifact_asana

    - name: List Artifact Directory
      run: ls -alh artifact_asana

    - name: Read Asana Task ID
      run: |
        asana_task_id=$(cat artifact_asana/asana_task_id.txt)
        echo "Retrieved Asana Task ID: $asana_task_id"
        echo "asana_task_id=$asana_task_id" >> $GITHUB_ENV
    - name: Update Asana Task
      run: |
        if [ "${{ github.event.pull_request.merged }}" == "true" ]; then
          status="Pull Request has been merged."
          status_field="1205222382328469"
        else
          status="Pull Request has been closed."
          status_field="1205222382328469"
        fi
        curl -X PUT https://app.asana.com/api/1.0/tasks/${{ env.asana_task_id }} \
          -H "Authorization: Bearer 2/1206370253774697/1207905742780138:8d2035b60ee02493ca800700970a18f6" \
          -H "Content-Type: application/json" \
          -d "{
                \"data\": {
                  \"notes\": \"$status\",
                  \"custom_fields\": {
                    \"1205222382328468\": \"$status_field\"
                  }
                }
              }"
