name: Create Asana Tasks

on:
  pull_request:
    types: [opened]
    branches:
      - dev
  workflow_dispatch:

jobs:
  create_asana_task:
    if: ${{ github.event.action == 'opened' && github.base_ref == 'dev' && github.head_ref != 'dev' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create Asana Task
      run: |
        pr_title="${{ github.event.pull_request.title }}"
        pr_url="${{ github.event.pull_request.html_url }}"
        pr_body="${{ github.event.pull_request.body }}"
        due_date=$(TZ=Asia/Kolkata date +"%Y-%m-%d")
        
        asana_task_id=$(curl -X POST https://app.asana.com/api/1.0/tasks \
          -H "Authorization: Bearer ${{ secrets.ASANA_ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d "{
                \"data\": {
                  \"workspace\": \"${{ secrets.ASANA_WORKSPACE_ID }}\",
                  \"projects\": [\"${{ secrets.ASANA_PROJECT_ID }}\"],
                  \"name\": \"$pr_title\",
                  \"notes\": \"Pull Request URL: $pr_url\n\n$pr_body\",
                  \"due_on\": \"$due_date\",
                  \"assignee\": \"${{ secrets.ASANA_ASSIGNEE_ID }}\",
                  \"memberships\": [{
                    \"project\": \"${{ secrets.ASANA_PROJECT_ID }}\",
                    \"section\": \"${{ secrets.ASANA_SECTION_ID }}\"
                  }],
                  \"custom_fields\": {
                    \"${{ secrets.ASANA_CUSTOM_FIELD_ID }}\": \"1205222382328471\"
                  }
                }
              }" | jq -r .data.gid)
        
        echo "Asana Task ID: $asana_task_id"
        echo "asana_task_id=$asana_task_id" >> $GITHUB_ENV
        echo $asana_task_id > asana_task_id.txt

    - name: Check Asana Task ID File
      run: cat asana_task_id.txt

    - name: List Directory Before Uploading Artifact
      run: ls -alh

    - name: Persist Asana Task ID
      uses: actions/upload-artifact@v4
      with:
        name: asana_task_id
        path: asana_task_id.txt

    - name: Update PR Description with Asana Task Link
      run: |
        asana_task_id=$(cat asana_task_id.txt)
        asana_task_url="https://app.asana.com/0/${{ secrets.ASANA_PROJECT_ID }}/$asana_task_id"
        pr_number=${{ github.event.pull_request.number }}
        pr_body="${{ github.event.pull_request.body }}"
        updated_pr_body="$pr_body\n\nAsana Task: $asana_task_url"
        
        curl -X PATCH \
          -H "Authorization: Bearer ${{ github.token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number \
          -d "{\"body\": \"$updated_pr_body\"}"
          
    - name: Attach pull request to Asana task
      uses: Asana/create-app-attachment-github-action@v1.3
      id: postAttachment
      with:
        asana-secret: "OA7YVTJJH7ZW3OTGBPHBESNAJREDYHUWJT5BZGPSQSLV3VCG2JQSYTXZ"
        allowed-projects: |
          ${{ secrets.ASANA_PROJECT_ID }}
    - name: Log output status
      run: echo "Status is ${{ steps.postAttachment.outputs.status }}"
