name: Create Asana Tasks

on:
  pull_request:
    types: [opened]
    branches:
      - dev
  workflow_dispatch:

jobs:
  create_asana_task:
    if: ${{ github.event.action == 'opened' && github.base_ref == 'dev' && github.head_ref != 'dev' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Determine Asana Token
      id: determine_asana_token
      run: |
        creator="${{ github.event.pull_request.user.login }}"
        asana_token_variable="ASANA_ACCESS_${creator^^}"

        echo "Checking for secret: $asana_token_variable"

        if [[ $asana_token_variable == "ASANA_ACCESS_UTSAVSUSTAINX" ]]; then
          asana_token="${{ secrets.ASANA_ACCESS_UTSAVSUSTAINX }}"
        elif [[ $asana_token_variable == "ASANA_ACCESS_YASHWANTH39" ]]; then
          asana_token="${{ secrets.ASANA_ACCESS_YASHWANTH39 }}"
        elif [[ $asana_token_variable == "ASANA_ACCESS_JAIRAJSUSTAINED" ]]; then
          asana_token="${{ secrets.ASANA_ACCESS_JAIRAJSUSTAINED }}"
        else
          asana_token="${{ secrets.ASANA_ACCESS_TOKEN }}"
        fi
        
        echo "asana_token=$asana_token" >> $GITHUB_ENV

    - name: Get Pull Request Reviewer Login
      id: get_reviewer_login
      run: |
        reviewers=$(curl -H "Authorization: token ${{ github.token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers)
        
        reviewer_login=$(echo $reviewers | jq -r '.users[0].login')
        
        echo "Reviewer login: $reviewer_login"
        
        if [ -z "$reviewer_login" ]; then
          reviewer_login="${{ github.event.pull_request.user.login }}"
        fi

        echo "reviewer_login=$reviewer_login" >> $GITHUB_ENV
  
    - name: Determine Reviewer Asana Token
      id: determine_reviewer_asana_token
      run: |
        reviewer_login="${{ env.reviewer_login }}"
        asana_token_variable="ASANA_ACCESS_${reviewer_login^^}"

        echo "Checking for secret: $asana_token_variable"

        if [[ $asana_token_variable == "ASANA_ACCESS_UTSAVSUSTAINX" ]]; then
          reviewer_asana_token="${{ secrets.ASANA_ACCESS_UTSAVSUSTAINX }}"
        elif [[ $asana_token_variable == "ASANA_ACCESS_YASHWANTH39" ]]; then
          reviewer_asana_token="${{ secrets.ASANA_ACCESS_YASHWANTH39 }}"
        elif [[ $asana_token_variable == "ASANA_ACCESS_JAIRAJSUSTAINED" ]]; then
          reviewer_asana_token="${{ secrets.ASANA_ACCESS_JAIRAJSUSTAINED }}"
        else
          reviewer_asana_token="${{ secrets.ASANA_ACCESS_TOKEN }}"
        fi
        
        echo "reviewer_asana_token=$reviewer_asana_token" >> $GITHUB_ENV

    - name: Get Reviewer Asana User Details
      id: get_reviewer_asana_user_details
      run: |
        user_details=$(curl -H "Authorization: Bearer $reviewer_asana_token" \
                              -H "Content-Type: application/json" \
                              https://app.asana.com/api/1.0/users/me)
        
        reviewer_id=$(echo $user_details | jq -r '.data.gid')
        reviewer_email=$(echo $user_details | jq -r '.data.email')

        if [ -z "$reviewer_id" ] || [ -z "$reviewer_email" ]; then
          reviewer_id="${{ secrets.ASANA_ASSIGNEE_ID }}"
        fi
        
        echo "reviewer_id=$reviewer_id" >> $GITHUB_ENV
        echo "reviewer_email=$reviewer_email" >> $GITHUB_ENV

        echo "Reviewer Asana User ID: $reviewer_id"
        echo "Reviewer Asana User Email: $reviewer_email"

    - name: Create Asana Task
      run: |
        pr_title="${{ github.event.pull_request.title }}"
        pr_url="${{ github.event.pull_request.html_url }}"
        pr_body="${{ github.event.pull_request.body }}"
        due_date=$(TZ=Asia/Kolkata date +"%Y-%m-%d")
        
        asana_task_id=$(curl -X POST https://app.asana.com/api/1.0/tasks \
          -H "Authorization: Bearer $asana_token" \
          -H "Content-Type: application/json" \
          -d "{
                \"data\": {
                  \"workspace\": \"${{ secrets.ASANA_WORKSPACE_ID }}\",
                  \"projects\": [\"${{ secrets.ASANA_PROJECT_ID }}\"],
                  \"name\": \"$pr_title\",
                  \"notes\": \"Pull Request URL: $pr_url\n\n$pr_body\",
                  \"due_on\": \"$due_date\",
                  \"assignee\": \"$reviewer_id\",
                  \"memberships\": [{
                    \"project\": \"${{ secrets.ASANA_PROJECT_ID }}\",
                    \"section\": \"${{ secrets.ASANA_SECTION_ID }}\"
                  }],
                  \"custom_fields\": {
                    \"${{ secrets.ASANA_CUSTOM_FIELD_ID }}\": \"1205222382328471\"
                  }
                }
              }" | jq -r .data.gid)
        
        echo "Asana Task ID: $asana_task_id"
        echo "asana_task_id=$asana_task_id" >> $GITHUB_ENV
        echo $asana_task_id > asana_task_id.txt

    - name: Check Asana Task ID File
      run: cat asana_task_id.txt

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: asana_task_id
        path: asana_task_id.txt
