name: Update Asana Task

on:
  pull_request:
    types: [closed]
    branches:
      - dev
  workflow_dispatch:

jobs:
  update_asana_task:
    if: ${{ github.event.action == 'closed' && github.base_ref == 'dev' && github.head_ref != 'dev' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get latest matching run-id of create_asana_task
      id: get_run_id
      run: |
        echo "Checking for latest matching run ID"
        head_ref="${{ github.event.pull_request.head.ref }}"
        response=$(curl -s -H "Authorization: token ${{ github.token }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/create_asana_task.yml/runs?status=success")
        echo "API Response: $response"
        matching_run_id=$(echo $response | jq -r --arg head_ref "$head_ref" '
          .workflow_runs | map(select(.head_branch == $head_ref)) | 
          sort_by(.created_at) | reverse | .[0].id') # Sorting by created at date
        echo "Matching run-id: $matching_run_id"
        if [ -z "$matching_run_id" ]; then
          echo "No matching run ID found"
          exit 1
        fi
        echo "run_id=$matching_run_id" >> $GITHUB_ENV

    - name: List Directory Before Downloading Artifact
      run: ls -alh

    - name: Retrieve Asana Details
      uses: actions/download-artifact@v4
      with:
        name: asana_details
        path: artifact_asana
        github-token: ${{ github.token }}
        repository: ${{ github.repository }}
        run-id: ${{ env.run_id }}

    - name: List Artifact Directory
      run: ls -alh artifact_asana

    - name: Read Asana Details
      run: |
        reviewer_asana_token=$(cat artifact_asana/reviewer_asana_token.txt)
        asana_task_id=$(cat artifact_asana/asana_task_id.txt)
        echo "Retrieved Reviewer's Asana Token: $reviewer_asana_token"
        echo "Retrieved Asana Task ID: $asana_task_id"
        echo "reviewer_asana_token=$reviewer_asana_token" >> $GITHUB_ENV
        echo "asana_task_id=$asana_task_id" >> $GITHUB_ENV

    - name: Update Asana Task
      run: |
        pr_url="${{ github.event.pull_request.html_url }}"
        pr_closed_at="${{ github.event.pull_request.closed_at }}"
        pr_merged_at="${{ github.event.pull_request.merged_at }}"

        if [ "${{ github.event.pull_request.merged }}" == "true" ]; then
          status="Pull Request has been merged on $pr_merged_at. PR URL: $pr_url"
          status_field="1205222382328469"
        else
          status="Pull Request has been closed on $pr_closed_at. PR URL: $pr_url"
          status_field="1205222382328469"
        fi
        curl -X PUT https://app.asana.com/api/1.0/tasks/${{ env.asana_task_id }} \
          -H "Authorization: Bearer ${{ env.reviewer_asana_token }}" \
          -H "Content-Type: application/json" \
          -d "{
                \"data\": {
                  \"notes\": \"$status\",
                  \"custom_fields\": {
                    \"${{ secrets.ASANA_CUSTOM_FIELD_ID }}\": \"$status_field\"
                  },
                  \"completed\": true
                }
              }"
