name: Update Asana Task on Pull Request Closed

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  update_asana_task:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Delay for artifact availability
      run: sleep 10

    - name: List Directory Before Downloading Artifact
      run: ls -alh

    - name: Retrieve Asana Task ID
      uses: actions/download-artifact@v2
      with:
        name: asana_task_id

    - name: List Artifact Directory
      run: |
        echo "Checking the contents of the artifact directory"
        ls -alh

    - name: Read Asana Task ID
      run: |
        asana_task_id=$(cat asana_task_id.txt)
        echo "Retrieved Asana Task ID: $asana_task_id"
        echo "asana_task_id=$asana_task_id" >> $GITHUB_ENV

    - name: Update Asana Task
      run: |
        asana_task_id=${{ env.asana_task_id }}
        echo "Updating Asana Task ID: $asana_task_id"
        
        if [ "${{ github.event.pull_request.merged }}" == "true" ]; then
          status="Pull Request has been merged."
          status_field="1205222382328469"
        else
          status="Pull Request has been closed."
          status_field="1205222382328469"
        fi

        curl -X PUT https://app.asana.com/api/1.0/tasks/$asana_task_id \
          -H "Authorization: Bearer 2/1206370253774697/1207905742780138:8d2035b60ee02493ca800700970a18f6" \
          -H "Content-Type: application/json" \
          -d "{
                \"data\": {
                  \"notes\": \"$status\",
                  \"custom_fields\": {
                    \"1205222382328468\": \"$status_field\"
                  }
                }
              }"
